// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/conversation/v1/conversation.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reference struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DocumentId        string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentVersionId string                 `protobuf:"bytes,2,opt,name=document_version_id,json=documentVersionId,proto3" json:"document_version_id,omitempty"`
	ChunkId           string                 `protobuf:"bytes,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Score             float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	Rank              int32                  `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	Snippet           string                 `protobuf:"bytes,6,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_api_conversation_v1_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *Reference) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Reference) GetDocumentVersionId() string {
	if x != nil {
		return x.DocumentVersionId
	}
	return ""
}

func (x *Reference) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Reference) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Reference) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Reference) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	References    []*Reference           `protobuf:"bytes,6,rep,name=references,proto3" json:"references,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_conversation_v1_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Message) GetReferences() []*Reference {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Session struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BotId          string                 `protobuf:"bytes,3,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CloseReason    string                 `protobuf:"bytes,5,opt,name=close_reason,json=closeReason,proto3" json:"close_reason,omitempty"`
	UserExternalId string                 `protobuf:"bytes,6,opt,name=user_external_id,json=userExternalId,proto3" json:"user_external_id,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ClosedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_conversation_v1_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Session) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *Session) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Session) GetCloseReason() string {
	if x != nil {
		return x.CloseReason
	}
	return ""
}

func (x *Session) GetUserExternalId() string {
	if x != nil {
		return x.UserExternalId
	}
	return ""
}

func (x *Session) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Session) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

type CreateSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserExternalId string                 `protobuf:"bytes,2,opt,name=user_external_id,json=userExternalId,proto3" json:"user_external_id,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_conversation_v1_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSessionRequest) GetUserExternalId() string {
	if x != nil {
		return x.UserExternalId
	}
	return ""
}

func (x *CreateSessionRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_conversation_v1_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetSessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IncludeMessages bool                   `protobuf:"varint,2,opt,name=include_messages,json=includeMessages,proto3" json:"include_messages,omitempty"`
	Limit           int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset          int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_conversation_v1_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionRequest) GetIncludeMessages() bool {
	if x != nil {
		return x.IncludeMessages
	}
	return false
}

func (x *GetSessionRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetSessionRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_conversation_v1_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetSessionResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CloseReason   string                 `protobuf:"bytes,2,opt,name=close_reason,json=closeReason,proto3" json:"close_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_conversation_v1_conversation_proto_rawDescGZIP(), []int{7}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CloseSessionRequest) GetCloseReason() string {
	if x != nil {
		return x.CloseReason
	}
	return ""
}

type CreateFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Correction    string                 `protobuf:"bytes,5,opt,name=correction,proto3" json:"correction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedbackRequest) Reset() {
	*x = CreateFeedbackRequest{}
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedbackRequest) ProtoMessage() {}

func (x *CreateFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedbackRequest.ProtoReflect.Descriptor instead.
func (*CreateFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_api_conversation_v1_conversation_proto_rawDescGZIP(), []int{8}
}

func (x *CreateFeedbackRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateFeedbackRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *CreateFeedbackRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateFeedbackRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CreateFeedbackRequest) GetCorrection() string {
	if x != nil {
		return x.Correction
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_conversation_v1_conversation_proto_rawDescGZIP(), []int{9}
}

func (x *ListSessionsRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *ListSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSessionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_conversation_v1_conversation_proto_rawDescGZIP(), []int{10}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type ListMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_conversation_v1_conversation_proto_rawDescGZIP(), []int{11}
}

func (x *ListMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMessagesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_conversation_v1_conversation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_conversation_v1_conversation_proto_rawDescGZIP(), []int{12}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_api_conversation_v1_conversation_proto protoreflect.FileDescriptor

const file_api_conversation_v1_conversation_proto_rawDesc = "" +
	"\n" +
	"&api/conversation/v1/conversation.proto\x12\x13api.conversation.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\tReference\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12.\n" +
	"\x13document_version_id\x18\x02 \x01(\tR\x11documentVersionId\x12\x19\n" +
	"\bchunk_id\x18\x03 \x01(\tR\achunkId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x05R\x04rank\x12\x18\n" +
	"\asnippet\x18\x06 \x01(\tR\asnippet\"\x81\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12>\n" +
	"\n" +
	"references\x18\x06 \x03(\v2\x1e.api.conversation.v1.ReferenceR\n" +
	"references\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x96\x03\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x15\n" +
	"\x06bot_id\x18\x03 \x01(\tR\x05botId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\fclose_reason\x18\x05 \x01(\tR\vcloseReason\x12(\n" +
	"\x10user_external_id\x18\x06 \x01(\tR\x0euserExternalId\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\tclosed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\"{\n" +
	"\x14CreateSessionRequest\x12(\n" +
	"\x10user_external_id\x18\x02 \x01(\tR\x0euserExternalId\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadataJ\x04\b\x01\x10\x02\"O\n" +
	"\x15CreateSessionResponse\x126\n" +
	"\asession\x18\x01 \x01(\v2\x1c.api.conversation.v1.SessionR\asession\"\x8b\x01\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x10include_messages\x18\x02 \x01(\bR\x0fincludeMessages\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\x86\x01\n" +
	"\x12GetSessionResponse\x126\n" +
	"\asession\x18\x01 \x01(\v2\x1c.api.conversation.v1.SessionR\asession\x128\n" +
	"\bmessages\x18\x02 \x03(\v2\x1c.api.conversation.v1.MessageR\bmessages\"W\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fclose_reason\x18\x02 \x01(\tR\vcloseReason\"\xa7\x01\n" +
	"\x15CreateFeedbackRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x1e\n" +
	"\n" +
	"correction\x18\x05 \x01(\tR\n" +
	"correction\"Z\n" +
	"\x13ListSessionsRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"P\n" +
	"\x14ListSessionsResponse\x128\n" +
	"\bsessions\x18\x01 \x03(\v2\x1c.api.conversation.v1.SessionR\bsessions\"b\n" +
	"\x13ListMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"P\n" +
	"\x14ListMessagesResponse\x128\n" +
	"\bmessages\x18\x01 \x03(\v2\x1c.api.conversation.v1.MessageR\bmessages2\x8d\x04\n" +
	"\fConversation\x12\x82\x01\n" +
	"\rCreateSession\x12).api.conversation.v1.CreateSessionRequest\x1a*.api.conversation.v1.CreateSessionResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/session\x12\x83\x01\n" +
	"\n" +
	"GetSession\x12&.api.conversation.v1.GetSessionRequest\x1a'.api.conversation.v1.GetSessionResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/session/{session_id}\x12\x7f\n" +
	"\fCloseSession\x12(.api.conversation.v1.CloseSessionRequest\x1a\x16.google.protobuf.Empty\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/api/v1/session/{session_id}/close\x12q\n" +
	"\x0eCreateFeedback\x12*.api.conversation.v1.CreateFeedbackRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/feedback2\xb3\x02\n" +
	"\x13ConsoleConversation\x12\x81\x01\n" +
	"\fListSessions\x12(.api.conversation.v1.ListSessionsRequest\x1a).api.conversation.v1.ListSessionsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/console/v1/sessions\x12\x97\x01\n" +
	"\fListMessages\x12(.api.conversation.v1.ListMessagesRequest\x1a).api.conversation.v1.ListMessagesResponse\"2\x82\xd3\xe4\x93\x02,\x12*/console/v1/sessions/{session_id}/messagesB=Z;github.com/ZTH7/RagoDesk/apps/server/api/conversation/v1;v1b\x06proto3"

var (
	file_api_conversation_v1_conversation_proto_rawDescOnce sync.Once
	file_api_conversation_v1_conversation_proto_rawDescData []byte
)

func file_api_conversation_v1_conversation_proto_rawDescGZIP() []byte {
	file_api_conversation_v1_conversation_proto_rawDescOnce.Do(func() {
		file_api_conversation_v1_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_conversation_v1_conversation_proto_rawDesc), len(file_api_conversation_v1_conversation_proto_rawDesc)))
	})
	return file_api_conversation_v1_conversation_proto_rawDescData
}

var file_api_conversation_v1_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_conversation_v1_conversation_proto_goTypes = []any{
	(*Reference)(nil),             // 0: api.conversation.v1.Reference
	(*Message)(nil),               // 1: api.conversation.v1.Message
	(*Session)(nil),               // 2: api.conversation.v1.Session
	(*CreateSessionRequest)(nil),  // 3: api.conversation.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 4: api.conversation.v1.CreateSessionResponse
	(*GetSessionRequest)(nil),     // 5: api.conversation.v1.GetSessionRequest
	(*GetSessionResponse)(nil),    // 6: api.conversation.v1.GetSessionResponse
	(*CloseSessionRequest)(nil),   // 7: api.conversation.v1.CloseSessionRequest
	(*CreateFeedbackRequest)(nil), // 8: api.conversation.v1.CreateFeedbackRequest
	(*ListSessionsRequest)(nil),   // 9: api.conversation.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),  // 10: api.conversation.v1.ListSessionsResponse
	(*ListMessagesRequest)(nil),   // 11: api.conversation.v1.ListMessagesRequest
	(*ListMessagesResponse)(nil),  // 12: api.conversation.v1.ListMessagesResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 14: google.protobuf.Struct
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_api_conversation_v1_conversation_proto_depIdxs = []int32{
	0,  // 0: api.conversation.v1.Message.references:type_name -> api.conversation.v1.Reference
	13, // 1: api.conversation.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: api.conversation.v1.Session.metadata:type_name -> google.protobuf.Struct
	13, // 3: api.conversation.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	13, // 4: api.conversation.v1.Session.updated_at:type_name -> google.protobuf.Timestamp
	13, // 5: api.conversation.v1.Session.closed_at:type_name -> google.protobuf.Timestamp
	14, // 6: api.conversation.v1.CreateSessionRequest.metadata:type_name -> google.protobuf.Struct
	2,  // 7: api.conversation.v1.CreateSessionResponse.session:type_name -> api.conversation.v1.Session
	2,  // 8: api.conversation.v1.GetSessionResponse.session:type_name -> api.conversation.v1.Session
	1,  // 9: api.conversation.v1.GetSessionResponse.messages:type_name -> api.conversation.v1.Message
	2,  // 10: api.conversation.v1.ListSessionsResponse.sessions:type_name -> api.conversation.v1.Session
	1,  // 11: api.conversation.v1.ListMessagesResponse.messages:type_name -> api.conversation.v1.Message
	3,  // 12: api.conversation.v1.Conversation.CreateSession:input_type -> api.conversation.v1.CreateSessionRequest
	5,  // 13: api.conversation.v1.Conversation.GetSession:input_type -> api.conversation.v1.GetSessionRequest
	7,  // 14: api.conversation.v1.Conversation.CloseSession:input_type -> api.conversation.v1.CloseSessionRequest
	8,  // 15: api.conversation.v1.Conversation.CreateFeedback:input_type -> api.conversation.v1.CreateFeedbackRequest
	9,  // 16: api.conversation.v1.ConsoleConversation.ListSessions:input_type -> api.conversation.v1.ListSessionsRequest
	11, // 17: api.conversation.v1.ConsoleConversation.ListMessages:input_type -> api.conversation.v1.ListMessagesRequest
	4,  // 18: api.conversation.v1.Conversation.CreateSession:output_type -> api.conversation.v1.CreateSessionResponse
	6,  // 19: api.conversation.v1.Conversation.GetSession:output_type -> api.conversation.v1.GetSessionResponse
	15, // 20: api.conversation.v1.Conversation.CloseSession:output_type -> google.protobuf.Empty
	15, // 21: api.conversation.v1.Conversation.CreateFeedback:output_type -> google.protobuf.Empty
	10, // 22: api.conversation.v1.ConsoleConversation.ListSessions:output_type -> api.conversation.v1.ListSessionsResponse
	12, // 23: api.conversation.v1.ConsoleConversation.ListMessages:output_type -> api.conversation.v1.ListMessagesResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_conversation_v1_conversation_proto_init() }
func file_api_conversation_v1_conversation_proto_init() {
	if File_api_conversation_v1_conversation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_conversation_v1_conversation_proto_rawDesc), len(file_api_conversation_v1_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_conversation_v1_conversation_proto_goTypes,
		DependencyIndexes: file_api_conversation_v1_conversation_proto_depIdxs,
		MessageInfos:      file_api_conversation_v1_conversation_proto_msgTypes,
	}.Build()
	File_api_conversation_v1_conversation_proto = out.File
	file_api_conversation_v1_conversation_proto_goTypes = nil
	file_api_conversation_v1_conversation_proto_depIdxs = nil
}
