// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/knowledge/v1/admin_knowledge.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KnowledgeBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeBase) Reset() {
	*x = KnowledgeBase{}
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeBase) ProtoMessage() {}

func (x *KnowledgeBase) ProtoReflect() protoreflect.Message {
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeBase.ProtoReflect.Descriptor instead.
func (*KnowledgeBase) Descriptor() ([]byte, []int) {
	return file_api_knowledge_v1_admin_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *KnowledgeBase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeBase) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *KnowledgeBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KnowledgeBase) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KnowledgeBase) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KnowledgeBase) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Document struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	KbId           string                 `protobuf:"bytes,3,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	SourceType     string                 `protobuf:"bytes,5,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CurrentVersion int32                  `protobuf:"varint,7,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_api_knowledge_v1_admin_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Document) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *Document) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Document) GetCurrentVersion() int32 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DocumentVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentVersion) Reset() {
	*x = DocumentVersion{}
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentVersion) ProtoMessage() {}

func (x *DocumentVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentVersion.ProtoReflect.Descriptor instead.
func (*DocumentVersion) Descriptor() ([]byte, []int) {
	return file_api_knowledge_v1_admin_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentVersion) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DocumentVersion) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentVersion) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DocumentVersion) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DocumentVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateKnowledgeBaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKnowledgeBaseRequest) Reset() {
	*x = CreateKnowledgeBaseRequest{}
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeBaseRequest) ProtoMessage() {}

func (x *CreateKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_api_knowledge_v1_admin_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *CreateKnowledgeBaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKnowledgeBaseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetKnowledgeBaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeBaseRequest) Reset() {
	*x = GetKnowledgeBaseRequest{}
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeBaseRequest) ProtoMessage() {}

func (x *GetKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*GetKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_api_knowledge_v1_admin_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *GetKnowledgeBaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListKnowledgeBasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnowledgeBasesRequest) Reset() {
	*x = ListKnowledgeBasesRequest{}
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgeBasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeBasesRequest) ProtoMessage() {}

func (x *ListKnowledgeBasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeBasesRequest.ProtoReflect.Descriptor instead.
func (*ListKnowledgeBasesRequest) Descriptor() ([]byte, []int) {
	return file_api_knowledge_v1_admin_knowledge_proto_rawDescGZIP(), []int{5}
}

type ListKnowledgeBasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KnowledgeBase       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnowledgeBasesResponse) Reset() {
	*x = ListKnowledgeBasesResponse{}
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgeBasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeBasesResponse) ProtoMessage() {}

func (x *ListKnowledgeBasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeBasesResponse.ProtoReflect.Descriptor instead.
func (*ListKnowledgeBasesResponse) Descriptor() ([]byte, []int) {
	return file_api_knowledge_v1_admin_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *ListKnowledgeBasesResponse) GetItems() []*KnowledgeBase {
	if x != nil {
		return x.Items
	}
	return nil
}

type KnowledgeBaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeBase *KnowledgeBase         `protobuf:"bytes,1,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeBaseResponse) Reset() {
	*x = KnowledgeBaseResponse{}
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeBaseResponse) ProtoMessage() {}

func (x *KnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*KnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_api_knowledge_v1_admin_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *KnowledgeBaseResponse) GetKnowledgeBase() *KnowledgeBase {
	if x != nil {
		return x.KnowledgeBase
	}
	return nil
}

type UploadDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KbId          string                 `protobuf:"bytes,1,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SourceType    string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentRequest) Reset() {
	*x = UploadDocumentRequest{}
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentRequest) ProtoMessage() {}

func (x *UploadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentRequest.ProtoReflect.Descriptor instead.
func (*UploadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_knowledge_v1_admin_knowledge_proto_rawDescGZIP(), []int{8}
}

func (x *UploadDocumentRequest) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

func (x *UploadDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadDocumentRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *UploadDocumentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UploadDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Version       *DocumentVersion       `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentResponse) Reset() {
	*x = UploadDocumentResponse{}
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentResponse) ProtoMessage() {}

func (x *UploadDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentResponse.ProtoReflect.Descriptor instead.
func (*UploadDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_knowledge_v1_admin_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *UploadDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *UploadDocumentResponse) GetVersion() *DocumentVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_knowledge_v1_admin_knowledge_proto_rawDescGZIP(), []int{10}
}

func (x *GetDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Versions      []*DocumentVersion     `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_knowledge_v1_admin_knowledge_proto_rawDescGZIP(), []int{11}
}

func (x *GetDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *GetDocumentResponse) GetVersions() []*DocumentVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type ReindexDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexDocumentRequest) Reset() {
	*x = ReindexDocumentRequest{}
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexDocumentRequest) ProtoMessage() {}

func (x *ReindexDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexDocumentRequest.ProtoReflect.Descriptor instead.
func (*ReindexDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_knowledge_v1_admin_knowledge_proto_rawDescGZIP(), []int{12}
}

func (x *ReindexDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RollbackDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackDocumentRequest) Reset() {
	*x = RollbackDocumentRequest{}
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackDocumentRequest) ProtoMessage() {}

func (x *RollbackDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_knowledge_v1_admin_knowledge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackDocumentRequest.ProtoReflect.Descriptor instead.
func (*RollbackDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_knowledge_v1_admin_knowledge_proto_rawDescGZIP(), []int{13}
}

func (x *RollbackDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RollbackDocumentRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_api_knowledge_v1_admin_knowledge_proto protoreflect.FileDescriptor

const file_api_knowledge_v1_admin_knowledge_proto_rawDesc = "" +
	"\n" +
	"&api/knowledge/v1/admin_knowledge.proto\x12\x10api.knowledge.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x01\n" +
	"\rKnowledgeBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xba\x02\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x13\n" +
	"\x05kb_id\x18\x03 \x01(\tR\x04kbId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1f\n" +
	"\vsource_type\x18\x05 \x01(\tR\n" +
	"sourceType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12'\n" +
	"\x0fcurrent_version\x18\a \x01(\x05R\x0ecurrentVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xcc\x01\n" +
	"\x0fDocumentVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"R\n" +
	"\x1aCreateKnowledgeBaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\")\n" +
	"\x17GetKnowledgeBaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19ListKnowledgeBasesRequest\"S\n" +
	"\x1aListKnowledgeBasesResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.api.knowledge.v1.KnowledgeBaseR\x05items\"_\n" +
	"\x15KnowledgeBaseResponse\x12F\n" +
	"\x0eknowledge_base\x18\x01 \x01(\v2\x1f.api.knowledge.v1.KnowledgeBaseR\rknowledgeBase\"}\n" +
	"\x15UploadDocumentRequest\x12\x13\n" +
	"\x05kb_id\x18\x01 \x01(\tR\x04kbId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"\x8d\x01\n" +
	"\x16UploadDocumentResponse\x126\n" +
	"\bdocument\x18\x01 \x01(\v2\x1a.api.knowledge.v1.DocumentR\bdocument\x12;\n" +
	"\aversion\x18\x02 \x01(\v2!.api.knowledge.v1.DocumentVersionR\aversion\"$\n" +
	"\x12GetDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8c\x01\n" +
	"\x13GetDocumentResponse\x126\n" +
	"\bdocument\x18\x01 \x01(\v2\x1a.api.knowledge.v1.DocumentR\bdocument\x12=\n" +
	"\bversions\x18\x02 \x03(\v2!.api.knowledge.v1.DocumentVersionR\bversions\"(\n" +
	"\x16ReindexDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x17RollbackDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion2\xdf\a\n" +
	"\x0eKnowledgeAdmin\x12\x92\x01\n" +
	"\x13CreateKnowledgeBase\x12,.api.knowledge.v1.CreateKnowledgeBaseRequest\x1a'.api.knowledge.v1.KnowledgeBaseResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/admin/v1/knowledge_bases\x12\x8e\x01\n" +
	"\x10GetKnowledgeBase\x12).api.knowledge.v1.GetKnowledgeBaseRequest\x1a'.api.knowledge.v1.KnowledgeBaseResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/admin/v1/knowledge_bases/{id}\x12\x92\x01\n" +
	"\x12ListKnowledgeBases\x12+.api.knowledge.v1.ListKnowledgeBasesRequest\x1a,.api.knowledge.v1.ListKnowledgeBasesResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/admin/v1/knowledge_bases\x12\x8a\x01\n" +
	"\x0eUploadDocument\x12'.api.knowledge.v1.UploadDocumentRequest\x1a(.api.knowledge.v1.UploadDocumentResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/admin/v1/documents/upload\x12|\n" +
	"\vGetDocument\x12$.api.knowledge.v1.GetDocumentRequest\x1a%.api.knowledge.v1.GetDocumentResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/admin/v1/documents/{id}\x12\x80\x01\n" +
	"\x0fReindexDocument\x12(.api.knowledge.v1.ReindexDocumentRequest\x1a\x16.google.protobuf.Empty\"+\x82\xd3\xe4\x93\x02%:\x01*\" /admin/v1/documents/{id}/reindex\x12\x83\x01\n" +
	"\x10RollbackDocument\x12).api.knowledge.v1.RollbackDocumentRequest\x1a\x16.google.protobuf.Empty\",\x82\xd3\xe4\x93\x02&:\x01*\"!/admin/v1/documents/{id}/rollbackB9Z7github.com/ZTH7/RAGDesk/apps/server/api/knowledge/v1;v1b\x06proto3"

var (
	file_api_knowledge_v1_admin_knowledge_proto_rawDescOnce sync.Once
	file_api_knowledge_v1_admin_knowledge_proto_rawDescData []byte
)

func file_api_knowledge_v1_admin_knowledge_proto_rawDescGZIP() []byte {
	file_api_knowledge_v1_admin_knowledge_proto_rawDescOnce.Do(func() {
		file_api_knowledge_v1_admin_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_knowledge_v1_admin_knowledge_proto_rawDesc), len(file_api_knowledge_v1_admin_knowledge_proto_rawDesc)))
	})
	return file_api_knowledge_v1_admin_knowledge_proto_rawDescData
}

var file_api_knowledge_v1_admin_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_knowledge_v1_admin_knowledge_proto_goTypes = []any{
	(*KnowledgeBase)(nil),              // 0: api.knowledge.v1.KnowledgeBase
	(*Document)(nil),                   // 1: api.knowledge.v1.Document
	(*DocumentVersion)(nil),            // 2: api.knowledge.v1.DocumentVersion
	(*CreateKnowledgeBaseRequest)(nil), // 3: api.knowledge.v1.CreateKnowledgeBaseRequest
	(*GetKnowledgeBaseRequest)(nil),    // 4: api.knowledge.v1.GetKnowledgeBaseRequest
	(*ListKnowledgeBasesRequest)(nil),  // 5: api.knowledge.v1.ListKnowledgeBasesRequest
	(*ListKnowledgeBasesResponse)(nil), // 6: api.knowledge.v1.ListKnowledgeBasesResponse
	(*KnowledgeBaseResponse)(nil),      // 7: api.knowledge.v1.KnowledgeBaseResponse
	(*UploadDocumentRequest)(nil),      // 8: api.knowledge.v1.UploadDocumentRequest
	(*UploadDocumentResponse)(nil),     // 9: api.knowledge.v1.UploadDocumentResponse
	(*GetDocumentRequest)(nil),         // 10: api.knowledge.v1.GetDocumentRequest
	(*GetDocumentResponse)(nil),        // 11: api.knowledge.v1.GetDocumentResponse
	(*ReindexDocumentRequest)(nil),     // 12: api.knowledge.v1.ReindexDocumentRequest
	(*RollbackDocumentRequest)(nil),    // 13: api.knowledge.v1.RollbackDocumentRequest
	(*timestamppb.Timestamp)(nil),      // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 15: google.protobuf.Empty
}
var file_api_knowledge_v1_admin_knowledge_proto_depIdxs = []int32{
	14, // 0: api.knowledge.v1.KnowledgeBase.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: api.knowledge.v1.KnowledgeBase.updated_at:type_name -> google.protobuf.Timestamp
	14, // 2: api.knowledge.v1.Document.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: api.knowledge.v1.Document.updated_at:type_name -> google.protobuf.Timestamp
	14, // 4: api.knowledge.v1.DocumentVersion.created_at:type_name -> google.protobuf.Timestamp
	0,  // 5: api.knowledge.v1.ListKnowledgeBasesResponse.items:type_name -> api.knowledge.v1.KnowledgeBase
	0,  // 6: api.knowledge.v1.KnowledgeBaseResponse.knowledge_base:type_name -> api.knowledge.v1.KnowledgeBase
	1,  // 7: api.knowledge.v1.UploadDocumentResponse.document:type_name -> api.knowledge.v1.Document
	2,  // 8: api.knowledge.v1.UploadDocumentResponse.version:type_name -> api.knowledge.v1.DocumentVersion
	1,  // 9: api.knowledge.v1.GetDocumentResponse.document:type_name -> api.knowledge.v1.Document
	2,  // 10: api.knowledge.v1.GetDocumentResponse.versions:type_name -> api.knowledge.v1.DocumentVersion
	3,  // 11: api.knowledge.v1.KnowledgeAdmin.CreateKnowledgeBase:input_type -> api.knowledge.v1.CreateKnowledgeBaseRequest
	4,  // 12: api.knowledge.v1.KnowledgeAdmin.GetKnowledgeBase:input_type -> api.knowledge.v1.GetKnowledgeBaseRequest
	5,  // 13: api.knowledge.v1.KnowledgeAdmin.ListKnowledgeBases:input_type -> api.knowledge.v1.ListKnowledgeBasesRequest
	8,  // 14: api.knowledge.v1.KnowledgeAdmin.UploadDocument:input_type -> api.knowledge.v1.UploadDocumentRequest
	10, // 15: api.knowledge.v1.KnowledgeAdmin.GetDocument:input_type -> api.knowledge.v1.GetDocumentRequest
	12, // 16: api.knowledge.v1.KnowledgeAdmin.ReindexDocument:input_type -> api.knowledge.v1.ReindexDocumentRequest
	13, // 17: api.knowledge.v1.KnowledgeAdmin.RollbackDocument:input_type -> api.knowledge.v1.RollbackDocumentRequest
	7,  // 18: api.knowledge.v1.KnowledgeAdmin.CreateKnowledgeBase:output_type -> api.knowledge.v1.KnowledgeBaseResponse
	7,  // 19: api.knowledge.v1.KnowledgeAdmin.GetKnowledgeBase:output_type -> api.knowledge.v1.KnowledgeBaseResponse
	6,  // 20: api.knowledge.v1.KnowledgeAdmin.ListKnowledgeBases:output_type -> api.knowledge.v1.ListKnowledgeBasesResponse
	9,  // 21: api.knowledge.v1.KnowledgeAdmin.UploadDocument:output_type -> api.knowledge.v1.UploadDocumentResponse
	11, // 22: api.knowledge.v1.KnowledgeAdmin.GetDocument:output_type -> api.knowledge.v1.GetDocumentResponse
	15, // 23: api.knowledge.v1.KnowledgeAdmin.ReindexDocument:output_type -> google.protobuf.Empty
	15, // 24: api.knowledge.v1.KnowledgeAdmin.RollbackDocument:output_type -> google.protobuf.Empty
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_knowledge_v1_admin_knowledge_proto_init() }
func file_api_knowledge_v1_admin_knowledge_proto_init() {
	if File_api_knowledge_v1_admin_knowledge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_knowledge_v1_admin_knowledge_proto_rawDesc), len(file_api_knowledge_v1_admin_knowledge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_knowledge_v1_admin_knowledge_proto_goTypes,
		DependencyIndexes: file_api_knowledge_v1_admin_knowledge_proto_depIdxs,
		MessageInfos:      file_api_knowledge_v1_admin_knowledge_proto_msgTypes,
	}.Build()
	File_api_knowledge_v1_admin_knowledge_proto = out.File
	file_api_knowledge_v1_admin_knowledge_proto_goTypes = nil
	file_api_knowledge_v1_admin_knowledge_proto_depIdxs = nil
}
