// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0--rc2
// source: api/knowledge/v1/admin_knowledge.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationKnowledgeAdminBindBotKnowledgeBase = "/api.knowledge.v1.KnowledgeAdmin/BindBotKnowledgeBase"
const OperationKnowledgeAdminCreateKnowledgeBase = "/api.knowledge.v1.KnowledgeAdmin/CreateKnowledgeBase"
const OperationKnowledgeAdminDeleteKnowledgeBase = "/api.knowledge.v1.KnowledgeAdmin/DeleteKnowledgeBase"
const OperationKnowledgeAdminGetDocument = "/api.knowledge.v1.KnowledgeAdmin/GetDocument"
const OperationKnowledgeAdminGetKnowledgeBase = "/api.knowledge.v1.KnowledgeAdmin/GetKnowledgeBase"
const OperationKnowledgeAdminListBotKnowledgeBases = "/api.knowledge.v1.KnowledgeAdmin/ListBotKnowledgeBases"
const OperationKnowledgeAdminListKnowledgeBases = "/api.knowledge.v1.KnowledgeAdmin/ListKnowledgeBases"
const OperationKnowledgeAdminReindexDocument = "/api.knowledge.v1.KnowledgeAdmin/ReindexDocument"
const OperationKnowledgeAdminRollbackDocument = "/api.knowledge.v1.KnowledgeAdmin/RollbackDocument"
const OperationKnowledgeAdminUnbindBotKnowledgeBase = "/api.knowledge.v1.KnowledgeAdmin/UnbindBotKnowledgeBase"
const OperationKnowledgeAdminUpdateKnowledgeBase = "/api.knowledge.v1.KnowledgeAdmin/UpdateKnowledgeBase"
const OperationKnowledgeAdminUploadDocument = "/api.knowledge.v1.KnowledgeAdmin/UploadDocument"

type KnowledgeAdminHTTPServer interface {
	BindBotKnowledgeBase(context.Context, *BindBotKnowledgeBaseRequest) (*BotKnowledgeBaseResponse, error)
	CreateKnowledgeBase(context.Context, *CreateKnowledgeBaseRequest) (*KnowledgeBaseResponse, error)
	DeleteKnowledgeBase(context.Context, *DeleteKnowledgeBaseRequest) (*emptypb.Empty, error)
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	GetKnowledgeBase(context.Context, *GetKnowledgeBaseRequest) (*KnowledgeBaseResponse, error)
	ListBotKnowledgeBases(context.Context, *ListBotKnowledgeBasesRequest) (*ListBotKnowledgeBasesResponse, error)
	ListKnowledgeBases(context.Context, *ListKnowledgeBasesRequest) (*ListKnowledgeBasesResponse, error)
	ReindexDocument(context.Context, *ReindexDocumentRequest) (*emptypb.Empty, error)
	RollbackDocument(context.Context, *RollbackDocumentRequest) (*emptypb.Empty, error)
	UnbindBotKnowledgeBase(context.Context, *UnbindBotKnowledgeBaseRequest) (*emptypb.Empty, error)
	UpdateKnowledgeBase(context.Context, *UpdateKnowledgeBaseRequest) (*KnowledgeBaseResponse, error)
	UploadDocument(context.Context, *UploadDocumentRequest) (*UploadDocumentResponse, error)
}

func RegisterKnowledgeAdminHTTPServer(s *http.Server, srv KnowledgeAdminHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/v1/knowledge_bases", _KnowledgeAdmin_CreateKnowledgeBase0_HTTP_Handler(srv))
	r.GET("/admin/v1/knowledge_bases/{id}", _KnowledgeAdmin_GetKnowledgeBase0_HTTP_Handler(srv))
	r.PATCH("/admin/v1/knowledge_bases/{id}", _KnowledgeAdmin_UpdateKnowledgeBase0_HTTP_Handler(srv))
	r.DELETE("/admin/v1/knowledge_bases/{id}", _KnowledgeAdmin_DeleteKnowledgeBase0_HTTP_Handler(srv))
	r.GET("/admin/v1/knowledge_bases", _KnowledgeAdmin_ListKnowledgeBases0_HTTP_Handler(srv))
	r.GET("/admin/v1/bots/{bot_id}/knowledge_bases", _KnowledgeAdmin_ListBotKnowledgeBases0_HTTP_Handler(srv))
	r.POST("/admin/v1/bots/{bot_id}/knowledge_bases", _KnowledgeAdmin_BindBotKnowledgeBase0_HTTP_Handler(srv))
	r.DELETE("/admin/v1/bots/{bot_id}/knowledge_bases/{kb_id}", _KnowledgeAdmin_UnbindBotKnowledgeBase0_HTTP_Handler(srv))
	r.POST("/admin/v1/documents/upload", _KnowledgeAdmin_UploadDocument0_HTTP_Handler(srv))
	r.GET("/admin/v1/documents/{id}", _KnowledgeAdmin_GetDocument0_HTTP_Handler(srv))
	r.POST("/admin/v1/documents/{id}/reindex", _KnowledgeAdmin_ReindexDocument0_HTTP_Handler(srv))
	r.POST("/admin/v1/documents/{id}/rollback", _KnowledgeAdmin_RollbackDocument0_HTTP_Handler(srv))
}

func _KnowledgeAdmin_CreateKnowledgeBase0_HTTP_Handler(srv KnowledgeAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateKnowledgeBaseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeAdminCreateKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateKnowledgeBase(ctx, req.(*CreateKnowledgeBaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KnowledgeBaseResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeAdmin_GetKnowledgeBase0_HTTP_Handler(srv KnowledgeAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetKnowledgeBaseRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeAdminGetKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetKnowledgeBase(ctx, req.(*GetKnowledgeBaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KnowledgeBaseResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeAdmin_UpdateKnowledgeBase0_HTTP_Handler(srv KnowledgeAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateKnowledgeBaseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeAdminUpdateKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateKnowledgeBase(ctx, req.(*UpdateKnowledgeBaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KnowledgeBaseResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeAdmin_DeleteKnowledgeBase0_HTTP_Handler(srv KnowledgeAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteKnowledgeBaseRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeAdminDeleteKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteKnowledgeBase(ctx, req.(*DeleteKnowledgeBaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeAdmin_ListKnowledgeBases0_HTTP_Handler(srv KnowledgeAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListKnowledgeBasesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeAdminListKnowledgeBases)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListKnowledgeBases(ctx, req.(*ListKnowledgeBasesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListKnowledgeBasesResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeAdmin_ListBotKnowledgeBases0_HTTP_Handler(srv KnowledgeAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBotKnowledgeBasesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeAdminListBotKnowledgeBases)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBotKnowledgeBases(ctx, req.(*ListBotKnowledgeBasesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBotKnowledgeBasesResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeAdmin_BindBotKnowledgeBase0_HTTP_Handler(srv KnowledgeAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BindBotKnowledgeBaseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeAdminBindBotKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BindBotKnowledgeBase(ctx, req.(*BindBotKnowledgeBaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BotKnowledgeBaseResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeAdmin_UnbindBotKnowledgeBase0_HTTP_Handler(srv KnowledgeAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnbindBotKnowledgeBaseRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeAdminUnbindBotKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnbindBotKnowledgeBase(ctx, req.(*UnbindBotKnowledgeBaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeAdmin_UploadDocument0_HTTP_Handler(srv KnowledgeAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadDocumentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeAdminUploadDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadDocument(ctx, req.(*UploadDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadDocumentResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeAdmin_GetDocument0_HTTP_Handler(srv KnowledgeAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDocumentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeAdminGetDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDocument(ctx, req.(*GetDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDocumentResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeAdmin_ReindexDocument0_HTTP_Handler(srv KnowledgeAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReindexDocumentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeAdminReindexDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReindexDocument(ctx, req.(*ReindexDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeAdmin_RollbackDocument0_HTTP_Handler(srv KnowledgeAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RollbackDocumentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeAdminRollbackDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RollbackDocument(ctx, req.(*RollbackDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type KnowledgeAdminHTTPClient interface {
	BindBotKnowledgeBase(ctx context.Context, req *BindBotKnowledgeBaseRequest, opts ...http.CallOption) (rsp *BotKnowledgeBaseResponse, err error)
	CreateKnowledgeBase(ctx context.Context, req *CreateKnowledgeBaseRequest, opts ...http.CallOption) (rsp *KnowledgeBaseResponse, err error)
	DeleteKnowledgeBase(ctx context.Context, req *DeleteKnowledgeBaseRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetDocument(ctx context.Context, req *GetDocumentRequest, opts ...http.CallOption) (rsp *GetDocumentResponse, err error)
	GetKnowledgeBase(ctx context.Context, req *GetKnowledgeBaseRequest, opts ...http.CallOption) (rsp *KnowledgeBaseResponse, err error)
	ListBotKnowledgeBases(ctx context.Context, req *ListBotKnowledgeBasesRequest, opts ...http.CallOption) (rsp *ListBotKnowledgeBasesResponse, err error)
	ListKnowledgeBases(ctx context.Context, req *ListKnowledgeBasesRequest, opts ...http.CallOption) (rsp *ListKnowledgeBasesResponse, err error)
	ReindexDocument(ctx context.Context, req *ReindexDocumentRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	RollbackDocument(ctx context.Context, req *RollbackDocumentRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	UnbindBotKnowledgeBase(ctx context.Context, req *UnbindBotKnowledgeBaseRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	UpdateKnowledgeBase(ctx context.Context, req *UpdateKnowledgeBaseRequest, opts ...http.CallOption) (rsp *KnowledgeBaseResponse, err error)
	UploadDocument(ctx context.Context, req *UploadDocumentRequest, opts ...http.CallOption) (rsp *UploadDocumentResponse, err error)
}

type KnowledgeAdminHTTPClientImpl struct {
	cc *http.Client
}

func NewKnowledgeAdminHTTPClient(client *http.Client) KnowledgeAdminHTTPClient {
	return &KnowledgeAdminHTTPClientImpl{client}
}

func (c *KnowledgeAdminHTTPClientImpl) BindBotKnowledgeBase(ctx context.Context, in *BindBotKnowledgeBaseRequest, opts ...http.CallOption) (*BotKnowledgeBaseResponse, error) {
	var out BotKnowledgeBaseResponse
	pattern := "/admin/v1/bots/{bot_id}/knowledge_bases"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeAdminBindBotKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeAdminHTTPClientImpl) CreateKnowledgeBase(ctx context.Context, in *CreateKnowledgeBaseRequest, opts ...http.CallOption) (*KnowledgeBaseResponse, error) {
	var out KnowledgeBaseResponse
	pattern := "/admin/v1/knowledge_bases"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeAdminCreateKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeAdminHTTPClientImpl) DeleteKnowledgeBase(ctx context.Context, in *DeleteKnowledgeBaseRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/v1/knowledge_bases/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeAdminDeleteKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeAdminHTTPClientImpl) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...http.CallOption) (*GetDocumentResponse, error) {
	var out GetDocumentResponse
	pattern := "/admin/v1/documents/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeAdminGetDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeAdminHTTPClientImpl) GetKnowledgeBase(ctx context.Context, in *GetKnowledgeBaseRequest, opts ...http.CallOption) (*KnowledgeBaseResponse, error) {
	var out KnowledgeBaseResponse
	pattern := "/admin/v1/knowledge_bases/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeAdminGetKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeAdminHTTPClientImpl) ListBotKnowledgeBases(ctx context.Context, in *ListBotKnowledgeBasesRequest, opts ...http.CallOption) (*ListBotKnowledgeBasesResponse, error) {
	var out ListBotKnowledgeBasesResponse
	pattern := "/admin/v1/bots/{bot_id}/knowledge_bases"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeAdminListBotKnowledgeBases))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeAdminHTTPClientImpl) ListKnowledgeBases(ctx context.Context, in *ListKnowledgeBasesRequest, opts ...http.CallOption) (*ListKnowledgeBasesResponse, error) {
	var out ListKnowledgeBasesResponse
	pattern := "/admin/v1/knowledge_bases"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeAdminListKnowledgeBases))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeAdminHTTPClientImpl) ReindexDocument(ctx context.Context, in *ReindexDocumentRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/v1/documents/{id}/reindex"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeAdminReindexDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeAdminHTTPClientImpl) RollbackDocument(ctx context.Context, in *RollbackDocumentRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/v1/documents/{id}/rollback"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeAdminRollbackDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeAdminHTTPClientImpl) UnbindBotKnowledgeBase(ctx context.Context, in *UnbindBotKnowledgeBaseRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/v1/bots/{bot_id}/knowledge_bases/{kb_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeAdminUnbindBotKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeAdminHTTPClientImpl) UpdateKnowledgeBase(ctx context.Context, in *UpdateKnowledgeBaseRequest, opts ...http.CallOption) (*KnowledgeBaseResponse, error) {
	var out KnowledgeBaseResponse
	pattern := "/admin/v1/knowledge_bases/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeAdminUpdateKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeAdminHTTPClientImpl) UploadDocument(ctx context.Context, in *UploadDocumentRequest, opts ...http.CallOption) (*UploadDocumentResponse, error) {
	var out UploadDocumentResponse
	pattern := "/admin/v1/documents/upload"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeAdminUploadDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
