// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/knowledge/v1/console_knowledge.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationConsoleKnowledgeBindBotKnowledgeBase = "/api.knowledge.v1.ConsoleKnowledge/BindBotKnowledgeBase"
const OperationConsoleKnowledgeCreateKnowledgeBase = "/api.knowledge.v1.ConsoleKnowledge/CreateKnowledgeBase"
const OperationConsoleKnowledgeDeleteDocument = "/api.knowledge.v1.ConsoleKnowledge/DeleteDocument"
const OperationConsoleKnowledgeDeleteKnowledgeBase = "/api.knowledge.v1.ConsoleKnowledge/DeleteKnowledgeBase"
const OperationConsoleKnowledgeGetDocument = "/api.knowledge.v1.ConsoleKnowledge/GetDocument"
const OperationConsoleKnowledgeGetKnowledgeBase = "/api.knowledge.v1.ConsoleKnowledge/GetKnowledgeBase"
const OperationConsoleKnowledgeListBotKnowledgeBases = "/api.knowledge.v1.ConsoleKnowledge/ListBotKnowledgeBases"
const OperationConsoleKnowledgeListDocuments = "/api.knowledge.v1.ConsoleKnowledge/ListDocuments"
const OperationConsoleKnowledgeListKnowledgeBases = "/api.knowledge.v1.ConsoleKnowledge/ListKnowledgeBases"
const OperationConsoleKnowledgeReindexDocument = "/api.knowledge.v1.ConsoleKnowledge/ReindexDocument"
const OperationConsoleKnowledgeRollbackDocument = "/api.knowledge.v1.ConsoleKnowledge/RollbackDocument"
const OperationConsoleKnowledgeUnbindBotKnowledgeBase = "/api.knowledge.v1.ConsoleKnowledge/UnbindBotKnowledgeBase"
const OperationConsoleKnowledgeUpdateDocument = "/api.knowledge.v1.ConsoleKnowledge/UpdateDocument"
const OperationConsoleKnowledgeUpdateKnowledgeBase = "/api.knowledge.v1.ConsoleKnowledge/UpdateKnowledgeBase"
const OperationConsoleKnowledgeUploadDocument = "/api.knowledge.v1.ConsoleKnowledge/UploadDocument"

type ConsoleKnowledgeHTTPServer interface {
	BindBotKnowledgeBase(context.Context, *BindBotKnowledgeBaseRequest) (*BotKnowledgeBaseResponse, error)
	CreateKnowledgeBase(context.Context, *CreateKnowledgeBaseRequest) (*KnowledgeBaseResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*emptypb.Empty, error)
	DeleteKnowledgeBase(context.Context, *DeleteKnowledgeBaseRequest) (*emptypb.Empty, error)
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	GetKnowledgeBase(context.Context, *GetKnowledgeBaseRequest) (*KnowledgeBaseResponse, error)
	ListBotKnowledgeBases(context.Context, *ListBotKnowledgeBasesRequest) (*ListBotKnowledgeBasesResponse, error)
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	ListKnowledgeBases(context.Context, *ListKnowledgeBasesRequest) (*ListKnowledgeBasesResponse, error)
	ReindexDocument(context.Context, *ReindexDocumentRequest) (*emptypb.Empty, error)
	RollbackDocument(context.Context, *RollbackDocumentRequest) (*emptypb.Empty, error)
	UnbindBotKnowledgeBase(context.Context, *UnbindBotKnowledgeBaseRequest) (*emptypb.Empty, error)
	UpdateDocument(context.Context, *UpdateDocumentRequest) (*DocumentResponse, error)
	UpdateKnowledgeBase(context.Context, *UpdateKnowledgeBaseRequest) (*KnowledgeBaseResponse, error)
	UploadDocument(context.Context, *UploadDocumentRequest) (*UploadDocumentResponse, error)
}

func RegisterConsoleKnowledgeHTTPServer(s *http.Server, srv ConsoleKnowledgeHTTPServer) {
	r := s.Route("/")
	r.POST("/console/v1/knowledge_bases", _ConsoleKnowledge_CreateKnowledgeBase0_HTTP_Handler(srv))
	r.GET("/console/v1/knowledge_bases/{id}", _ConsoleKnowledge_GetKnowledgeBase0_HTTP_Handler(srv))
	r.PATCH("/console/v1/knowledge_bases/{id}", _ConsoleKnowledge_UpdateKnowledgeBase0_HTTP_Handler(srv))
	r.DELETE("/console/v1/knowledge_bases/{id}", _ConsoleKnowledge_DeleteKnowledgeBase0_HTTP_Handler(srv))
	r.GET("/console/v1/knowledge_bases", _ConsoleKnowledge_ListKnowledgeBases0_HTTP_Handler(srv))
	r.GET("/console/v1/documents", _ConsoleKnowledge_ListDocuments0_HTTP_Handler(srv))
	r.GET("/console/v1/bots/{bot_id}/knowledge_bases", _ConsoleKnowledge_ListBotKnowledgeBases0_HTTP_Handler(srv))
	r.POST("/console/v1/bots/{bot_id}/knowledge_bases", _ConsoleKnowledge_BindBotKnowledgeBase0_HTTP_Handler(srv))
	r.DELETE("/console/v1/bots/{bot_id}/knowledge_bases/{kb_id}", _ConsoleKnowledge_UnbindBotKnowledgeBase0_HTTP_Handler(srv))
	r.POST("/console/v1/documents/upload", _ConsoleKnowledge_UploadDocument0_HTTP_Handler(srv))
	r.GET("/console/v1/documents/{id}", _ConsoleKnowledge_GetDocument0_HTTP_Handler(srv))
	r.DELETE("/console/v1/documents/{id}", _ConsoleKnowledge_DeleteDocument0_HTTP_Handler(srv))
	r.PATCH("/console/v1/documents/{id}", _ConsoleKnowledge_UpdateDocument0_HTTP_Handler(srv))
	r.POST("/console/v1/documents/{id}/reindex", _ConsoleKnowledge_ReindexDocument0_HTTP_Handler(srv))
	r.POST("/console/v1/documents/{id}/rollback", _ConsoleKnowledge_RollbackDocument0_HTTP_Handler(srv))
}

func _ConsoleKnowledge_CreateKnowledgeBase0_HTTP_Handler(srv ConsoleKnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateKnowledgeBaseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleKnowledgeCreateKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateKnowledgeBase(ctx, req.(*CreateKnowledgeBaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KnowledgeBaseResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleKnowledge_GetKnowledgeBase0_HTTP_Handler(srv ConsoleKnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetKnowledgeBaseRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleKnowledgeGetKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetKnowledgeBase(ctx, req.(*GetKnowledgeBaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KnowledgeBaseResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleKnowledge_UpdateKnowledgeBase0_HTTP_Handler(srv ConsoleKnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateKnowledgeBaseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleKnowledgeUpdateKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateKnowledgeBase(ctx, req.(*UpdateKnowledgeBaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KnowledgeBaseResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleKnowledge_DeleteKnowledgeBase0_HTTP_Handler(srv ConsoleKnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteKnowledgeBaseRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleKnowledgeDeleteKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteKnowledgeBase(ctx, req.(*DeleteKnowledgeBaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ConsoleKnowledge_ListKnowledgeBases0_HTTP_Handler(srv ConsoleKnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListKnowledgeBasesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleKnowledgeListKnowledgeBases)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListKnowledgeBases(ctx, req.(*ListKnowledgeBasesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListKnowledgeBasesResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleKnowledge_ListDocuments0_HTTP_Handler(srv ConsoleKnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDocumentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleKnowledgeListDocuments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDocuments(ctx, req.(*ListDocumentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDocumentsResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleKnowledge_ListBotKnowledgeBases0_HTTP_Handler(srv ConsoleKnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBotKnowledgeBasesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleKnowledgeListBotKnowledgeBases)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBotKnowledgeBases(ctx, req.(*ListBotKnowledgeBasesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBotKnowledgeBasesResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleKnowledge_BindBotKnowledgeBase0_HTTP_Handler(srv ConsoleKnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BindBotKnowledgeBaseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleKnowledgeBindBotKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BindBotKnowledgeBase(ctx, req.(*BindBotKnowledgeBaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BotKnowledgeBaseResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleKnowledge_UnbindBotKnowledgeBase0_HTTP_Handler(srv ConsoleKnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnbindBotKnowledgeBaseRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleKnowledgeUnbindBotKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnbindBotKnowledgeBase(ctx, req.(*UnbindBotKnowledgeBaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ConsoleKnowledge_UploadDocument0_HTTP_Handler(srv ConsoleKnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadDocumentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleKnowledgeUploadDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadDocument(ctx, req.(*UploadDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadDocumentResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleKnowledge_GetDocument0_HTTP_Handler(srv ConsoleKnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDocumentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleKnowledgeGetDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDocument(ctx, req.(*GetDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDocumentResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleKnowledge_DeleteDocument0_HTTP_Handler(srv ConsoleKnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteDocumentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleKnowledgeDeleteDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteDocument(ctx, req.(*DeleteDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ConsoleKnowledge_UpdateDocument0_HTTP_Handler(srv ConsoleKnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDocumentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleKnowledgeUpdateDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDocument(ctx, req.(*UpdateDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DocumentResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleKnowledge_ReindexDocument0_HTTP_Handler(srv ConsoleKnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReindexDocumentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleKnowledgeReindexDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReindexDocument(ctx, req.(*ReindexDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ConsoleKnowledge_RollbackDocument0_HTTP_Handler(srv ConsoleKnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RollbackDocumentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleKnowledgeRollbackDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RollbackDocument(ctx, req.(*RollbackDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type ConsoleKnowledgeHTTPClient interface {
	BindBotKnowledgeBase(ctx context.Context, req *BindBotKnowledgeBaseRequest, opts ...http.CallOption) (rsp *BotKnowledgeBaseResponse, err error)
	CreateKnowledgeBase(ctx context.Context, req *CreateKnowledgeBaseRequest, opts ...http.CallOption) (rsp *KnowledgeBaseResponse, err error)
	DeleteDocument(ctx context.Context, req *DeleteDocumentRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteKnowledgeBase(ctx context.Context, req *DeleteKnowledgeBaseRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetDocument(ctx context.Context, req *GetDocumentRequest, opts ...http.CallOption) (rsp *GetDocumentResponse, err error)
	GetKnowledgeBase(ctx context.Context, req *GetKnowledgeBaseRequest, opts ...http.CallOption) (rsp *KnowledgeBaseResponse, err error)
	ListBotKnowledgeBases(ctx context.Context, req *ListBotKnowledgeBasesRequest, opts ...http.CallOption) (rsp *ListBotKnowledgeBasesResponse, err error)
	ListDocuments(ctx context.Context, req *ListDocumentsRequest, opts ...http.CallOption) (rsp *ListDocumentsResponse, err error)
	ListKnowledgeBases(ctx context.Context, req *ListKnowledgeBasesRequest, opts ...http.CallOption) (rsp *ListKnowledgeBasesResponse, err error)
	ReindexDocument(ctx context.Context, req *ReindexDocumentRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	RollbackDocument(ctx context.Context, req *RollbackDocumentRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	UnbindBotKnowledgeBase(ctx context.Context, req *UnbindBotKnowledgeBaseRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	UpdateDocument(ctx context.Context, req *UpdateDocumentRequest, opts ...http.CallOption) (rsp *DocumentResponse, err error)
	UpdateKnowledgeBase(ctx context.Context, req *UpdateKnowledgeBaseRequest, opts ...http.CallOption) (rsp *KnowledgeBaseResponse, err error)
	UploadDocument(ctx context.Context, req *UploadDocumentRequest, opts ...http.CallOption) (rsp *UploadDocumentResponse, err error)
}

type ConsoleKnowledgeHTTPClientImpl struct {
	cc *http.Client
}

func NewConsoleKnowledgeHTTPClient(client *http.Client) ConsoleKnowledgeHTTPClient {
	return &ConsoleKnowledgeHTTPClientImpl{client}
}

func (c *ConsoleKnowledgeHTTPClientImpl) BindBotKnowledgeBase(ctx context.Context, in *BindBotKnowledgeBaseRequest, opts ...http.CallOption) (*BotKnowledgeBaseResponse, error) {
	var out BotKnowledgeBaseResponse
	pattern := "/console/v1/bots/{bot_id}/knowledge_bases"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConsoleKnowledgeBindBotKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleKnowledgeHTTPClientImpl) CreateKnowledgeBase(ctx context.Context, in *CreateKnowledgeBaseRequest, opts ...http.CallOption) (*KnowledgeBaseResponse, error) {
	var out KnowledgeBaseResponse
	pattern := "/console/v1/knowledge_bases"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConsoleKnowledgeCreateKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleKnowledgeHTTPClientImpl) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/console/v1/documents/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleKnowledgeDeleteDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleKnowledgeHTTPClientImpl) DeleteKnowledgeBase(ctx context.Context, in *DeleteKnowledgeBaseRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/console/v1/knowledge_bases/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleKnowledgeDeleteKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleKnowledgeHTTPClientImpl) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...http.CallOption) (*GetDocumentResponse, error) {
	var out GetDocumentResponse
	pattern := "/console/v1/documents/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleKnowledgeGetDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleKnowledgeHTTPClientImpl) GetKnowledgeBase(ctx context.Context, in *GetKnowledgeBaseRequest, opts ...http.CallOption) (*KnowledgeBaseResponse, error) {
	var out KnowledgeBaseResponse
	pattern := "/console/v1/knowledge_bases/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleKnowledgeGetKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleKnowledgeHTTPClientImpl) ListBotKnowledgeBases(ctx context.Context, in *ListBotKnowledgeBasesRequest, opts ...http.CallOption) (*ListBotKnowledgeBasesResponse, error) {
	var out ListBotKnowledgeBasesResponse
	pattern := "/console/v1/bots/{bot_id}/knowledge_bases"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleKnowledgeListBotKnowledgeBases))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleKnowledgeHTTPClientImpl) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...http.CallOption) (*ListDocumentsResponse, error) {
	var out ListDocumentsResponse
	pattern := "/console/v1/documents"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleKnowledgeListDocuments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleKnowledgeHTTPClientImpl) ListKnowledgeBases(ctx context.Context, in *ListKnowledgeBasesRequest, opts ...http.CallOption) (*ListKnowledgeBasesResponse, error) {
	var out ListKnowledgeBasesResponse
	pattern := "/console/v1/knowledge_bases"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleKnowledgeListKnowledgeBases))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleKnowledgeHTTPClientImpl) ReindexDocument(ctx context.Context, in *ReindexDocumentRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/console/v1/documents/{id}/reindex"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConsoleKnowledgeReindexDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleKnowledgeHTTPClientImpl) RollbackDocument(ctx context.Context, in *RollbackDocumentRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/console/v1/documents/{id}/rollback"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConsoleKnowledgeRollbackDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleKnowledgeHTTPClientImpl) UnbindBotKnowledgeBase(ctx context.Context, in *UnbindBotKnowledgeBaseRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/console/v1/bots/{bot_id}/knowledge_bases/{kb_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleKnowledgeUnbindBotKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleKnowledgeHTTPClientImpl) UpdateDocument(ctx context.Context, in *UpdateDocumentRequest, opts ...http.CallOption) (*DocumentResponse, error) {
	var out DocumentResponse
	pattern := "/console/v1/documents/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConsoleKnowledgeUpdateDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleKnowledgeHTTPClientImpl) UpdateKnowledgeBase(ctx context.Context, in *UpdateKnowledgeBaseRequest, opts ...http.CallOption) (*KnowledgeBaseResponse, error) {
	var out KnowledgeBaseResponse
	pattern := "/console/v1/knowledge_bases/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConsoleKnowledgeUpdateKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleKnowledgeHTTPClientImpl) UploadDocument(ctx context.Context, in *UploadDocumentRequest, opts ...http.CallOption) (*UploadDocumentResponse, error) {
	var out UploadDocumentResponse
	pattern := "/console/v1/documents/upload"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConsoleKnowledgeUploadDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
