// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/knowledge/v1/console_knowledge.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsoleKnowledge_CreateKnowledgeBase_FullMethodName    = "/api.knowledge.v1.ConsoleKnowledge/CreateKnowledgeBase"
	ConsoleKnowledge_GetKnowledgeBase_FullMethodName       = "/api.knowledge.v1.ConsoleKnowledge/GetKnowledgeBase"
	ConsoleKnowledge_UpdateKnowledgeBase_FullMethodName    = "/api.knowledge.v1.ConsoleKnowledge/UpdateKnowledgeBase"
	ConsoleKnowledge_DeleteKnowledgeBase_FullMethodName    = "/api.knowledge.v1.ConsoleKnowledge/DeleteKnowledgeBase"
	ConsoleKnowledge_ListKnowledgeBases_FullMethodName     = "/api.knowledge.v1.ConsoleKnowledge/ListKnowledgeBases"
	ConsoleKnowledge_ListDocuments_FullMethodName          = "/api.knowledge.v1.ConsoleKnowledge/ListDocuments"
	ConsoleKnowledge_ListBotKnowledgeBases_FullMethodName  = "/api.knowledge.v1.ConsoleKnowledge/ListBotKnowledgeBases"
	ConsoleKnowledge_BindBotKnowledgeBase_FullMethodName   = "/api.knowledge.v1.ConsoleKnowledge/BindBotKnowledgeBase"
	ConsoleKnowledge_UnbindBotKnowledgeBase_FullMethodName = "/api.knowledge.v1.ConsoleKnowledge/UnbindBotKnowledgeBase"
	ConsoleKnowledge_UploadDocument_FullMethodName         = "/api.knowledge.v1.ConsoleKnowledge/UploadDocument"
	ConsoleKnowledge_GetDocument_FullMethodName            = "/api.knowledge.v1.ConsoleKnowledge/GetDocument"
	ConsoleKnowledge_DeleteDocument_FullMethodName         = "/api.knowledge.v1.ConsoleKnowledge/DeleteDocument"
	ConsoleKnowledge_ReindexDocument_FullMethodName        = "/api.knowledge.v1.ConsoleKnowledge/ReindexDocument"
	ConsoleKnowledge_RollbackDocument_FullMethodName       = "/api.knowledge.v1.ConsoleKnowledge/RollbackDocument"
)

// ConsoleKnowledgeClient is the client API for ConsoleKnowledge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsoleKnowledgeClient interface {
	CreateKnowledgeBase(ctx context.Context, in *CreateKnowledgeBaseRequest, opts ...grpc.CallOption) (*KnowledgeBaseResponse, error)
	GetKnowledgeBase(ctx context.Context, in *GetKnowledgeBaseRequest, opts ...grpc.CallOption) (*KnowledgeBaseResponse, error)
	UpdateKnowledgeBase(ctx context.Context, in *UpdateKnowledgeBaseRequest, opts ...grpc.CallOption) (*KnowledgeBaseResponse, error)
	DeleteKnowledgeBase(ctx context.Context, in *DeleteKnowledgeBaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListKnowledgeBases(ctx context.Context, in *ListKnowledgeBasesRequest, opts ...grpc.CallOption) (*ListKnowledgeBasesResponse, error)
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
	ListBotKnowledgeBases(ctx context.Context, in *ListBotKnowledgeBasesRequest, opts ...grpc.CallOption) (*ListBotKnowledgeBasesResponse, error)
	BindBotKnowledgeBase(ctx context.Context, in *BindBotKnowledgeBaseRequest, opts ...grpc.CallOption) (*BotKnowledgeBaseResponse, error)
	UnbindBotKnowledgeBase(ctx context.Context, in *UnbindBotKnowledgeBaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UploadDocument(ctx context.Context, in *UploadDocumentRequest, opts ...grpc.CallOption) (*UploadDocumentResponse, error)
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReindexDocument(ctx context.Context, in *ReindexDocumentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RollbackDocument(ctx context.Context, in *RollbackDocumentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type consoleKnowledgeClient struct {
	cc grpc.ClientConnInterface
}

func NewConsoleKnowledgeClient(cc grpc.ClientConnInterface) ConsoleKnowledgeClient {
	return &consoleKnowledgeClient{cc}
}

func (c *consoleKnowledgeClient) CreateKnowledgeBase(ctx context.Context, in *CreateKnowledgeBaseRequest, opts ...grpc.CallOption) (*KnowledgeBaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeBaseResponse)
	err := c.cc.Invoke(ctx, ConsoleKnowledge_CreateKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleKnowledgeClient) GetKnowledgeBase(ctx context.Context, in *GetKnowledgeBaseRequest, opts ...grpc.CallOption) (*KnowledgeBaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeBaseResponse)
	err := c.cc.Invoke(ctx, ConsoleKnowledge_GetKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleKnowledgeClient) UpdateKnowledgeBase(ctx context.Context, in *UpdateKnowledgeBaseRequest, opts ...grpc.CallOption) (*KnowledgeBaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeBaseResponse)
	err := c.cc.Invoke(ctx, ConsoleKnowledge_UpdateKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleKnowledgeClient) DeleteKnowledgeBase(ctx context.Context, in *DeleteKnowledgeBaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConsoleKnowledge_DeleteKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleKnowledgeClient) ListKnowledgeBases(ctx context.Context, in *ListKnowledgeBasesRequest, opts ...grpc.CallOption) (*ListKnowledgeBasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKnowledgeBasesResponse)
	err := c.cc.Invoke(ctx, ConsoleKnowledge_ListKnowledgeBases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleKnowledgeClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, ConsoleKnowledge_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleKnowledgeClient) ListBotKnowledgeBases(ctx context.Context, in *ListBotKnowledgeBasesRequest, opts ...grpc.CallOption) (*ListBotKnowledgeBasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBotKnowledgeBasesResponse)
	err := c.cc.Invoke(ctx, ConsoleKnowledge_ListBotKnowledgeBases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleKnowledgeClient) BindBotKnowledgeBase(ctx context.Context, in *BindBotKnowledgeBaseRequest, opts ...grpc.CallOption) (*BotKnowledgeBaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotKnowledgeBaseResponse)
	err := c.cc.Invoke(ctx, ConsoleKnowledge_BindBotKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleKnowledgeClient) UnbindBotKnowledgeBase(ctx context.Context, in *UnbindBotKnowledgeBaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConsoleKnowledge_UnbindBotKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleKnowledgeClient) UploadDocument(ctx context.Context, in *UploadDocumentRequest, opts ...grpc.CallOption) (*UploadDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadDocumentResponse)
	err := c.cc.Invoke(ctx, ConsoleKnowledge_UploadDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleKnowledgeClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, ConsoleKnowledge_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleKnowledgeClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConsoleKnowledge_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleKnowledgeClient) ReindexDocument(ctx context.Context, in *ReindexDocumentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConsoleKnowledge_ReindexDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleKnowledgeClient) RollbackDocument(ctx context.Context, in *RollbackDocumentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConsoleKnowledge_RollbackDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsoleKnowledgeServer is the server API for ConsoleKnowledge service.
// All implementations must embed UnimplementedConsoleKnowledgeServer
// for forward compatibility.
type ConsoleKnowledgeServer interface {
	CreateKnowledgeBase(context.Context, *CreateKnowledgeBaseRequest) (*KnowledgeBaseResponse, error)
	GetKnowledgeBase(context.Context, *GetKnowledgeBaseRequest) (*KnowledgeBaseResponse, error)
	UpdateKnowledgeBase(context.Context, *UpdateKnowledgeBaseRequest) (*KnowledgeBaseResponse, error)
	DeleteKnowledgeBase(context.Context, *DeleteKnowledgeBaseRequest) (*emptypb.Empty, error)
	ListKnowledgeBases(context.Context, *ListKnowledgeBasesRequest) (*ListKnowledgeBasesResponse, error)
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	ListBotKnowledgeBases(context.Context, *ListBotKnowledgeBasesRequest) (*ListBotKnowledgeBasesResponse, error)
	BindBotKnowledgeBase(context.Context, *BindBotKnowledgeBaseRequest) (*BotKnowledgeBaseResponse, error)
	UnbindBotKnowledgeBase(context.Context, *UnbindBotKnowledgeBaseRequest) (*emptypb.Empty, error)
	UploadDocument(context.Context, *UploadDocumentRequest) (*UploadDocumentResponse, error)
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*emptypb.Empty, error)
	ReindexDocument(context.Context, *ReindexDocumentRequest) (*emptypb.Empty, error)
	RollbackDocument(context.Context, *RollbackDocumentRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedConsoleKnowledgeServer()
}

// UnimplementedConsoleKnowledgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsoleKnowledgeServer struct{}

func (UnimplementedConsoleKnowledgeServer) CreateKnowledgeBase(context.Context, *CreateKnowledgeBaseRequest) (*KnowledgeBaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKnowledgeBase not implemented")
}
func (UnimplementedConsoleKnowledgeServer) GetKnowledgeBase(context.Context, *GetKnowledgeBaseRequest) (*KnowledgeBaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKnowledgeBase not implemented")
}
func (UnimplementedConsoleKnowledgeServer) UpdateKnowledgeBase(context.Context, *UpdateKnowledgeBaseRequest) (*KnowledgeBaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateKnowledgeBase not implemented")
}
func (UnimplementedConsoleKnowledgeServer) DeleteKnowledgeBase(context.Context, *DeleteKnowledgeBaseRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKnowledgeBase not implemented")
}
func (UnimplementedConsoleKnowledgeServer) ListKnowledgeBases(context.Context, *ListKnowledgeBasesRequest) (*ListKnowledgeBasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKnowledgeBases not implemented")
}
func (UnimplementedConsoleKnowledgeServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedConsoleKnowledgeServer) ListBotKnowledgeBases(context.Context, *ListBotKnowledgeBasesRequest) (*ListBotKnowledgeBasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBotKnowledgeBases not implemented")
}
func (UnimplementedConsoleKnowledgeServer) BindBotKnowledgeBase(context.Context, *BindBotKnowledgeBaseRequest) (*BotKnowledgeBaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindBotKnowledgeBase not implemented")
}
func (UnimplementedConsoleKnowledgeServer) UnbindBotKnowledgeBase(context.Context, *UnbindBotKnowledgeBaseRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbindBotKnowledgeBase not implemented")
}
func (UnimplementedConsoleKnowledgeServer) UploadDocument(context.Context, *UploadDocumentRequest) (*UploadDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadDocument not implemented")
}
func (UnimplementedConsoleKnowledgeServer) GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedConsoleKnowledgeServer) DeleteDocument(context.Context, *DeleteDocumentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedConsoleKnowledgeServer) ReindexDocument(context.Context, *ReindexDocumentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReindexDocument not implemented")
}
func (UnimplementedConsoleKnowledgeServer) RollbackDocument(context.Context, *RollbackDocumentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackDocument not implemented")
}
func (UnimplementedConsoleKnowledgeServer) mustEmbedUnimplementedConsoleKnowledgeServer() {}
func (UnimplementedConsoleKnowledgeServer) testEmbeddedByValue()                          {}

// UnsafeConsoleKnowledgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsoleKnowledgeServer will
// result in compilation errors.
type UnsafeConsoleKnowledgeServer interface {
	mustEmbedUnimplementedConsoleKnowledgeServer()
}

func RegisterConsoleKnowledgeServer(s grpc.ServiceRegistrar, srv ConsoleKnowledgeServer) {
	// If the following call panics, it indicates UnimplementedConsoleKnowledgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsoleKnowledge_ServiceDesc, srv)
}

func _ConsoleKnowledge_CreateKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKnowledgeBaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleKnowledgeServer).CreateKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleKnowledge_CreateKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleKnowledgeServer).CreateKnowledgeBase(ctx, req.(*CreateKnowledgeBaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleKnowledge_GetKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKnowledgeBaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleKnowledgeServer).GetKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleKnowledge_GetKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleKnowledgeServer).GetKnowledgeBase(ctx, req.(*GetKnowledgeBaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleKnowledge_UpdateKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKnowledgeBaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleKnowledgeServer).UpdateKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleKnowledge_UpdateKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleKnowledgeServer).UpdateKnowledgeBase(ctx, req.(*UpdateKnowledgeBaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleKnowledge_DeleteKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKnowledgeBaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleKnowledgeServer).DeleteKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleKnowledge_DeleteKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleKnowledgeServer).DeleteKnowledgeBase(ctx, req.(*DeleteKnowledgeBaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleKnowledge_ListKnowledgeBases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKnowledgeBasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleKnowledgeServer).ListKnowledgeBases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleKnowledge_ListKnowledgeBases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleKnowledgeServer).ListKnowledgeBases(ctx, req.(*ListKnowledgeBasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleKnowledge_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleKnowledgeServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleKnowledge_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleKnowledgeServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleKnowledge_ListBotKnowledgeBases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBotKnowledgeBasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleKnowledgeServer).ListBotKnowledgeBases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleKnowledge_ListBotKnowledgeBases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleKnowledgeServer).ListBotKnowledgeBases(ctx, req.(*ListBotKnowledgeBasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleKnowledge_BindBotKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindBotKnowledgeBaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleKnowledgeServer).BindBotKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleKnowledge_BindBotKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleKnowledgeServer).BindBotKnowledgeBase(ctx, req.(*BindBotKnowledgeBaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleKnowledge_UnbindBotKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindBotKnowledgeBaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleKnowledgeServer).UnbindBotKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleKnowledge_UnbindBotKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleKnowledgeServer).UnbindBotKnowledgeBase(ctx, req.(*UnbindBotKnowledgeBaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleKnowledge_UploadDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleKnowledgeServer).UploadDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleKnowledge_UploadDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleKnowledgeServer).UploadDocument(ctx, req.(*UploadDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleKnowledge_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleKnowledgeServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleKnowledge_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleKnowledgeServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleKnowledge_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleKnowledgeServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleKnowledge_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleKnowledgeServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleKnowledge_ReindexDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReindexDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleKnowledgeServer).ReindexDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleKnowledge_ReindexDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleKnowledgeServer).ReindexDocument(ctx, req.(*ReindexDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleKnowledge_RollbackDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleKnowledgeServer).RollbackDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleKnowledge_RollbackDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleKnowledgeServer).RollbackDocument(ctx, req.(*RollbackDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsoleKnowledge_ServiceDesc is the grpc.ServiceDesc for ConsoleKnowledge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsoleKnowledge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.knowledge.v1.ConsoleKnowledge",
	HandlerType: (*ConsoleKnowledgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKnowledgeBase",
			Handler:    _ConsoleKnowledge_CreateKnowledgeBase_Handler,
		},
		{
			MethodName: "GetKnowledgeBase",
			Handler:    _ConsoleKnowledge_GetKnowledgeBase_Handler,
		},
		{
			MethodName: "UpdateKnowledgeBase",
			Handler:    _ConsoleKnowledge_UpdateKnowledgeBase_Handler,
		},
		{
			MethodName: "DeleteKnowledgeBase",
			Handler:    _ConsoleKnowledge_DeleteKnowledgeBase_Handler,
		},
		{
			MethodName: "ListKnowledgeBases",
			Handler:    _ConsoleKnowledge_ListKnowledgeBases_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _ConsoleKnowledge_ListDocuments_Handler,
		},
		{
			MethodName: "ListBotKnowledgeBases",
			Handler:    _ConsoleKnowledge_ListBotKnowledgeBases_Handler,
		},
		{
			MethodName: "BindBotKnowledgeBase",
			Handler:    _ConsoleKnowledge_BindBotKnowledgeBase_Handler,
		},
		{
			MethodName: "UnbindBotKnowledgeBase",
			Handler:    _ConsoleKnowledge_UnbindBotKnowledgeBase_Handler,
		},
		{
			MethodName: "UploadDocument",
			Handler:    _ConsoleKnowledge_UploadDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _ConsoleKnowledge_GetDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _ConsoleKnowledge_DeleteDocument_Handler,
		},
		{
			MethodName: "ReindexDocument",
			Handler:    _ConsoleKnowledge_ReindexDocument_Handler,
		},
		{
			MethodName: "RollbackDocument",
			Handler:    _ConsoleKnowledge_RollbackDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/knowledge/v1/console_knowledge.proto",
}
