// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/bot/v1/console_bot.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsoleBot_CreateBot_FullMethodName = "/api.bot.v1.ConsoleBot/CreateBot"
	ConsoleBot_GetBot_FullMethodName    = "/api.bot.v1.ConsoleBot/GetBot"
	ConsoleBot_UpdateBot_FullMethodName = "/api.bot.v1.ConsoleBot/UpdateBot"
	ConsoleBot_DeleteBot_FullMethodName = "/api.bot.v1.ConsoleBot/DeleteBot"
	ConsoleBot_ListBots_FullMethodName  = "/api.bot.v1.ConsoleBot/ListBots"
)

// ConsoleBotClient is the client API for ConsoleBot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsoleBotClient interface {
	CreateBot(ctx context.Context, in *CreateBotRequest, opts ...grpc.CallOption) (*BotResponse, error)
	GetBot(ctx context.Context, in *GetBotRequest, opts ...grpc.CallOption) (*BotResponse, error)
	UpdateBot(ctx context.Context, in *UpdateBotRequest, opts ...grpc.CallOption) (*BotResponse, error)
	DeleteBot(ctx context.Context, in *DeleteBotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListBots(ctx context.Context, in *ListBotsRequest, opts ...grpc.CallOption) (*ListBotsResponse, error)
}

type consoleBotClient struct {
	cc grpc.ClientConnInterface
}

func NewConsoleBotClient(cc grpc.ClientConnInterface) ConsoleBotClient {
	return &consoleBotClient{cc}
}

func (c *consoleBotClient) CreateBot(ctx context.Context, in *CreateBotRequest, opts ...grpc.CallOption) (*BotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotResponse)
	err := c.cc.Invoke(ctx, ConsoleBot_CreateBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleBotClient) GetBot(ctx context.Context, in *GetBotRequest, opts ...grpc.CallOption) (*BotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotResponse)
	err := c.cc.Invoke(ctx, ConsoleBot_GetBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleBotClient) UpdateBot(ctx context.Context, in *UpdateBotRequest, opts ...grpc.CallOption) (*BotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotResponse)
	err := c.cc.Invoke(ctx, ConsoleBot_UpdateBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleBotClient) DeleteBot(ctx context.Context, in *DeleteBotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConsoleBot_DeleteBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleBotClient) ListBots(ctx context.Context, in *ListBotsRequest, opts ...grpc.CallOption) (*ListBotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBotsResponse)
	err := c.cc.Invoke(ctx, ConsoleBot_ListBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsoleBotServer is the server API for ConsoleBot service.
// All implementations must embed UnimplementedConsoleBotServer
// for forward compatibility.
type ConsoleBotServer interface {
	CreateBot(context.Context, *CreateBotRequest) (*BotResponse, error)
	GetBot(context.Context, *GetBotRequest) (*BotResponse, error)
	UpdateBot(context.Context, *UpdateBotRequest) (*BotResponse, error)
	DeleteBot(context.Context, *DeleteBotRequest) (*emptypb.Empty, error)
	ListBots(context.Context, *ListBotsRequest) (*ListBotsResponse, error)
	mustEmbedUnimplementedConsoleBotServer()
}

// UnimplementedConsoleBotServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsoleBotServer struct{}

func (UnimplementedConsoleBotServer) CreateBot(context.Context, *CreateBotRequest) (*BotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBot not implemented")
}
func (UnimplementedConsoleBotServer) GetBot(context.Context, *GetBotRequest) (*BotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBot not implemented")
}
func (UnimplementedConsoleBotServer) UpdateBot(context.Context, *UpdateBotRequest) (*BotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBot not implemented")
}
func (UnimplementedConsoleBotServer) DeleteBot(context.Context, *DeleteBotRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBot not implemented")
}
func (UnimplementedConsoleBotServer) ListBots(context.Context, *ListBotsRequest) (*ListBotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBots not implemented")
}
func (UnimplementedConsoleBotServer) mustEmbedUnimplementedConsoleBotServer() {}
func (UnimplementedConsoleBotServer) testEmbeddedByValue()                    {}

// UnsafeConsoleBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsoleBotServer will
// result in compilation errors.
type UnsafeConsoleBotServer interface {
	mustEmbedUnimplementedConsoleBotServer()
}

func RegisterConsoleBotServer(s grpc.ServiceRegistrar, srv ConsoleBotServer) {
	// If the following call panics, it indicates UnimplementedConsoleBotServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsoleBot_ServiceDesc, srv)
}

func _ConsoleBot_CreateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleBotServer).CreateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleBot_CreateBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleBotServer).CreateBot(ctx, req.(*CreateBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleBot_GetBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleBotServer).GetBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleBot_GetBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleBotServer).GetBot(ctx, req.(*GetBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleBot_UpdateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleBotServer).UpdateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleBot_UpdateBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleBotServer).UpdateBot(ctx, req.(*UpdateBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleBot_DeleteBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleBotServer).DeleteBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleBot_DeleteBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleBotServer).DeleteBot(ctx, req.(*DeleteBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleBot_ListBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleBotServer).ListBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleBot_ListBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleBotServer).ListBots(ctx, req.(*ListBotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsoleBot_ServiceDesc is the grpc.ServiceDesc for ConsoleBot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsoleBot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.bot.v1.ConsoleBot",
	HandlerType: (*ConsoleBotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBot",
			Handler:    _ConsoleBot_CreateBot_Handler,
		},
		{
			MethodName: "GetBot",
			Handler:    _ConsoleBot_GetBot_Handler,
		},
		{
			MethodName: "UpdateBot",
			Handler:    _ConsoleBot_UpdateBot_Handler,
		},
		{
			MethodName: "DeleteBot",
			Handler:    _ConsoleBot_DeleteBot_Handler,
		},
		{
			MethodName: "ListBots",
			Handler:    _ConsoleBot_ListBots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/bot/v1/console_bot.proto",
}
