// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/bot/v1/console_bot.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bot) Reset() {
	*x = Bot{}
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bot) ProtoMessage() {}

func (x *Bot) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bot.ProtoReflect.Descriptor instead.
func (*Bot) Descriptor() ([]byte, []int) {
	return file_api_bot_v1_console_bot_proto_rawDescGZIP(), []int{0}
}

func (x *Bot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bot) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Bot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Bot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Bot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Bot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBotRequest) Reset() {
	*x = CreateBotRequest{}
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotRequest) ProtoMessage() {}

func (x *CreateBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotRequest.ProtoReflect.Descriptor instead.
func (*CreateBotRequest) Descriptor() ([]byte, []int) {
	return file_api_bot_v1_console_bot_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBotRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBotRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotRequest) Reset() {
	*x = GetBotRequest{}
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotRequest) ProtoMessage() {}

func (x *GetBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotRequest.ProtoReflect.Descriptor instead.
func (*GetBotRequest) Descriptor() ([]byte, []int) {
	return file_api_bot_v1_console_bot_proto_rawDescGZIP(), []int{2}
}

func (x *GetBotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBotRequest) Reset() {
	*x = UpdateBotRequest{}
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBotRequest) ProtoMessage() {}

func (x *UpdateBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBotRequest.ProtoReflect.Descriptor instead.
func (*UpdateBotRequest) Descriptor() ([]byte, []int) {
	return file_api_bot_v1_console_bot_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBotRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateBotRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBotRequest) Reset() {
	*x = DeleteBotRequest{}
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBotRequest) ProtoMessage() {}

func (x *DeleteBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBotRequest.ProtoReflect.Descriptor instead.
func (*DeleteBotRequest) Descriptor() ([]byte, []int) {
	return file_api_bot_v1_console_bot_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListBotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBotsRequest) Reset() {
	*x = ListBotsRequest{}
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBotsRequest) ProtoMessage() {}

func (x *ListBotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBotsRequest.ProtoReflect.Descriptor instead.
func (*ListBotsRequest) Descriptor() ([]byte, []int) {
	return file_api_bot_v1_console_bot_proto_rawDescGZIP(), []int{5}
}

func (x *ListBotsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBotsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListBotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Bot                 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBotsResponse) Reset() {
	*x = ListBotsResponse{}
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBotsResponse) ProtoMessage() {}

func (x *ListBotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBotsResponse.ProtoReflect.Descriptor instead.
func (*ListBotsResponse) Descriptor() ([]byte, []int) {
	return file_api_bot_v1_console_bot_proto_rawDescGZIP(), []int{6}
}

func (x *ListBotsResponse) GetItems() []*Bot {
	if x != nil {
		return x.Items
	}
	return nil
}

type BotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bot           *Bot                   `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotResponse) Reset() {
	*x = BotResponse{}
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotResponse) ProtoMessage() {}

func (x *BotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_v1_console_bot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotResponse.ProtoReflect.Descriptor instead.
func (*BotResponse) Descriptor() ([]byte, []int) {
	return file_api_bot_v1_console_bot_proto_rawDescGZIP(), []int{7}
}

func (x *BotResponse) GetBot() *Bot {
	if x != nil {
		return x.Bot
	}
	return nil
}

var File_api_bot_v1_console_bot_proto protoreflect.FileDescriptor

const file_api_bot_v1_console_bot_proto_rawDesc = "" +
	"\n" +
	"\x1capi/bot/v1/console_bot.proto\x12\n" +
	"api.bot.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x01\n" +
	"\x03Bot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"`\n" +
	"\x10CreateBotRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x1f\n" +
	"\rGetBotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"p\n" +
	"\x10UpdateBotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\"\n" +
	"\x10DeleteBotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x0fListBotsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"9\n" +
	"\x10ListBotsResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.api.bot.v1.BotR\x05items\"0\n" +
	"\vBotResponse\x12!\n" +
	"\x03bot\x18\x01 \x01(\v2\x0f.api.bot.v1.BotR\x03bot2\xf3\x03\n" +
	"\n" +
	"ConsoleBot\x12_\n" +
	"\tCreateBot\x12\x1c.api.bot.v1.CreateBotRequest\x1a\x17.api.bot.v1.BotResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/console/v1/bots\x12[\n" +
	"\x06GetBot\x12\x19.api.bot.v1.GetBotRequest\x1a\x17.api.bot.v1.BotResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/console/v1/bots/{id}\x12d\n" +
	"\tUpdateBot\x12\x1c.api.bot.v1.UpdateBotRequest\x1a\x17.api.bot.v1.BotResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*2\x15/console/v1/bots/{id}\x12`\n" +
	"\tDeleteBot\x12\x1c.api.bot.v1.DeleteBotRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/console/v1/bots/{id}\x12_\n" +
	"\bListBots\x12\x1b.api.bot.v1.ListBotsRequest\x1a\x1c.api.bot.v1.ListBotsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/console/v1/botsB4Z2github.com/ZTH7/RagoDesk/apps/server/api/bot/v1;v1b\x06proto3"

var (
	file_api_bot_v1_console_bot_proto_rawDescOnce sync.Once
	file_api_bot_v1_console_bot_proto_rawDescData []byte
)

func file_api_bot_v1_console_bot_proto_rawDescGZIP() []byte {
	file_api_bot_v1_console_bot_proto_rawDescOnce.Do(func() {
		file_api_bot_v1_console_bot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_bot_v1_console_bot_proto_rawDesc), len(file_api_bot_v1_console_bot_proto_rawDesc)))
	})
	return file_api_bot_v1_console_bot_proto_rawDescData
}

var file_api_bot_v1_console_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_bot_v1_console_bot_proto_goTypes = []any{
	(*Bot)(nil),                   // 0: api.bot.v1.Bot
	(*CreateBotRequest)(nil),      // 1: api.bot.v1.CreateBotRequest
	(*GetBotRequest)(nil),         // 2: api.bot.v1.GetBotRequest
	(*UpdateBotRequest)(nil),      // 3: api.bot.v1.UpdateBotRequest
	(*DeleteBotRequest)(nil),      // 4: api.bot.v1.DeleteBotRequest
	(*ListBotsRequest)(nil),       // 5: api.bot.v1.ListBotsRequest
	(*ListBotsResponse)(nil),      // 6: api.bot.v1.ListBotsResponse
	(*BotResponse)(nil),           // 7: api.bot.v1.BotResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_api_bot_v1_console_bot_proto_depIdxs = []int32{
	8, // 0: api.bot.v1.Bot.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: api.bot.v1.Bot.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: api.bot.v1.ListBotsResponse.items:type_name -> api.bot.v1.Bot
	0, // 3: api.bot.v1.BotResponse.bot:type_name -> api.bot.v1.Bot
	1, // 4: api.bot.v1.ConsoleBot.CreateBot:input_type -> api.bot.v1.CreateBotRequest
	2, // 5: api.bot.v1.ConsoleBot.GetBot:input_type -> api.bot.v1.GetBotRequest
	3, // 6: api.bot.v1.ConsoleBot.UpdateBot:input_type -> api.bot.v1.UpdateBotRequest
	4, // 7: api.bot.v1.ConsoleBot.DeleteBot:input_type -> api.bot.v1.DeleteBotRequest
	5, // 8: api.bot.v1.ConsoleBot.ListBots:input_type -> api.bot.v1.ListBotsRequest
	7, // 9: api.bot.v1.ConsoleBot.CreateBot:output_type -> api.bot.v1.BotResponse
	7, // 10: api.bot.v1.ConsoleBot.GetBot:output_type -> api.bot.v1.BotResponse
	7, // 11: api.bot.v1.ConsoleBot.UpdateBot:output_type -> api.bot.v1.BotResponse
	9, // 12: api.bot.v1.ConsoleBot.DeleteBot:output_type -> google.protobuf.Empty
	6, // 13: api.bot.v1.ConsoleBot.ListBots:output_type -> api.bot.v1.ListBotsResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_bot_v1_console_bot_proto_init() }
func file_api_bot_v1_console_bot_proto_init() {
	if File_api_bot_v1_console_bot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_bot_v1_console_bot_proto_rawDesc), len(file_api_bot_v1_console_bot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_bot_v1_console_bot_proto_goTypes,
		DependencyIndexes: file_api_bot_v1_console_bot_proto_depIdxs,
		MessageInfos:      file_api_bot_v1_console_bot_proto_msgTypes,
	}.Build()
	File_api_bot_v1_console_bot_proto = out.File
	file_api_bot_v1_console_bot_proto_goTypes = nil
	file_api_bot_v1_console_bot_proto_depIdxs = nil
}
