// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/iam/v1/console_iam.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_iam_v1_console_iam_proto protoreflect.FileDescriptor

const file_api_iam_v1_console_iam_proto_rawDesc = "" +
	"\n" +
	"\x1capi/iam/v1/console_iam.proto\x12\n" +
	"api.iam.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14api/iam/v1/iam.proto2\xde\a\n" +
	"\n" +
	"ConsoleIAM\x12w\n" +
	"\n" +
	"CreateUser\x12\x1d.api.iam.v1.CreateUserRequest\x1a\x18.api.iam.v1.UserResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/console/v1/tenants/{tenant_id}/users\x12w\n" +
	"\tListUsers\x12\x1c.api.iam.v1.ListUsersRequest\x1a\x1d.api.iam.v1.ListUsersResponse\"-\x82\xd3\xe4\x93\x02'\x12%/console/v1/tenants/{tenant_id}/users\x12c\n" +
	"\n" +
	"CreateRole\x12\x1d.api.iam.v1.CreateRoleRequest\x1a\x18.api.iam.v1.RoleResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/console/v1/roles\x12c\n" +
	"\tListRoles\x12\x1c.api.iam.v1.ListRolesRequest\x1a\x1d.api.iam.v1.ListRolesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/console/v1/roles\x12q\n" +
	"\n" +
	"AssignRole\x12\x1d.api.iam.v1.AssignRoleRequest\x1a\x16.google.protobuf.Empty\",\x82\xd3\xe4\x93\x02&:\x01*\"!/console/v1/users/{user_id}/roles\x12{\n" +
	"\x0fListPermissions\x12\".api.iam.v1.ListPermissionsRequest\x1a#.api.iam.v1.ListPermissionsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/console/v1/permissions\x12\x8d\x01\n" +
	"\x15AssignRolePermissions\x12(.api.iam.v1.AssignRolePermissionsRequest\x1a\x16.google.protobuf.Empty\"2\x82\xd3\xe4\x93\x02,:\x01*\"'/console/v1/roles/{role_id}/permissions\x12\x93\x01\n" +
	"\x13ListRolePermissions\x12&.api.iam.v1.ListRolePermissionsRequest\x1a#.api.iam.v1.ListPermissionsResponse\"/\x82\xd3\xe4\x93\x02)\x12'/console/v1/roles/{role_id}/permissionsB4Z2github.com/ZTH7/RagoDesk/apps/server/api/iam/v1;v1b\x06proto3"

var file_api_iam_v1_console_iam_proto_goTypes = []any{
	(*CreateUserRequest)(nil),            // 0: api.iam.v1.CreateUserRequest
	(*ListUsersRequest)(nil),             // 1: api.iam.v1.ListUsersRequest
	(*CreateRoleRequest)(nil),            // 2: api.iam.v1.CreateRoleRequest
	(*ListRolesRequest)(nil),             // 3: api.iam.v1.ListRolesRequest
	(*AssignRoleRequest)(nil),            // 4: api.iam.v1.AssignRoleRequest
	(*ListPermissionsRequest)(nil),       // 5: api.iam.v1.ListPermissionsRequest
	(*AssignRolePermissionsRequest)(nil), // 6: api.iam.v1.AssignRolePermissionsRequest
	(*ListRolePermissionsRequest)(nil),   // 7: api.iam.v1.ListRolePermissionsRequest
	(*UserResponse)(nil),                 // 8: api.iam.v1.UserResponse
	(*ListUsersResponse)(nil),            // 9: api.iam.v1.ListUsersResponse
	(*RoleResponse)(nil),                 // 10: api.iam.v1.RoleResponse
	(*ListRolesResponse)(nil),            // 11: api.iam.v1.ListRolesResponse
	(*emptypb.Empty)(nil),                // 12: google.protobuf.Empty
	(*ListPermissionsResponse)(nil),      // 13: api.iam.v1.ListPermissionsResponse
}
var file_api_iam_v1_console_iam_proto_depIdxs = []int32{
	0,  // 0: api.iam.v1.ConsoleIAM.CreateUser:input_type -> api.iam.v1.CreateUserRequest
	1,  // 1: api.iam.v1.ConsoleIAM.ListUsers:input_type -> api.iam.v1.ListUsersRequest
	2,  // 2: api.iam.v1.ConsoleIAM.CreateRole:input_type -> api.iam.v1.CreateRoleRequest
	3,  // 3: api.iam.v1.ConsoleIAM.ListRoles:input_type -> api.iam.v1.ListRolesRequest
	4,  // 4: api.iam.v1.ConsoleIAM.AssignRole:input_type -> api.iam.v1.AssignRoleRequest
	5,  // 5: api.iam.v1.ConsoleIAM.ListPermissions:input_type -> api.iam.v1.ListPermissionsRequest
	6,  // 6: api.iam.v1.ConsoleIAM.AssignRolePermissions:input_type -> api.iam.v1.AssignRolePermissionsRequest
	7,  // 7: api.iam.v1.ConsoleIAM.ListRolePermissions:input_type -> api.iam.v1.ListRolePermissionsRequest
	8,  // 8: api.iam.v1.ConsoleIAM.CreateUser:output_type -> api.iam.v1.UserResponse
	9,  // 9: api.iam.v1.ConsoleIAM.ListUsers:output_type -> api.iam.v1.ListUsersResponse
	10, // 10: api.iam.v1.ConsoleIAM.CreateRole:output_type -> api.iam.v1.RoleResponse
	11, // 11: api.iam.v1.ConsoleIAM.ListRoles:output_type -> api.iam.v1.ListRolesResponse
	12, // 12: api.iam.v1.ConsoleIAM.AssignRole:output_type -> google.protobuf.Empty
	13, // 13: api.iam.v1.ConsoleIAM.ListPermissions:output_type -> api.iam.v1.ListPermissionsResponse
	12, // 14: api.iam.v1.ConsoleIAM.AssignRolePermissions:output_type -> google.protobuf.Empty
	13, // 15: api.iam.v1.ConsoleIAM.ListRolePermissions:output_type -> api.iam.v1.ListPermissionsResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_iam_v1_console_iam_proto_init() }
func file_api_iam_v1_console_iam_proto_init() {
	if File_api_iam_v1_console_iam_proto != nil {
		return
	}
	file_api_iam_v1_iam_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_iam_v1_console_iam_proto_rawDesc), len(file_api_iam_v1_console_iam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_iam_v1_console_iam_proto_goTypes,
		DependencyIndexes: file_api_iam_v1_console_iam_proto_depIdxs,
	}.Build()
	File_api_iam_v1_console_iam_proto = out.File
	file_api_iam_v1_console_iam_proto_goTypes = nil
	file_api_iam_v1_console_iam_proto_depIdxs = nil
}
