// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/iam/v1/console_iam.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationConsoleIAMAssignRole = "/api.iam.v1.ConsoleIAM/AssignRole"
const OperationConsoleIAMAssignRolePermissions = "/api.iam.v1.ConsoleIAM/AssignRolePermissions"
const OperationConsoleIAMCreateRole = "/api.iam.v1.ConsoleIAM/CreateRole"
const OperationConsoleIAMCreateUser = "/api.iam.v1.ConsoleIAM/CreateUser"
const OperationConsoleIAMListPermissions = "/api.iam.v1.ConsoleIAM/ListPermissions"
const OperationConsoleIAMListRolePermissions = "/api.iam.v1.ConsoleIAM/ListRolePermissions"
const OperationConsoleIAMListRoles = "/api.iam.v1.ConsoleIAM/ListRoles"
const OperationConsoleIAMListUsers = "/api.iam.v1.ConsoleIAM/ListUsers"

type ConsoleIAMHTTPServer interface {
	AssignRole(context.Context, *AssignRoleRequest) (*emptypb.Empty, error)
	AssignRolePermissions(context.Context, *AssignRolePermissionsRequest) (*emptypb.Empty, error)
	CreateRole(context.Context, *CreateRoleRequest) (*RoleResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*UserResponse, error)
	ListPermissions(context.Context, *ListPermissionsRequest) (*ListPermissionsResponse, error)
	ListRolePermissions(context.Context, *ListRolePermissionsRequest) (*ListPermissionsResponse, error)
	ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
}

func RegisterConsoleIAMHTTPServer(s *http.Server, srv ConsoleIAMHTTPServer) {
	r := s.Route("/")
	r.POST("/console/v1/tenants/{tenant_id}/users", _ConsoleIAM_CreateUser0_HTTP_Handler(srv))
	r.GET("/console/v1/tenants/{tenant_id}/users", _ConsoleIAM_ListUsers0_HTTP_Handler(srv))
	r.POST("/console/v1/roles", _ConsoleIAM_CreateRole0_HTTP_Handler(srv))
	r.GET("/console/v1/roles", _ConsoleIAM_ListRoles0_HTTP_Handler(srv))
	r.POST("/console/v1/users/{user_id}/roles", _ConsoleIAM_AssignRole0_HTTP_Handler(srv))
	r.GET("/console/v1/permissions", _ConsoleIAM_ListPermissions0_HTTP_Handler(srv))
	r.POST("/console/v1/roles/{role_id}/permissions", _ConsoleIAM_AssignRolePermissions0_HTTP_Handler(srv))
	r.GET("/console/v1/roles/{role_id}/permissions", _ConsoleIAM_ListRolePermissions0_HTTP_Handler(srv))
}

func _ConsoleIAM_CreateUser0_HTTP_Handler(srv ConsoleIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleIAMCreateUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateUser(ctx, req.(*CreateUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleIAM_ListUsers0_HTTP_Handler(srv ConsoleIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListUsersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleIAMListUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUsers(ctx, req.(*ListUsersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListUsersResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleIAM_CreateRole0_HTTP_Handler(srv ConsoleIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleIAMCreateRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRole(ctx, req.(*CreateRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RoleResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleIAM_ListRoles0_HTTP_Handler(srv ConsoleIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRolesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleIAMListRoles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRoles(ctx, req.(*ListRolesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRolesResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleIAM_AssignRole0_HTTP_Handler(srv ConsoleIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleIAMAssignRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignRole(ctx, req.(*AssignRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ConsoleIAM_ListPermissions0_HTTP_Handler(srv ConsoleIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPermissionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleIAMListPermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPermissions(ctx, req.(*ListPermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPermissionsResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleIAM_AssignRolePermissions0_HTTP_Handler(srv ConsoleIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignRolePermissionsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleIAMAssignRolePermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignRolePermissions(ctx, req.(*AssignRolePermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ConsoleIAM_ListRolePermissions0_HTTP_Handler(srv ConsoleIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRolePermissionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleIAMListRolePermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRolePermissions(ctx, req.(*ListRolePermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPermissionsResponse)
		return ctx.Result(200, reply)
	}
}

type ConsoleIAMHTTPClient interface {
	AssignRole(ctx context.Context, req *AssignRoleRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	AssignRolePermissions(ctx context.Context, req *AssignRolePermissionsRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	CreateRole(ctx context.Context, req *CreateRoleRequest, opts ...http.CallOption) (rsp *RoleResponse, err error)
	CreateUser(ctx context.Context, req *CreateUserRequest, opts ...http.CallOption) (rsp *UserResponse, err error)
	ListPermissions(ctx context.Context, req *ListPermissionsRequest, opts ...http.CallOption) (rsp *ListPermissionsResponse, err error)
	ListRolePermissions(ctx context.Context, req *ListRolePermissionsRequest, opts ...http.CallOption) (rsp *ListPermissionsResponse, err error)
	ListRoles(ctx context.Context, req *ListRolesRequest, opts ...http.CallOption) (rsp *ListRolesResponse, err error)
	ListUsers(ctx context.Context, req *ListUsersRequest, opts ...http.CallOption) (rsp *ListUsersResponse, err error)
}

type ConsoleIAMHTTPClientImpl struct {
	cc *http.Client
}

func NewConsoleIAMHTTPClient(client *http.Client) ConsoleIAMHTTPClient {
	return &ConsoleIAMHTTPClientImpl{client}
}

func (c *ConsoleIAMHTTPClientImpl) AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/console/v1/users/{user_id}/roles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConsoleIAMAssignRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleIAMHTTPClientImpl) AssignRolePermissions(ctx context.Context, in *AssignRolePermissionsRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/console/v1/roles/{role_id}/permissions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConsoleIAMAssignRolePermissions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleIAMHTTPClientImpl) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...http.CallOption) (*RoleResponse, error) {
	var out RoleResponse
	pattern := "/console/v1/roles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConsoleIAMCreateRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleIAMHTTPClientImpl) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...http.CallOption) (*UserResponse, error) {
	var out UserResponse
	pattern := "/console/v1/tenants/{tenant_id}/users"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConsoleIAMCreateUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleIAMHTTPClientImpl) ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...http.CallOption) (*ListPermissionsResponse, error) {
	var out ListPermissionsResponse
	pattern := "/console/v1/permissions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleIAMListPermissions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleIAMHTTPClientImpl) ListRolePermissions(ctx context.Context, in *ListRolePermissionsRequest, opts ...http.CallOption) (*ListPermissionsResponse, error) {
	var out ListPermissionsResponse
	pattern := "/console/v1/roles/{role_id}/permissions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleIAMListRolePermissions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleIAMHTTPClientImpl) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...http.CallOption) (*ListRolesResponse, error) {
	var out ListRolesResponse
	pattern := "/console/v1/roles"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleIAMListRoles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleIAMHTTPClientImpl) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...http.CallOption) (*ListUsersResponse, error) {
	var out ListUsersResponse
	pattern := "/console/v1/tenants/{tenant_id}/users"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleIAMListUsers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
