// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/iam/v1/platform_iam.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPlatformIAMAssignPlatformAdminRole = "/api.iam.v1.PlatformIAM/AssignPlatformAdminRole"
const OperationPlatformIAMAssignPlatformRolePermissions = "/api.iam.v1.PlatformIAM/AssignPlatformRolePermissions"
const OperationPlatformIAMCreatePermission = "/api.iam.v1.PlatformIAM/CreatePermission"
const OperationPlatformIAMCreatePlatformAdmin = "/api.iam.v1.PlatformIAM/CreatePlatformAdmin"
const OperationPlatformIAMCreatePlatformRole = "/api.iam.v1.PlatformIAM/CreatePlatformRole"
const OperationPlatformIAMCreateTenant = "/api.iam.v1.PlatformIAM/CreateTenant"
const OperationPlatformIAMGetPlatformAdmin = "/api.iam.v1.PlatformIAM/GetPlatformAdmin"
const OperationPlatformIAMGetPlatformRole = "/api.iam.v1.PlatformIAM/GetPlatformRole"
const OperationPlatformIAMGetTenant = "/api.iam.v1.PlatformIAM/GetTenant"
const OperationPlatformIAMListPermissions = "/api.iam.v1.PlatformIAM/ListPermissions"
const OperationPlatformIAMListPlatformAdminRoles = "/api.iam.v1.PlatformIAM/ListPlatformAdminRoles"
const OperationPlatformIAMListPlatformAdmins = "/api.iam.v1.PlatformIAM/ListPlatformAdmins"
const OperationPlatformIAMListPlatformRolePermissions = "/api.iam.v1.PlatformIAM/ListPlatformRolePermissions"
const OperationPlatformIAMListPlatformRoles = "/api.iam.v1.PlatformIAM/ListPlatformRoles"
const OperationPlatformIAMListTenants = "/api.iam.v1.PlatformIAM/ListTenants"
const OperationPlatformIAMRemovePlatformAdminRole = "/api.iam.v1.PlatformIAM/RemovePlatformAdminRole"

type PlatformIAMHTTPServer interface {
	AssignPlatformAdminRole(context.Context, *AssignPlatformAdminRoleRequest) (*emptypb.Empty, error)
	AssignPlatformRolePermissions(context.Context, *AssignPlatformRolePermissionsRequest) (*emptypb.Empty, error)
	CreatePermission(context.Context, *CreatePermissionRequest) (*PermissionResponse, error)
	CreatePlatformAdmin(context.Context, *CreatePlatformAdminRequest) (*PlatformAdminResponse, error)
	CreatePlatformRole(context.Context, *CreatePlatformRoleRequest) (*PlatformRoleResponse, error)
	CreateTenant(context.Context, *CreateTenantRequest) (*TenantResponse, error)
	GetPlatformAdmin(context.Context, *GetPlatformAdminRequest) (*PlatformAdminResponse, error)
	GetPlatformRole(context.Context, *GetPlatformRoleRequest) (*PlatformRoleResponse, error)
	GetTenant(context.Context, *GetTenantRequest) (*TenantResponse, error)
	ListPermissions(context.Context, *ListPermissionsRequest) (*ListPermissionsResponse, error)
	ListPlatformAdminRoles(context.Context, *ListPlatformAdminRolesRequest) (*ListPlatformRolesResponse, error)
	ListPlatformAdmins(context.Context, *ListPlatformAdminsRequest) (*ListPlatformAdminsResponse, error)
	ListPlatformRolePermissions(context.Context, *ListPlatformRolePermissionsRequest) (*ListPermissionsResponse, error)
	ListPlatformRoles(context.Context, *ListPlatformRolesRequest) (*ListPlatformRolesResponse, error)
	ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error)
	RemovePlatformAdminRole(context.Context, *RemovePlatformAdminRoleRequest) (*emptypb.Empty, error)
}

func RegisterPlatformIAMHTTPServer(s *http.Server, srv PlatformIAMHTTPServer) {
	r := s.Route("/")
	r.POST("/platform/v1/tenants", _PlatformIAM_CreateTenant0_HTTP_Handler(srv))
	r.GET("/platform/v1/tenants/{id}", _PlatformIAM_GetTenant0_HTTP_Handler(srv))
	r.GET("/platform/v1/tenants", _PlatformIAM_ListTenants0_HTTP_Handler(srv))
	r.POST("/platform/v1/permissions", _PlatformIAM_CreatePermission0_HTTP_Handler(srv))
	r.GET("/platform/v1/permissions", _PlatformIAM_ListPermissions1_HTTP_Handler(srv))
	r.POST("/platform/v1/admins", _PlatformIAM_CreatePlatformAdmin0_HTTP_Handler(srv))
	r.GET("/platform/v1/admins", _PlatformIAM_ListPlatformAdmins0_HTTP_Handler(srv))
	r.GET("/platform/v1/admins/{id}", _PlatformIAM_GetPlatformAdmin0_HTTP_Handler(srv))
	r.POST("/platform/v1/roles", _PlatformIAM_CreatePlatformRole0_HTTP_Handler(srv))
	r.GET("/platform/v1/roles", _PlatformIAM_ListPlatformRoles0_HTTP_Handler(srv))
	r.GET("/platform/v1/roles/{id}", _PlatformIAM_GetPlatformRole0_HTTP_Handler(srv))
	r.POST("/platform/v1/admins/{admin_id}/roles", _PlatformIAM_AssignPlatformAdminRole0_HTTP_Handler(srv))
	r.GET("/platform/v1/admins/{admin_id}/roles", _PlatformIAM_ListPlatformAdminRoles0_HTTP_Handler(srv))
	r.DELETE("/platform/v1/admins/{admin_id}/roles/{role_id}", _PlatformIAM_RemovePlatformAdminRole0_HTTP_Handler(srv))
	r.POST("/platform/v1/roles/{role_id}/permissions", _PlatformIAM_AssignPlatformRolePermissions0_HTTP_Handler(srv))
	r.GET("/platform/v1/roles/{role_id}/permissions", _PlatformIAM_ListPlatformRolePermissions0_HTTP_Handler(srv))
}

func _PlatformIAM_CreateTenant0_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTenantRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMCreateTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTenant(ctx, req.(*CreateTenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TenantResponse)
		return ctx.Result(200, reply)
	}
}

func _PlatformIAM_GetTenant0_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTenantRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMGetTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTenant(ctx, req.(*GetTenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TenantResponse)
		return ctx.Result(200, reply)
	}
}

func _PlatformIAM_ListTenants0_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTenantsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMListTenants)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTenants(ctx, req.(*ListTenantsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTenantsResponse)
		return ctx.Result(200, reply)
	}
}

func _PlatformIAM_CreatePermission0_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePermissionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMCreatePermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePermission(ctx, req.(*CreatePermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PermissionResponse)
		return ctx.Result(200, reply)
	}
}

func _PlatformIAM_ListPermissions1_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPermissionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMListPermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPermissions(ctx, req.(*ListPermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPermissionsResponse)
		return ctx.Result(200, reply)
	}
}

func _PlatformIAM_CreatePlatformAdmin0_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePlatformAdminRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMCreatePlatformAdmin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePlatformAdmin(ctx, req.(*CreatePlatformAdminRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PlatformAdminResponse)
		return ctx.Result(200, reply)
	}
}

func _PlatformIAM_ListPlatformAdmins0_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPlatformAdminsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMListPlatformAdmins)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPlatformAdmins(ctx, req.(*ListPlatformAdminsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPlatformAdminsResponse)
		return ctx.Result(200, reply)
	}
}

func _PlatformIAM_GetPlatformAdmin0_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPlatformAdminRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMGetPlatformAdmin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPlatformAdmin(ctx, req.(*GetPlatformAdminRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PlatformAdminResponse)
		return ctx.Result(200, reply)
	}
}

func _PlatformIAM_CreatePlatformRole0_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePlatformRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMCreatePlatformRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePlatformRole(ctx, req.(*CreatePlatformRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PlatformRoleResponse)
		return ctx.Result(200, reply)
	}
}

func _PlatformIAM_ListPlatformRoles0_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPlatformRolesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMListPlatformRoles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPlatformRoles(ctx, req.(*ListPlatformRolesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPlatformRolesResponse)
		return ctx.Result(200, reply)
	}
}

func _PlatformIAM_GetPlatformRole0_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPlatformRoleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMGetPlatformRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPlatformRole(ctx, req.(*GetPlatformRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PlatformRoleResponse)
		return ctx.Result(200, reply)
	}
}

func _PlatformIAM_AssignPlatformAdminRole0_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignPlatformAdminRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMAssignPlatformAdminRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignPlatformAdminRole(ctx, req.(*AssignPlatformAdminRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PlatformIAM_ListPlatformAdminRoles0_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPlatformAdminRolesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMListPlatformAdminRoles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPlatformAdminRoles(ctx, req.(*ListPlatformAdminRolesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPlatformRolesResponse)
		return ctx.Result(200, reply)
	}
}

func _PlatformIAM_RemovePlatformAdminRole0_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemovePlatformAdminRoleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMRemovePlatformAdminRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemovePlatformAdminRole(ctx, req.(*RemovePlatformAdminRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PlatformIAM_AssignPlatformRolePermissions0_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignPlatformRolePermissionsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMAssignPlatformRolePermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignPlatformRolePermissions(ctx, req.(*AssignPlatformRolePermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PlatformIAM_ListPlatformRolePermissions0_HTTP_Handler(srv PlatformIAMHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPlatformRolePermissionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformIAMListPlatformRolePermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPlatformRolePermissions(ctx, req.(*ListPlatformRolePermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPermissionsResponse)
		return ctx.Result(200, reply)
	}
}

type PlatformIAMHTTPClient interface {
	AssignPlatformAdminRole(ctx context.Context, req *AssignPlatformAdminRoleRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	AssignPlatformRolePermissions(ctx context.Context, req *AssignPlatformRolePermissionsRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	CreatePermission(ctx context.Context, req *CreatePermissionRequest, opts ...http.CallOption) (rsp *PermissionResponse, err error)
	CreatePlatformAdmin(ctx context.Context, req *CreatePlatformAdminRequest, opts ...http.CallOption) (rsp *PlatformAdminResponse, err error)
	CreatePlatformRole(ctx context.Context, req *CreatePlatformRoleRequest, opts ...http.CallOption) (rsp *PlatformRoleResponse, err error)
	CreateTenant(ctx context.Context, req *CreateTenantRequest, opts ...http.CallOption) (rsp *TenantResponse, err error)
	GetPlatformAdmin(ctx context.Context, req *GetPlatformAdminRequest, opts ...http.CallOption) (rsp *PlatformAdminResponse, err error)
	GetPlatformRole(ctx context.Context, req *GetPlatformRoleRequest, opts ...http.CallOption) (rsp *PlatformRoleResponse, err error)
	GetTenant(ctx context.Context, req *GetTenantRequest, opts ...http.CallOption) (rsp *TenantResponse, err error)
	ListPermissions(ctx context.Context, req *ListPermissionsRequest, opts ...http.CallOption) (rsp *ListPermissionsResponse, err error)
	ListPlatformAdminRoles(ctx context.Context, req *ListPlatformAdminRolesRequest, opts ...http.CallOption) (rsp *ListPlatformRolesResponse, err error)
	ListPlatformAdmins(ctx context.Context, req *ListPlatformAdminsRequest, opts ...http.CallOption) (rsp *ListPlatformAdminsResponse, err error)
	ListPlatformRolePermissions(ctx context.Context, req *ListPlatformRolePermissionsRequest, opts ...http.CallOption) (rsp *ListPermissionsResponse, err error)
	ListPlatformRoles(ctx context.Context, req *ListPlatformRolesRequest, opts ...http.CallOption) (rsp *ListPlatformRolesResponse, err error)
	ListTenants(ctx context.Context, req *ListTenantsRequest, opts ...http.CallOption) (rsp *ListTenantsResponse, err error)
	RemovePlatformAdminRole(ctx context.Context, req *RemovePlatformAdminRoleRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type PlatformIAMHTTPClientImpl struct {
	cc *http.Client
}

func NewPlatformIAMHTTPClient(client *http.Client) PlatformIAMHTTPClient {
	return &PlatformIAMHTTPClientImpl{client}
}

func (c *PlatformIAMHTTPClientImpl) AssignPlatformAdminRole(ctx context.Context, in *AssignPlatformAdminRoleRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/platform/v1/admins/{admin_id}/roles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPlatformIAMAssignPlatformAdminRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PlatformIAMHTTPClientImpl) AssignPlatformRolePermissions(ctx context.Context, in *AssignPlatformRolePermissionsRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/platform/v1/roles/{role_id}/permissions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPlatformIAMAssignPlatformRolePermissions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PlatformIAMHTTPClientImpl) CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...http.CallOption) (*PermissionResponse, error) {
	var out PermissionResponse
	pattern := "/platform/v1/permissions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPlatformIAMCreatePermission))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PlatformIAMHTTPClientImpl) CreatePlatformAdmin(ctx context.Context, in *CreatePlatformAdminRequest, opts ...http.CallOption) (*PlatformAdminResponse, error) {
	var out PlatformAdminResponse
	pattern := "/platform/v1/admins"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPlatformIAMCreatePlatformAdmin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PlatformIAMHTTPClientImpl) CreatePlatformRole(ctx context.Context, in *CreatePlatformRoleRequest, opts ...http.CallOption) (*PlatformRoleResponse, error) {
	var out PlatformRoleResponse
	pattern := "/platform/v1/roles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPlatformIAMCreatePlatformRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PlatformIAMHTTPClientImpl) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...http.CallOption) (*TenantResponse, error) {
	var out TenantResponse
	pattern := "/platform/v1/tenants"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPlatformIAMCreateTenant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PlatformIAMHTTPClientImpl) GetPlatformAdmin(ctx context.Context, in *GetPlatformAdminRequest, opts ...http.CallOption) (*PlatformAdminResponse, error) {
	var out PlatformAdminResponse
	pattern := "/platform/v1/admins/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPlatformIAMGetPlatformAdmin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PlatformIAMHTTPClientImpl) GetPlatformRole(ctx context.Context, in *GetPlatformRoleRequest, opts ...http.CallOption) (*PlatformRoleResponse, error) {
	var out PlatformRoleResponse
	pattern := "/platform/v1/roles/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPlatformIAMGetPlatformRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PlatformIAMHTTPClientImpl) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...http.CallOption) (*TenantResponse, error) {
	var out TenantResponse
	pattern := "/platform/v1/tenants/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPlatformIAMGetTenant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PlatformIAMHTTPClientImpl) ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...http.CallOption) (*ListPermissionsResponse, error) {
	var out ListPermissionsResponse
	pattern := "/platform/v1/permissions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPlatformIAMListPermissions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PlatformIAMHTTPClientImpl) ListPlatformAdminRoles(ctx context.Context, in *ListPlatformAdminRolesRequest, opts ...http.CallOption) (*ListPlatformRolesResponse, error) {
	var out ListPlatformRolesResponse
	pattern := "/platform/v1/admins/{admin_id}/roles"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPlatformIAMListPlatformAdminRoles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PlatformIAMHTTPClientImpl) ListPlatformAdmins(ctx context.Context, in *ListPlatformAdminsRequest, opts ...http.CallOption) (*ListPlatformAdminsResponse, error) {
	var out ListPlatformAdminsResponse
	pattern := "/platform/v1/admins"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPlatformIAMListPlatformAdmins))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PlatformIAMHTTPClientImpl) ListPlatformRolePermissions(ctx context.Context, in *ListPlatformRolePermissionsRequest, opts ...http.CallOption) (*ListPermissionsResponse, error) {
	var out ListPermissionsResponse
	pattern := "/platform/v1/roles/{role_id}/permissions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPlatformIAMListPlatformRolePermissions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PlatformIAMHTTPClientImpl) ListPlatformRoles(ctx context.Context, in *ListPlatformRolesRequest, opts ...http.CallOption) (*ListPlatformRolesResponse, error) {
	var out ListPlatformRolesResponse
	pattern := "/platform/v1/roles"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPlatformIAMListPlatformRoles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PlatformIAMHTTPClientImpl) ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...http.CallOption) (*ListTenantsResponse, error) {
	var out ListTenantsResponse
	pattern := "/platform/v1/tenants"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPlatformIAMListTenants))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PlatformIAMHTTPClientImpl) RemovePlatformAdminRole(ctx context.Context, in *RemovePlatformAdminRoleRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/platform/v1/admins/{admin_id}/roles/{role_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPlatformIAMRemovePlatformAdminRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
