// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/iam/v1/platform_iam.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlatformIAM_CreateTenant_FullMethodName                  = "/api.iam.v1.PlatformIAM/CreateTenant"
	PlatformIAM_GetTenant_FullMethodName                     = "/api.iam.v1.PlatformIAM/GetTenant"
	PlatformIAM_ListTenants_FullMethodName                   = "/api.iam.v1.PlatformIAM/ListTenants"
	PlatformIAM_CreatePermission_FullMethodName              = "/api.iam.v1.PlatformIAM/CreatePermission"
	PlatformIAM_ListPermissions_FullMethodName               = "/api.iam.v1.PlatformIAM/ListPermissions"
	PlatformIAM_CreatePlatformAdmin_FullMethodName           = "/api.iam.v1.PlatformIAM/CreatePlatformAdmin"
	PlatformIAM_ListPlatformAdmins_FullMethodName            = "/api.iam.v1.PlatformIAM/ListPlatformAdmins"
	PlatformIAM_GetPlatformAdmin_FullMethodName              = "/api.iam.v1.PlatformIAM/GetPlatformAdmin"
	PlatformIAM_CreatePlatformRole_FullMethodName            = "/api.iam.v1.PlatformIAM/CreatePlatformRole"
	PlatformIAM_ListPlatformRoles_FullMethodName             = "/api.iam.v1.PlatformIAM/ListPlatformRoles"
	PlatformIAM_GetPlatformRole_FullMethodName               = "/api.iam.v1.PlatformIAM/GetPlatformRole"
	PlatformIAM_AssignPlatformAdminRole_FullMethodName       = "/api.iam.v1.PlatformIAM/AssignPlatformAdminRole"
	PlatformIAM_ListPlatformAdminRoles_FullMethodName        = "/api.iam.v1.PlatformIAM/ListPlatformAdminRoles"
	PlatformIAM_RemovePlatformAdminRole_FullMethodName       = "/api.iam.v1.PlatformIAM/RemovePlatformAdminRole"
	PlatformIAM_AssignPlatformRolePermissions_FullMethodName = "/api.iam.v1.PlatformIAM/AssignPlatformRolePermissions"
	PlatformIAM_ListPlatformRolePermissions_FullMethodName   = "/api.iam.v1.PlatformIAM/ListPlatformRolePermissions"
)

// PlatformIAMClient is the client API for PlatformIAM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlatformIAMClient interface {
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*TenantResponse, error)
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*TenantResponse, error)
	ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error)
	CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...grpc.CallOption) (*PermissionResponse, error)
	ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error)
	CreatePlatformAdmin(ctx context.Context, in *CreatePlatformAdminRequest, opts ...grpc.CallOption) (*PlatformAdminResponse, error)
	ListPlatformAdmins(ctx context.Context, in *ListPlatformAdminsRequest, opts ...grpc.CallOption) (*ListPlatformAdminsResponse, error)
	GetPlatformAdmin(ctx context.Context, in *GetPlatformAdminRequest, opts ...grpc.CallOption) (*PlatformAdminResponse, error)
	CreatePlatformRole(ctx context.Context, in *CreatePlatformRoleRequest, opts ...grpc.CallOption) (*PlatformRoleResponse, error)
	ListPlatformRoles(ctx context.Context, in *ListPlatformRolesRequest, opts ...grpc.CallOption) (*ListPlatformRolesResponse, error)
	GetPlatformRole(ctx context.Context, in *GetPlatformRoleRequest, opts ...grpc.CallOption) (*PlatformRoleResponse, error)
	AssignPlatformAdminRole(ctx context.Context, in *AssignPlatformAdminRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListPlatformAdminRoles(ctx context.Context, in *ListPlatformAdminRolesRequest, opts ...grpc.CallOption) (*ListPlatformRolesResponse, error)
	RemovePlatformAdminRole(ctx context.Context, in *RemovePlatformAdminRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AssignPlatformRolePermissions(ctx context.Context, in *AssignPlatformRolePermissionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListPlatformRolePermissions(ctx context.Context, in *ListPlatformRolePermissionsRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error)
}

type platformIAMClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformIAMClient(cc grpc.ClientConnInterface) PlatformIAMClient {
	return &platformIAMClient{cc}
}

func (c *platformIAMClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*TenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantResponse)
	err := c.cc.Invoke(ctx, PlatformIAM_CreateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformIAMClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*TenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantResponse)
	err := c.cc.Invoke(ctx, PlatformIAM_GetTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformIAMClient) ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantsResponse)
	err := c.cc.Invoke(ctx, PlatformIAM_ListTenants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformIAMClient) CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...grpc.CallOption) (*PermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermissionResponse)
	err := c.cc.Invoke(ctx, PlatformIAM_CreatePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformIAMClient) ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPermissionsResponse)
	err := c.cc.Invoke(ctx, PlatformIAM_ListPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformIAMClient) CreatePlatformAdmin(ctx context.Context, in *CreatePlatformAdminRequest, opts ...grpc.CallOption) (*PlatformAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformAdminResponse)
	err := c.cc.Invoke(ctx, PlatformIAM_CreatePlatformAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformIAMClient) ListPlatformAdmins(ctx context.Context, in *ListPlatformAdminsRequest, opts ...grpc.CallOption) (*ListPlatformAdminsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlatformAdminsResponse)
	err := c.cc.Invoke(ctx, PlatformIAM_ListPlatformAdmins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformIAMClient) GetPlatformAdmin(ctx context.Context, in *GetPlatformAdminRequest, opts ...grpc.CallOption) (*PlatformAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformAdminResponse)
	err := c.cc.Invoke(ctx, PlatformIAM_GetPlatformAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformIAMClient) CreatePlatformRole(ctx context.Context, in *CreatePlatformRoleRequest, opts ...grpc.CallOption) (*PlatformRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformRoleResponse)
	err := c.cc.Invoke(ctx, PlatformIAM_CreatePlatformRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformIAMClient) ListPlatformRoles(ctx context.Context, in *ListPlatformRolesRequest, opts ...grpc.CallOption) (*ListPlatformRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlatformRolesResponse)
	err := c.cc.Invoke(ctx, PlatformIAM_ListPlatformRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformIAMClient) GetPlatformRole(ctx context.Context, in *GetPlatformRoleRequest, opts ...grpc.CallOption) (*PlatformRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformRoleResponse)
	err := c.cc.Invoke(ctx, PlatformIAM_GetPlatformRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformIAMClient) AssignPlatformAdminRole(ctx context.Context, in *AssignPlatformAdminRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlatformIAM_AssignPlatformAdminRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformIAMClient) ListPlatformAdminRoles(ctx context.Context, in *ListPlatformAdminRolesRequest, opts ...grpc.CallOption) (*ListPlatformRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlatformRolesResponse)
	err := c.cc.Invoke(ctx, PlatformIAM_ListPlatformAdminRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformIAMClient) RemovePlatformAdminRole(ctx context.Context, in *RemovePlatformAdminRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlatformIAM_RemovePlatformAdminRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformIAMClient) AssignPlatformRolePermissions(ctx context.Context, in *AssignPlatformRolePermissionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlatformIAM_AssignPlatformRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformIAMClient) ListPlatformRolePermissions(ctx context.Context, in *ListPlatformRolePermissionsRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPermissionsResponse)
	err := c.cc.Invoke(ctx, PlatformIAM_ListPlatformRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformIAMServer is the server API for PlatformIAM service.
// All implementations must embed UnimplementedPlatformIAMServer
// for forward compatibility.
type PlatformIAMServer interface {
	CreateTenant(context.Context, *CreateTenantRequest) (*TenantResponse, error)
	GetTenant(context.Context, *GetTenantRequest) (*TenantResponse, error)
	ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error)
	CreatePermission(context.Context, *CreatePermissionRequest) (*PermissionResponse, error)
	ListPermissions(context.Context, *ListPermissionsRequest) (*ListPermissionsResponse, error)
	CreatePlatformAdmin(context.Context, *CreatePlatformAdminRequest) (*PlatformAdminResponse, error)
	ListPlatformAdmins(context.Context, *ListPlatformAdminsRequest) (*ListPlatformAdminsResponse, error)
	GetPlatformAdmin(context.Context, *GetPlatformAdminRequest) (*PlatformAdminResponse, error)
	CreatePlatformRole(context.Context, *CreatePlatformRoleRequest) (*PlatformRoleResponse, error)
	ListPlatformRoles(context.Context, *ListPlatformRolesRequest) (*ListPlatformRolesResponse, error)
	GetPlatformRole(context.Context, *GetPlatformRoleRequest) (*PlatformRoleResponse, error)
	AssignPlatformAdminRole(context.Context, *AssignPlatformAdminRoleRequest) (*emptypb.Empty, error)
	ListPlatformAdminRoles(context.Context, *ListPlatformAdminRolesRequest) (*ListPlatformRolesResponse, error)
	RemovePlatformAdminRole(context.Context, *RemovePlatformAdminRoleRequest) (*emptypb.Empty, error)
	AssignPlatformRolePermissions(context.Context, *AssignPlatformRolePermissionsRequest) (*emptypb.Empty, error)
	ListPlatformRolePermissions(context.Context, *ListPlatformRolePermissionsRequest) (*ListPermissionsResponse, error)
	mustEmbedUnimplementedPlatformIAMServer()
}

// UnimplementedPlatformIAMServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformIAMServer struct{}

func (UnimplementedPlatformIAMServer) CreateTenant(context.Context, *CreateTenantRequest) (*TenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedPlatformIAMServer) GetTenant(context.Context, *GetTenantRequest) (*TenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedPlatformIAMServer) ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTenants not implemented")
}
func (UnimplementedPlatformIAMServer) CreatePermission(context.Context, *CreatePermissionRequest) (*PermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePermission not implemented")
}
func (UnimplementedPlatformIAMServer) ListPermissions(context.Context, *ListPermissionsRequest) (*ListPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPermissions not implemented")
}
func (UnimplementedPlatformIAMServer) CreatePlatformAdmin(context.Context, *CreatePlatformAdminRequest) (*PlatformAdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlatformAdmin not implemented")
}
func (UnimplementedPlatformIAMServer) ListPlatformAdmins(context.Context, *ListPlatformAdminsRequest) (*ListPlatformAdminsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlatformAdmins not implemented")
}
func (UnimplementedPlatformIAMServer) GetPlatformAdmin(context.Context, *GetPlatformAdminRequest) (*PlatformAdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatformAdmin not implemented")
}
func (UnimplementedPlatformIAMServer) CreatePlatformRole(context.Context, *CreatePlatformRoleRequest) (*PlatformRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlatformRole not implemented")
}
func (UnimplementedPlatformIAMServer) ListPlatformRoles(context.Context, *ListPlatformRolesRequest) (*ListPlatformRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlatformRoles not implemented")
}
func (UnimplementedPlatformIAMServer) GetPlatformRole(context.Context, *GetPlatformRoleRequest) (*PlatformRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatformRole not implemented")
}
func (UnimplementedPlatformIAMServer) AssignPlatformAdminRole(context.Context, *AssignPlatformAdminRoleRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignPlatformAdminRole not implemented")
}
func (UnimplementedPlatformIAMServer) ListPlatformAdminRoles(context.Context, *ListPlatformAdminRolesRequest) (*ListPlatformRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlatformAdminRoles not implemented")
}
func (UnimplementedPlatformIAMServer) RemovePlatformAdminRole(context.Context, *RemovePlatformAdminRoleRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePlatformAdminRole not implemented")
}
func (UnimplementedPlatformIAMServer) AssignPlatformRolePermissions(context.Context, *AssignPlatformRolePermissionsRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignPlatformRolePermissions not implemented")
}
func (UnimplementedPlatformIAMServer) ListPlatformRolePermissions(context.Context, *ListPlatformRolePermissionsRequest) (*ListPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlatformRolePermissions not implemented")
}
func (UnimplementedPlatformIAMServer) mustEmbedUnimplementedPlatformIAMServer() {}
func (UnimplementedPlatformIAMServer) testEmbeddedByValue()                     {}

// UnsafePlatformIAMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformIAMServer will
// result in compilation errors.
type UnsafePlatformIAMServer interface {
	mustEmbedUnimplementedPlatformIAMServer()
}

func RegisterPlatformIAMServer(s grpc.ServiceRegistrar, srv PlatformIAMServer) {
	// If the following call panics, it indicates UnimplementedPlatformIAMServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlatformIAM_ServiceDesc, srv)
}

func _PlatformIAM_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformIAM_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_GetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformIAM_ListTenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).ListTenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_ListTenants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).ListTenants(ctx, req.(*ListTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformIAM_CreatePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).CreatePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_CreatePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).CreatePermission(ctx, req.(*CreatePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformIAM_ListPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).ListPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_ListPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).ListPermissions(ctx, req.(*ListPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformIAM_CreatePlatformAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlatformAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).CreatePlatformAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_CreatePlatformAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).CreatePlatformAdmin(ctx, req.(*CreatePlatformAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformIAM_ListPlatformAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlatformAdminsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).ListPlatformAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_ListPlatformAdmins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).ListPlatformAdmins(ctx, req.(*ListPlatformAdminsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformIAM_GetPlatformAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlatformAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).GetPlatformAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_GetPlatformAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).GetPlatformAdmin(ctx, req.(*GetPlatformAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformIAM_CreatePlatformRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlatformRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).CreatePlatformRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_CreatePlatformRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).CreatePlatformRole(ctx, req.(*CreatePlatformRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformIAM_ListPlatformRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlatformRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).ListPlatformRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_ListPlatformRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).ListPlatformRoles(ctx, req.(*ListPlatformRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformIAM_GetPlatformRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlatformRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).GetPlatformRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_GetPlatformRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).GetPlatformRole(ctx, req.(*GetPlatformRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformIAM_AssignPlatformAdminRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignPlatformAdminRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).AssignPlatformAdminRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_AssignPlatformAdminRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).AssignPlatformAdminRole(ctx, req.(*AssignPlatformAdminRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformIAM_ListPlatformAdminRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlatformAdminRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).ListPlatformAdminRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_ListPlatformAdminRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).ListPlatformAdminRoles(ctx, req.(*ListPlatformAdminRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformIAM_RemovePlatformAdminRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePlatformAdminRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).RemovePlatformAdminRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_RemovePlatformAdminRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).RemovePlatformAdminRole(ctx, req.(*RemovePlatformAdminRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformIAM_AssignPlatformRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignPlatformRolePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).AssignPlatformRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_AssignPlatformRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).AssignPlatformRolePermissions(ctx, req.(*AssignPlatformRolePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformIAM_ListPlatformRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlatformRolePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformIAMServer).ListPlatformRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformIAM_ListPlatformRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformIAMServer).ListPlatformRolePermissions(ctx, req.(*ListPlatformRolePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatformIAM_ServiceDesc is the grpc.ServiceDesc for PlatformIAM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformIAM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.iam.v1.PlatformIAM",
	HandlerType: (*PlatformIAMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTenant",
			Handler:    _PlatformIAM_CreateTenant_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _PlatformIAM_GetTenant_Handler,
		},
		{
			MethodName: "ListTenants",
			Handler:    _PlatformIAM_ListTenants_Handler,
		},
		{
			MethodName: "CreatePermission",
			Handler:    _PlatformIAM_CreatePermission_Handler,
		},
		{
			MethodName: "ListPermissions",
			Handler:    _PlatformIAM_ListPermissions_Handler,
		},
		{
			MethodName: "CreatePlatformAdmin",
			Handler:    _PlatformIAM_CreatePlatformAdmin_Handler,
		},
		{
			MethodName: "ListPlatformAdmins",
			Handler:    _PlatformIAM_ListPlatformAdmins_Handler,
		},
		{
			MethodName: "GetPlatformAdmin",
			Handler:    _PlatformIAM_GetPlatformAdmin_Handler,
		},
		{
			MethodName: "CreatePlatformRole",
			Handler:    _PlatformIAM_CreatePlatformRole_Handler,
		},
		{
			MethodName: "ListPlatformRoles",
			Handler:    _PlatformIAM_ListPlatformRoles_Handler,
		},
		{
			MethodName: "GetPlatformRole",
			Handler:    _PlatformIAM_GetPlatformRole_Handler,
		},
		{
			MethodName: "AssignPlatformAdminRole",
			Handler:    _PlatformIAM_AssignPlatformAdminRole_Handler,
		},
		{
			MethodName: "ListPlatformAdminRoles",
			Handler:    _PlatformIAM_ListPlatformAdminRoles_Handler,
		},
		{
			MethodName: "RemovePlatformAdminRole",
			Handler:    _PlatformIAM_RemovePlatformAdminRole_Handler,
		},
		{
			MethodName: "AssignPlatformRolePermissions",
			Handler:    _PlatformIAM_AssignPlatformRolePermissions_Handler,
		},
		{
			MethodName: "ListPlatformRolePermissions",
			Handler:    _PlatformIAM_ListPlatformRolePermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/iam/v1/platform_iam.proto",
}
