// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/auth/v1/auth.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationConsoleAuthLogin = "/api.auth.v1.ConsoleAuth/Login"
const OperationConsoleAuthRegister = "/api.auth.v1.ConsoleAuth/Register"

type ConsoleAuthHTTPServer interface {
	Login(context.Context, *ConsoleLoginRequest) (*AuthResponse, error)
	Register(context.Context, *ConsoleRegisterRequest) (*AuthResponse, error)
}

func RegisterConsoleAuthHTTPServer(s *http.Server, srv ConsoleAuthHTTPServer) {
	r := s.Route("/")
	r.POST("/console/v1/register", _ConsoleAuth_Register0_HTTP_Handler(srv))
	r.POST("/console/v1/login", _ConsoleAuth_Login0_HTTP_Handler(srv))
}

func _ConsoleAuth_Register0_HTTP_Handler(srv ConsoleAuthHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConsoleRegisterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleAuthRegister)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Register(ctx, req.(*ConsoleRegisterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AuthResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleAuth_Login0_HTTP_Handler(srv ConsoleAuthHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConsoleLoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleAuthLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*ConsoleLoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AuthResponse)
		return ctx.Result(200, reply)
	}
}

type ConsoleAuthHTTPClient interface {
	Login(ctx context.Context, req *ConsoleLoginRequest, opts ...http.CallOption) (rsp *AuthResponse, err error)
	Register(ctx context.Context, req *ConsoleRegisterRequest, opts ...http.CallOption) (rsp *AuthResponse, err error)
}

type ConsoleAuthHTTPClientImpl struct {
	cc *http.Client
}

func NewConsoleAuthHTTPClient(client *http.Client) ConsoleAuthHTTPClient {
	return &ConsoleAuthHTTPClientImpl{client}
}

func (c *ConsoleAuthHTTPClientImpl) Login(ctx context.Context, in *ConsoleLoginRequest, opts ...http.CallOption) (*AuthResponse, error) {
	var out AuthResponse
	pattern := "/console/v1/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConsoleAuthLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleAuthHTTPClientImpl) Register(ctx context.Context, in *ConsoleRegisterRequest, opts ...http.CallOption) (*AuthResponse, error) {
	var out AuthResponse
	pattern := "/console/v1/register"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConsoleAuthRegister))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationPlatformAuthLogin = "/api.auth.v1.PlatformAuth/Login"

type PlatformAuthHTTPServer interface {
	Login(context.Context, *PlatformLoginRequest) (*AuthResponse, error)
}

func RegisterPlatformAuthHTTPServer(s *http.Server, srv PlatformAuthHTTPServer) {
	r := s.Route("/")
	r.POST("/platform/v1/login", _PlatformAuth_Login1_HTTP_Handler(srv))
}

func _PlatformAuth_Login1_HTTP_Handler(srv PlatformAuthHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PlatformLoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformAuthLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*PlatformLoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AuthResponse)
		return ctx.Result(200, reply)
	}
}

type PlatformAuthHTTPClient interface {
	Login(ctx context.Context, req *PlatformLoginRequest, opts ...http.CallOption) (rsp *AuthResponse, err error)
}

type PlatformAuthHTTPClientImpl struct {
	cc *http.Client
}

func NewPlatformAuthHTTPClient(client *http.Client) PlatformAuthHTTPClient {
	return &PlatformAuthHTTPClientImpl{client}
}

func (c *PlatformAuthHTTPClientImpl) Login(ctx context.Context, in *PlatformLoginRequest, opts ...http.CallOption) (*AuthResponse, error) {
	var out AuthResponse
	pattern := "/platform/v1/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPlatformAuthLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
