// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/analytics/v1/console_analytics.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationConsoleAnalyticsGetKBGaps = "/api.analytics.v1.ConsoleAnalytics/GetKBGaps"
const OperationConsoleAnalyticsGetLatency = "/api.analytics.v1.ConsoleAnalytics/GetLatency"
const OperationConsoleAnalyticsGetOverview = "/api.analytics.v1.ConsoleAnalytics/GetOverview"
const OperationConsoleAnalyticsGetTopQuestions = "/api.analytics.v1.ConsoleAnalytics/GetTopQuestions"

type ConsoleAnalyticsHTTPServer interface {
	GetKBGaps(context.Context, *GetKBGapsRequest) (*GetKBGapsResponse, error)
	GetLatency(context.Context, *GetLatencyRequest) (*GetLatencyResponse, error)
	GetOverview(context.Context, *GetOverviewRequest) (*GetOverviewResponse, error)
	GetTopQuestions(context.Context, *GetTopQuestionsRequest) (*GetTopQuestionsResponse, error)
}

func RegisterConsoleAnalyticsHTTPServer(s *http.Server, srv ConsoleAnalyticsHTTPServer) {
	r := s.Route("/")
	r.GET("/console/v1/analytics/overview", _ConsoleAnalytics_GetOverview0_HTTP_Handler(srv))
	r.GET("/console/v1/analytics/latency", _ConsoleAnalytics_GetLatency0_HTTP_Handler(srv))
	r.GET("/console/v1/analytics/top_questions", _ConsoleAnalytics_GetTopQuestions0_HTTP_Handler(srv))
	r.GET("/console/v1/analytics/kb_gaps", _ConsoleAnalytics_GetKBGaps0_HTTP_Handler(srv))
}

func _ConsoleAnalytics_GetOverview0_HTTP_Handler(srv ConsoleAnalyticsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOverviewRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleAnalyticsGetOverview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOverview(ctx, req.(*GetOverviewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOverviewResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleAnalytics_GetLatency0_HTTP_Handler(srv ConsoleAnalyticsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLatencyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleAnalyticsGetLatency)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLatency(ctx, req.(*GetLatencyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLatencyResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleAnalytics_GetTopQuestions0_HTTP_Handler(srv ConsoleAnalyticsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTopQuestionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleAnalyticsGetTopQuestions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTopQuestions(ctx, req.(*GetTopQuestionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTopQuestionsResponse)
		return ctx.Result(200, reply)
	}
}

func _ConsoleAnalytics_GetKBGaps0_HTTP_Handler(srv ConsoleAnalyticsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetKBGapsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsoleAnalyticsGetKBGaps)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetKBGaps(ctx, req.(*GetKBGapsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetKBGapsResponse)
		return ctx.Result(200, reply)
	}
}

type ConsoleAnalyticsHTTPClient interface {
	GetKBGaps(ctx context.Context, req *GetKBGapsRequest, opts ...http.CallOption) (rsp *GetKBGapsResponse, err error)
	GetLatency(ctx context.Context, req *GetLatencyRequest, opts ...http.CallOption) (rsp *GetLatencyResponse, err error)
	GetOverview(ctx context.Context, req *GetOverviewRequest, opts ...http.CallOption) (rsp *GetOverviewResponse, err error)
	GetTopQuestions(ctx context.Context, req *GetTopQuestionsRequest, opts ...http.CallOption) (rsp *GetTopQuestionsResponse, err error)
}

type ConsoleAnalyticsHTTPClientImpl struct {
	cc *http.Client
}

func NewConsoleAnalyticsHTTPClient(client *http.Client) ConsoleAnalyticsHTTPClient {
	return &ConsoleAnalyticsHTTPClientImpl{client}
}

func (c *ConsoleAnalyticsHTTPClientImpl) GetKBGaps(ctx context.Context, in *GetKBGapsRequest, opts ...http.CallOption) (*GetKBGapsResponse, error) {
	var out GetKBGapsResponse
	pattern := "/console/v1/analytics/kb_gaps"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleAnalyticsGetKBGaps))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleAnalyticsHTTPClientImpl) GetLatency(ctx context.Context, in *GetLatencyRequest, opts ...http.CallOption) (*GetLatencyResponse, error) {
	var out GetLatencyResponse
	pattern := "/console/v1/analytics/latency"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleAnalyticsGetLatency))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleAnalyticsHTTPClientImpl) GetOverview(ctx context.Context, in *GetOverviewRequest, opts ...http.CallOption) (*GetOverviewResponse, error) {
	var out GetOverviewResponse
	pattern := "/console/v1/analytics/overview"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleAnalyticsGetOverview))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConsoleAnalyticsHTTPClientImpl) GetTopQuestions(ctx context.Context, in *GetTopQuestionsRequest, opts ...http.CallOption) (*GetTopQuestionsResponse, error) {
	var out GetTopQuestionsResponse
	pattern := "/console/v1/analytics/top_questions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsoleAnalyticsGetTopQuestions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
