// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/analytics/v1/console_analytics.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverviewRequest) Reset() {
	*x = GetOverviewRequest{}
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewRequest) ProtoMessage() {}

func (x *GetOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewRequest.ProtoReflect.Descriptor instead.
func (*GetOverviewRequest) Descriptor() ([]byte, []int) {
	return file_api_analytics_v1_console_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetOverviewRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *GetOverviewRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetOverviewRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type Overview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalQueries  int64                  `protobuf:"varint,1,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`
	HitQueries    int64                  `protobuf:"varint,2,opt,name=hit_queries,json=hitQueries,proto3" json:"hit_queries,omitempty"`
	HitRate       float64                `protobuf:"fixed64,3,opt,name=hit_rate,json=hitRate,proto3" json:"hit_rate,omitempty"`
	AvgLatencyMs  float64                `protobuf:"fixed64,4,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	P95LatencyMs  float64                `protobuf:"fixed64,5,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	ErrorCount    int64                  `protobuf:"varint,6,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	ErrorRate     float64                `protobuf:"fixed64,7,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Overview) Reset() {
	*x = Overview{}
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Overview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Overview) ProtoMessage() {}

func (x *Overview) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Overview.ProtoReflect.Descriptor instead.
func (*Overview) Descriptor() ([]byte, []int) {
	return file_api_analytics_v1_console_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *Overview) GetTotalQueries() int64 {
	if x != nil {
		return x.TotalQueries
	}
	return 0
}

func (x *Overview) GetHitQueries() int64 {
	if x != nil {
		return x.HitQueries
	}
	return 0
}

func (x *Overview) GetHitRate() float64 {
	if x != nil {
		return x.HitRate
	}
	return 0
}

func (x *Overview) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *Overview) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *Overview) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *Overview) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

type GetOverviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Overview      *Overview              `protobuf:"bytes,1,opt,name=overview,proto3" json:"overview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverviewResponse) Reset() {
	*x = GetOverviewResponse{}
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewResponse) ProtoMessage() {}

func (x *GetOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewResponse.ProtoReflect.Descriptor instead.
func (*GetOverviewResponse) Descriptor() ([]byte, []int) {
	return file_api_analytics_v1_console_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetOverviewResponse) GetOverview() *Overview {
	if x != nil {
		return x.Overview
	}
	return nil
}

type GetLatencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatencyRequest) Reset() {
	*x = GetLatencyRequest{}
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatencyRequest) ProtoMessage() {}

func (x *GetLatencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatencyRequest.ProtoReflect.Descriptor instead.
func (*GetLatencyRequest) Descriptor() ([]byte, []int) {
	return file_api_analytics_v1_console_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetLatencyRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *GetLatencyRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetLatencyRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type LatencyPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	AvgLatencyMs  float64                `protobuf:"fixed64,2,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	P95LatencyMs  float64                `protobuf:"fixed64,3,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	TotalQueries  int64                  `protobuf:"varint,4,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`
	HitQueries    int64                  `protobuf:"varint,5,opt,name=hit_queries,json=hitQueries,proto3" json:"hit_queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyPoint) Reset() {
	*x = LatencyPoint{}
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyPoint) ProtoMessage() {}

func (x *LatencyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyPoint.ProtoReflect.Descriptor instead.
func (*LatencyPoint) Descriptor() ([]byte, []int) {
	return file_api_analytics_v1_console_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *LatencyPoint) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *LatencyPoint) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *LatencyPoint) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *LatencyPoint) GetTotalQueries() int64 {
	if x != nil {
		return x.TotalQueries
	}
	return 0
}

func (x *LatencyPoint) GetHitQueries() int64 {
	if x != nil {
		return x.HitQueries
	}
	return 0
}

type GetLatencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*LatencyPoint        `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatencyResponse) Reset() {
	*x = GetLatencyResponse{}
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatencyResponse) ProtoMessage() {}

func (x *GetLatencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatencyResponse.ProtoReflect.Descriptor instead.
func (*GetLatencyResponse) Descriptor() ([]byte, []int) {
	return file_api_analytics_v1_console_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetLatencyResponse) GetPoints() []*LatencyPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type GetTopQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopQuestionsRequest) Reset() {
	*x = GetTopQuestionsRequest{}
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopQuestionsRequest) ProtoMessage() {}

func (x *GetTopQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopQuestionsRequest.ProtoReflect.Descriptor instead.
func (*GetTopQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_api_analytics_v1_console_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetTopQuestionsRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *GetTopQuestionsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetTopQuestionsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetTopQuestionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QuestionStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	HitRate       float64                `protobuf:"fixed64,3,opt,name=hit_rate,json=hitRate,proto3" json:"hit_rate,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionStat) Reset() {
	*x = QuestionStat{}
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionStat) ProtoMessage() {}

func (x *QuestionStat) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionStat.ProtoReflect.Descriptor instead.
func (*QuestionStat) Descriptor() ([]byte, []int) {
	return file_api_analytics_v1_console_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *QuestionStat) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QuestionStat) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *QuestionStat) GetHitRate() float64 {
	if x != nil {
		return x.HitRate
	}
	return 0
}

func (x *QuestionStat) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type GetTopQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*QuestionStat        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopQuestionsResponse) Reset() {
	*x = GetTopQuestionsResponse{}
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopQuestionsResponse) ProtoMessage() {}

func (x *GetTopQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopQuestionsResponse.ProtoReflect.Descriptor instead.
func (*GetTopQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_api_analytics_v1_console_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *GetTopQuestionsResponse) GetItems() []*QuestionStat {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetKBGapsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKBGapsRequest) Reset() {
	*x = GetKBGapsRequest{}
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKBGapsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKBGapsRequest) ProtoMessage() {}

func (x *GetKBGapsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKBGapsRequest.ProtoReflect.Descriptor instead.
func (*GetKBGapsRequest) Descriptor() ([]byte, []int) {
	return file_api_analytics_v1_console_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *GetKBGapsRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *GetKBGapsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetKBGapsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetKBGapsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GapStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	MissCount     int64                  `protobuf:"varint,2,opt,name=miss_count,json=missCount,proto3" json:"miss_count,omitempty"`
	AvgConfidence float64                `protobuf:"fixed64,3,opt,name=avg_confidence,json=avgConfidence,proto3" json:"avg_confidence,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GapStat) Reset() {
	*x = GapStat{}
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GapStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GapStat) ProtoMessage() {}

func (x *GapStat) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GapStat.ProtoReflect.Descriptor instead.
func (*GapStat) Descriptor() ([]byte, []int) {
	return file_api_analytics_v1_console_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *GapStat) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GapStat) GetMissCount() int64 {
	if x != nil {
		return x.MissCount
	}
	return 0
}

func (x *GapStat) GetAvgConfidence() float64 {
	if x != nil {
		return x.AvgConfidence
	}
	return 0
}

func (x *GapStat) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type GetKBGapsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GapStat             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKBGapsResponse) Reset() {
	*x = GetKBGapsResponse{}
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKBGapsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKBGapsResponse) ProtoMessage() {}

func (x *GetKBGapsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_analytics_v1_console_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKBGapsResponse.ProtoReflect.Descriptor instead.
func (*GetKBGapsResponse) Descriptor() ([]byte, []int) {
	return file_api_analytics_v1_console_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *GetKBGapsResponse) GetItems() []*GapStat {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_analytics_v1_console_analytics_proto protoreflect.FileDescriptor

const file_api_analytics_v1_console_analytics_proto_rawDesc = "" +
	"\n" +
	"(api/analytics/v1/console_analytics.proto\x12\x10api.analytics.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x01\n" +
	"\x12GetOverviewRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xf7\x01\n" +
	"\bOverview\x12#\n" +
	"\rtotal_queries\x18\x01 \x01(\x03R\ftotalQueries\x12\x1f\n" +
	"\vhit_queries\x18\x02 \x01(\x03R\n" +
	"hitQueries\x12\x19\n" +
	"\bhit_rate\x18\x03 \x01(\x01R\ahitRate\x12$\n" +
	"\x0eavg_latency_ms\x18\x04 \x01(\x01R\favgLatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\x05 \x01(\x01R\fp95LatencyMs\x12\x1f\n" +
	"\verror_count\x18\x06 \x01(\x03R\n" +
	"errorCount\x12\x1d\n" +
	"\n" +
	"error_rate\x18\a \x01(\x01R\terrorRate\"M\n" +
	"\x13GetOverviewResponse\x126\n" +
	"\boverview\x18\x01 \x01(\v2\x1a.api.analytics.v1.OverviewR\boverview\"\x9c\x01\n" +
	"\x11GetLatencyRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xd0\x01\n" +
	"\fLatencyPoint\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12$\n" +
	"\x0eavg_latency_ms\x18\x02 \x01(\x01R\favgLatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\x03 \x01(\x01R\fp95LatencyMs\x12#\n" +
	"\rtotal_queries\x18\x04 \x01(\x03R\ftotalQueries\x12\x1f\n" +
	"\vhit_queries\x18\x05 \x01(\x03R\n" +
	"hitQueries\"L\n" +
	"\x12GetLatencyResponse\x126\n" +
	"\x06points\x18\x01 \x03(\v2\x1e.api.analytics.v1.LatencyPointR\x06points\"\xb7\x01\n" +
	"\x16GetTopQuestionsRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x93\x01\n" +
	"\fQuestionStat\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x19\n" +
	"\bhit_rate\x18\x03 \x01(\x01R\ahitRate\x12<\n" +
	"\flast_seen_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\"O\n" +
	"\x17GetTopQuestionsResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.api.analytics.v1.QuestionStatR\x05items\"\xb1\x01\n" +
	"\x10GetKBGapsRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xa3\x01\n" +
	"\aGapStat\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"miss_count\x18\x02 \x01(\x03R\tmissCount\x12%\n" +
	"\x0eavg_confidence\x18\x03 \x01(\x01R\ravgConfidence\x12<\n" +
	"\flast_seen_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\"D\n" +
	"\x11GetKBGapsResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.api.analytics.v1.GapStatR\x05items2\xaa\x04\n" +
	"\x10ConsoleAnalytics\x12\x82\x01\n" +
	"\vGetOverview\x12$.api.analytics.v1.GetOverviewRequest\x1a%.api.analytics.v1.GetOverviewResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/console/v1/analytics/overview\x12~\n" +
	"\n" +
	"GetLatency\x12#.api.analytics.v1.GetLatencyRequest\x1a$.api.analytics.v1.GetLatencyResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/console/v1/analytics/latency\x12\x93\x01\n" +
	"\x0fGetTopQuestions\x12(.api.analytics.v1.GetTopQuestionsRequest\x1a).api.analytics.v1.GetTopQuestionsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/console/v1/analytics/top_questions\x12{\n" +
	"\tGetKBGaps\x12\".api.analytics.v1.GetKBGapsRequest\x1a#.api.analytics.v1.GetKBGapsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/console/v1/analytics/kb_gapsB:Z8github.com/ZTH7/RagoDesk/apps/server/api/analytics/v1;v1b\x06proto3"

var (
	file_api_analytics_v1_console_analytics_proto_rawDescOnce sync.Once
	file_api_analytics_v1_console_analytics_proto_rawDescData []byte
)

func file_api_analytics_v1_console_analytics_proto_rawDescGZIP() []byte {
	file_api_analytics_v1_console_analytics_proto_rawDescOnce.Do(func() {
		file_api_analytics_v1_console_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_analytics_v1_console_analytics_proto_rawDesc), len(file_api_analytics_v1_console_analytics_proto_rawDesc)))
	})
	return file_api_analytics_v1_console_analytics_proto_rawDescData
}

var file_api_analytics_v1_console_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_analytics_v1_console_analytics_proto_goTypes = []any{
	(*GetOverviewRequest)(nil),      // 0: api.analytics.v1.GetOverviewRequest
	(*Overview)(nil),                // 1: api.analytics.v1.Overview
	(*GetOverviewResponse)(nil),     // 2: api.analytics.v1.GetOverviewResponse
	(*GetLatencyRequest)(nil),       // 3: api.analytics.v1.GetLatencyRequest
	(*LatencyPoint)(nil),            // 4: api.analytics.v1.LatencyPoint
	(*GetLatencyResponse)(nil),      // 5: api.analytics.v1.GetLatencyResponse
	(*GetTopQuestionsRequest)(nil),  // 6: api.analytics.v1.GetTopQuestionsRequest
	(*QuestionStat)(nil),            // 7: api.analytics.v1.QuestionStat
	(*GetTopQuestionsResponse)(nil), // 8: api.analytics.v1.GetTopQuestionsResponse
	(*GetKBGapsRequest)(nil),        // 9: api.analytics.v1.GetKBGapsRequest
	(*GapStat)(nil),                 // 10: api.analytics.v1.GapStat
	(*GetKBGapsResponse)(nil),       // 11: api.analytics.v1.GetKBGapsResponse
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
}
var file_api_analytics_v1_console_analytics_proto_depIdxs = []int32{
	12, // 0: api.analytics.v1.GetOverviewRequest.start_time:type_name -> google.protobuf.Timestamp
	12, // 1: api.analytics.v1.GetOverviewRequest.end_time:type_name -> google.protobuf.Timestamp
	1,  // 2: api.analytics.v1.GetOverviewResponse.overview:type_name -> api.analytics.v1.Overview
	12, // 3: api.analytics.v1.GetLatencyRequest.start_time:type_name -> google.protobuf.Timestamp
	12, // 4: api.analytics.v1.GetLatencyRequest.end_time:type_name -> google.protobuf.Timestamp
	12, // 5: api.analytics.v1.LatencyPoint.date:type_name -> google.protobuf.Timestamp
	4,  // 6: api.analytics.v1.GetLatencyResponse.points:type_name -> api.analytics.v1.LatencyPoint
	12, // 7: api.analytics.v1.GetTopQuestionsRequest.start_time:type_name -> google.protobuf.Timestamp
	12, // 8: api.analytics.v1.GetTopQuestionsRequest.end_time:type_name -> google.protobuf.Timestamp
	12, // 9: api.analytics.v1.QuestionStat.last_seen_at:type_name -> google.protobuf.Timestamp
	7,  // 10: api.analytics.v1.GetTopQuestionsResponse.items:type_name -> api.analytics.v1.QuestionStat
	12, // 11: api.analytics.v1.GetKBGapsRequest.start_time:type_name -> google.protobuf.Timestamp
	12, // 12: api.analytics.v1.GetKBGapsRequest.end_time:type_name -> google.protobuf.Timestamp
	12, // 13: api.analytics.v1.GapStat.last_seen_at:type_name -> google.protobuf.Timestamp
	10, // 14: api.analytics.v1.GetKBGapsResponse.items:type_name -> api.analytics.v1.GapStat
	0,  // 15: api.analytics.v1.ConsoleAnalytics.GetOverview:input_type -> api.analytics.v1.GetOverviewRequest
	3,  // 16: api.analytics.v1.ConsoleAnalytics.GetLatency:input_type -> api.analytics.v1.GetLatencyRequest
	6,  // 17: api.analytics.v1.ConsoleAnalytics.GetTopQuestions:input_type -> api.analytics.v1.GetTopQuestionsRequest
	9,  // 18: api.analytics.v1.ConsoleAnalytics.GetKBGaps:input_type -> api.analytics.v1.GetKBGapsRequest
	2,  // 19: api.analytics.v1.ConsoleAnalytics.GetOverview:output_type -> api.analytics.v1.GetOverviewResponse
	5,  // 20: api.analytics.v1.ConsoleAnalytics.GetLatency:output_type -> api.analytics.v1.GetLatencyResponse
	8,  // 21: api.analytics.v1.ConsoleAnalytics.GetTopQuestions:output_type -> api.analytics.v1.GetTopQuestionsResponse
	11, // 22: api.analytics.v1.ConsoleAnalytics.GetKBGaps:output_type -> api.analytics.v1.GetKBGapsResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_analytics_v1_console_analytics_proto_init() }
func file_api_analytics_v1_console_analytics_proto_init() {
	if File_api_analytics_v1_console_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_analytics_v1_console_analytics_proto_rawDesc), len(file_api_analytics_v1_console_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_analytics_v1_console_analytics_proto_goTypes,
		DependencyIndexes: file_api_analytics_v1_console_analytics_proto_depIdxs,
		MessageInfos:      file_api_analytics_v1_console_analytics_proto_msgTypes,
	}.Build()
	File_api_analytics_v1_console_analytics_proto = out.File
	file_api_analytics_v1_console_analytics_proto_goTypes = nil
	file_api_analytics_v1_console_analytics_proto_depIdxs = nil
}
