// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/rag/v1/rag.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reference struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DocumentId        string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentVersionId string                 `protobuf:"bytes,2,opt,name=document_version_id,json=documentVersionId,proto3" json:"document_version_id,omitempty"`
	ChunkId           string                 `protobuf:"bytes,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Score             float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	Rank              int32                  `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	Snippet           string                 `protobuf:"bytes,6,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_api_rag_v1_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_v1_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_api_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

func (x *Reference) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Reference) GetDocumentVersionId() string {
	if x != nil {
		return x.DocumentVersionId
	}
	return ""
}

func (x *Reference) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Reference) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Reference) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Reference) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	TopK          int32                  `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Threshold     float32                `protobuf:"fixed32,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_api_rag_v1_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_v1_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_v1_rag_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMessageRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SendMessageRequest) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	References    []*Reference           `protobuf:"bytes,3,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_api_rag_v1_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_v1_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *SendMessageResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SendMessageResponse) GetReferences() []*Reference {
	if x != nil {
		return x.References
	}
	return nil
}

var File_api_rag_v1_rag_proto protoreflect.FileDescriptor

const file_api_rag_v1_rag_proto_rawDesc = "" +
	"\n" +
	"\x14api/rag/v1/rag.proto\x12\n" +
	"api.rag.v1\x1a\x1cgoogle/api/annotations.proto\"\xbb\x01\n" +
	"\tReference\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12.\n" +
	"\x13document_version_id\x18\x02 \x01(\tR\x11documentVersionId\x12\x19\n" +
	"\bchunk_id\x18\x03 \x01(\tR\achunkId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x05R\x04rank\x12\x18\n" +
	"\asnippet\x18\x06 \x01(\tR\asnippet\"\x86\x01\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topK\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x02R\tthresholdJ\x04\b\x02\x10\x03\"\x82\x01\n" +
	"\x13SendMessageResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x125\n" +
	"\n" +
	"references\x18\x03 \x03(\v2\x15.api.rag.v1.ReferenceR\n" +
	"references2q\n" +
	"\x03RAG\x12j\n" +
	"\vSendMessage\x12\x1e.api.rag.v1.SendMessageRequest\x1a\x1f.api.rag.v1.SendMessageResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/messageB4Z2github.com/ZTH7/RagoDesk/apps/server/api/rag/v1;v1b\x06proto3"

var (
	file_api_rag_v1_rag_proto_rawDescOnce sync.Once
	file_api_rag_v1_rag_proto_rawDescData []byte
)

func file_api_rag_v1_rag_proto_rawDescGZIP() []byte {
	file_api_rag_v1_rag_proto_rawDescOnce.Do(func() {
		file_api_rag_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_rag_v1_rag_proto_rawDesc), len(file_api_rag_v1_rag_proto_rawDesc)))
	})
	return file_api_rag_v1_rag_proto_rawDescData
}

var file_api_rag_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_rag_v1_rag_proto_goTypes = []any{
	(*Reference)(nil),           // 0: api.rag.v1.Reference
	(*SendMessageRequest)(nil),  // 1: api.rag.v1.SendMessageRequest
	(*SendMessageResponse)(nil), // 2: api.rag.v1.SendMessageResponse
}
var file_api_rag_v1_rag_proto_depIdxs = []int32{
	0, // 0: api.rag.v1.SendMessageResponse.references:type_name -> api.rag.v1.Reference
	1, // 1: api.rag.v1.RAG.SendMessage:input_type -> api.rag.v1.SendMessageRequest
	2, // 2: api.rag.v1.RAG.SendMessage:output_type -> api.rag.v1.SendMessageResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_rag_v1_rag_proto_init() }
func file_api_rag_v1_rag_proto_init() {
	if File_api_rag_v1_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rag_v1_rag_proto_rawDesc), len(file_api_rag_v1_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rag_v1_rag_proto_goTypes,
		DependencyIndexes: file_api_rag_v1_rag_proto_depIdxs,
		MessageInfos:      file_api_rag_v1_rag_proto_msgTypes,
	}.Build()
	File_api_rag_v1_rag_proto = out.File
	file_api_rag_v1_rag_proto_goTypes = nil
	file_api_rag_v1_rag_proto_depIdxs = nil
}
