// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/rag/v1/rag.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRAGSendMessage = "/api.rag.v1.RAG/SendMessage"

type RAGHTTPServer interface {
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
}

func RegisterRAGHTTPServer(s *http.Server, srv RAGHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/message", _RAG_SendMessage0_HTTP_Handler(srv))
}

func _RAG_SendMessage0_HTTP_Handler(srv RAGHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRAGSendMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendMessage(ctx, req.(*SendMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendMessageResponse)
		return ctx.Result(200, reply)
	}
}

type RAGHTTPClient interface {
	SendMessage(ctx context.Context, req *SendMessageRequest, opts ...http.CallOption) (rsp *SendMessageResponse, err error)
}

type RAGHTTPClientImpl struct {
	cc *http.Client
}

func NewRAGHTTPClient(client *http.Client) RAGHTTPClient {
	return &RAGHTTPClientImpl{client}
}

func (c *RAGHTTPClientImpl) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...http.CallOption) (*SendMessageResponse, error) {
	var out SendMessageResponse
	pattern := "/api/v1/message"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRAGSendMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
