// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ZTH7/RAGDesk/apps/server/internal/conf"
	biz5 "github.com/ZTH7/RAGDesk/apps/server/internal/apimgmt/biz"
	data6 "github.com/ZTH7/RAGDesk/apps/server/internal/apimgmt/data"
	biz4 "github.com/ZTH7/RAGDesk/apps/server/internal/conversation/biz"
	data2 "github.com/ZTH7/RAGDesk/apps/server/internal/conversation/data"
	service4 "github.com/ZTH7/RAGDesk/apps/server/internal/conversation/service"
	"github.com/ZTH7/RAGDesk/apps/server/internal/data"
	"github.com/ZTH7/RAGDesk/apps/server/internal/iam/biz"
	data3 "github.com/ZTH7/RAGDesk/apps/server/internal/iam/data"
	"github.com/ZTH7/RAGDesk/apps/server/internal/iam/service"
	biz2 "github.com/ZTH7/RAGDesk/apps/server/internal/knowledge/biz"
	data4 "github.com/ZTH7/RAGDesk/apps/server/internal/knowledge/data"
	service2 "github.com/ZTH7/RAGDesk/apps/server/internal/knowledge/service"
	biz3 "github.com/ZTH7/RAGDesk/apps/server/internal/rag/biz"
	data5 "github.com/ZTH7/RAGDesk/apps/server/internal/rag/data"
	service3 "github.com/ZTH7/RAGDesk/apps/server/internal/rag/service"
	"github.com/ZTH7/RAGDesk/apps/server/internal/server"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	apimgmtRepo := data6.NewAPIMgmtRepo(dataData, logger)
	apimgmtUsecase := biz5.NewAPIMgmtUsecase(apimgmtRepo, logger)
	conversationRepo := data2.NewConversationRepo(dataData)
	conversationUsecase := biz4.NewConversationUsecase(conversationRepo, confData)
	conversationService := service4.NewConversationService(conversationUsecase, apimgmtUsecase)
	iamRepo := data3.NewIAMRepo(dataData, logger)
	iamUsecase := biz.NewIAMUsecase(iamRepo, logger)
	iamService := service.NewIAMService(iamUsecase, logger)
	knowledgeRepo := data4.NewKnowledgeRepo(dataData, confData, logger)
	ingestionQueue := data4.NewIngestionQueue(confData, logger)
	knowledgeUsecase := biz2.NewKnowledgeUsecase(knowledgeRepo, ingestionQueue, confData, logger)
	knowledgeService := service2.NewKnowledgeService(knowledgeUsecase, iamUsecase, logger)
	ragKBRepo := data5.NewKBRepo(dataData)
	ragVectorRepo := data5.NewVectorRepo(confData)
	ragChunkRepo := data5.NewChunkRepo(dataData)
	ragUsecase, err := biz3.NewRAGUsecase(ragKBRepo, ragVectorRepo, ragChunkRepo, confData, logger)
	if err != nil {
		return nil, nil, err
	}
	ragService := service3.NewRAGService(ragUsecase, conversationUsecase, apimgmtUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, iamService, knowledgeService, ragService, conversationService)
	httpServer := server.NewHTTPServer(confServer, logger, iamService, knowledgeService, ragService, conversationService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
