// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/apimgmt/v1/console_apimgmt.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsoleAPIMgmt_CreateAPIKey_FullMethodName           = "/api.apimgmt.v1.ConsoleAPIMgmt/CreateAPIKey"
	ConsoleAPIMgmt_ListAPIKeys_FullMethodName            = "/api.apimgmt.v1.ConsoleAPIMgmt/ListAPIKeys"
	ConsoleAPIMgmt_GetAPIKey_FullMethodName              = "/api.apimgmt.v1.ConsoleAPIMgmt/GetAPIKey"
	ConsoleAPIMgmt_UpdateAPIKey_FullMethodName           = "/api.apimgmt.v1.ConsoleAPIMgmt/UpdateAPIKey"
	ConsoleAPIMgmt_DeleteAPIKey_FullMethodName           = "/api.apimgmt.v1.ConsoleAPIMgmt/DeleteAPIKey"
	ConsoleAPIMgmt_RotateAPIKey_FullMethodName           = "/api.apimgmt.v1.ConsoleAPIMgmt/RotateAPIKey"
	ConsoleAPIMgmt_RegeneratePublicChatID_FullMethodName = "/api.apimgmt.v1.ConsoleAPIMgmt/RegeneratePublicChatID"
	ConsoleAPIMgmt_ListUsageLogs_FullMethodName          = "/api.apimgmt.v1.ConsoleAPIMgmt/ListUsageLogs"
	ConsoleAPIMgmt_GetUsageSummary_FullMethodName        = "/api.apimgmt.v1.ConsoleAPIMgmt/GetUsageSummary"
	ConsoleAPIMgmt_ExportUsageLogs_FullMethodName        = "/api.apimgmt.v1.ConsoleAPIMgmt/ExportUsageLogs"
)

// ConsoleAPIMgmtClient is the client API for ConsoleAPIMgmt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsoleAPIMgmtClient interface {
	CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error)
	ListAPIKeys(ctx context.Context, in *ListAPIKeysRequest, opts ...grpc.CallOption) (*ListAPIKeysResponse, error)
	GetAPIKey(ctx context.Context, in *GetAPIKeyRequest, opts ...grpc.CallOption) (*GetAPIKeyResponse, error)
	UpdateAPIKey(ctx context.Context, in *UpdateAPIKeyRequest, opts ...grpc.CallOption) (*UpdateAPIKeyResponse, error)
	DeleteAPIKey(ctx context.Context, in *DeleteAPIKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RotateAPIKey(ctx context.Context, in *RotateAPIKeyRequest, opts ...grpc.CallOption) (*RotateAPIKeyResponse, error)
	RegeneratePublicChatID(ctx context.Context, in *RegeneratePublicChatIDRequest, opts ...grpc.CallOption) (*RegeneratePublicChatIDResponse, error)
	ListUsageLogs(ctx context.Context, in *ListUsageLogsRequest, opts ...grpc.CallOption) (*ListUsageLogsResponse, error)
	GetUsageSummary(ctx context.Context, in *GetUsageSummaryRequest, opts ...grpc.CallOption) (*GetUsageSummaryResponse, error)
	ExportUsageLogs(ctx context.Context, in *ExportUsageLogsRequest, opts ...grpc.CallOption) (*ExportUsageLogsResponse, error)
}

type consoleAPIMgmtClient struct {
	cc grpc.ClientConnInterface
}

func NewConsoleAPIMgmtClient(cc grpc.ClientConnInterface) ConsoleAPIMgmtClient {
	return &consoleAPIMgmtClient{cc}
}

func (c *consoleAPIMgmtClient) CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAPIKeyResponse)
	err := c.cc.Invoke(ctx, ConsoleAPIMgmt_CreateAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleAPIMgmtClient) ListAPIKeys(ctx context.Context, in *ListAPIKeysRequest, opts ...grpc.CallOption) (*ListAPIKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAPIKeysResponse)
	err := c.cc.Invoke(ctx, ConsoleAPIMgmt_ListAPIKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleAPIMgmtClient) GetAPIKey(ctx context.Context, in *GetAPIKeyRequest, opts ...grpc.CallOption) (*GetAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAPIKeyResponse)
	err := c.cc.Invoke(ctx, ConsoleAPIMgmt_GetAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleAPIMgmtClient) UpdateAPIKey(ctx context.Context, in *UpdateAPIKeyRequest, opts ...grpc.CallOption) (*UpdateAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAPIKeyResponse)
	err := c.cc.Invoke(ctx, ConsoleAPIMgmt_UpdateAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleAPIMgmtClient) DeleteAPIKey(ctx context.Context, in *DeleteAPIKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConsoleAPIMgmt_DeleteAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleAPIMgmtClient) RotateAPIKey(ctx context.Context, in *RotateAPIKeyRequest, opts ...grpc.CallOption) (*RotateAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateAPIKeyResponse)
	err := c.cc.Invoke(ctx, ConsoleAPIMgmt_RotateAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleAPIMgmtClient) RegeneratePublicChatID(ctx context.Context, in *RegeneratePublicChatIDRequest, opts ...grpc.CallOption) (*RegeneratePublicChatIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegeneratePublicChatIDResponse)
	err := c.cc.Invoke(ctx, ConsoleAPIMgmt_RegeneratePublicChatID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleAPIMgmtClient) ListUsageLogs(ctx context.Context, in *ListUsageLogsRequest, opts ...grpc.CallOption) (*ListUsageLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsageLogsResponse)
	err := c.cc.Invoke(ctx, ConsoleAPIMgmt_ListUsageLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleAPIMgmtClient) GetUsageSummary(ctx context.Context, in *GetUsageSummaryRequest, opts ...grpc.CallOption) (*GetUsageSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsageSummaryResponse)
	err := c.cc.Invoke(ctx, ConsoleAPIMgmt_GetUsageSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleAPIMgmtClient) ExportUsageLogs(ctx context.Context, in *ExportUsageLogsRequest, opts ...grpc.CallOption) (*ExportUsageLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportUsageLogsResponse)
	err := c.cc.Invoke(ctx, ConsoleAPIMgmt_ExportUsageLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsoleAPIMgmtServer is the server API for ConsoleAPIMgmt service.
// All implementations must embed UnimplementedConsoleAPIMgmtServer
// for forward compatibility.
type ConsoleAPIMgmtServer interface {
	CreateAPIKey(context.Context, *CreateAPIKeyRequest) (*CreateAPIKeyResponse, error)
	ListAPIKeys(context.Context, *ListAPIKeysRequest) (*ListAPIKeysResponse, error)
	GetAPIKey(context.Context, *GetAPIKeyRequest) (*GetAPIKeyResponse, error)
	UpdateAPIKey(context.Context, *UpdateAPIKeyRequest) (*UpdateAPIKeyResponse, error)
	DeleteAPIKey(context.Context, *DeleteAPIKeyRequest) (*emptypb.Empty, error)
	RotateAPIKey(context.Context, *RotateAPIKeyRequest) (*RotateAPIKeyResponse, error)
	RegeneratePublicChatID(context.Context, *RegeneratePublicChatIDRequest) (*RegeneratePublicChatIDResponse, error)
	ListUsageLogs(context.Context, *ListUsageLogsRequest) (*ListUsageLogsResponse, error)
	GetUsageSummary(context.Context, *GetUsageSummaryRequest) (*GetUsageSummaryResponse, error)
	ExportUsageLogs(context.Context, *ExportUsageLogsRequest) (*ExportUsageLogsResponse, error)
	mustEmbedUnimplementedConsoleAPIMgmtServer()
}

// UnimplementedConsoleAPIMgmtServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsoleAPIMgmtServer struct{}

func (UnimplementedConsoleAPIMgmtServer) CreateAPIKey(context.Context, *CreateAPIKeyRequest) (*CreateAPIKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAPIKey not implemented")
}
func (UnimplementedConsoleAPIMgmtServer) ListAPIKeys(context.Context, *ListAPIKeysRequest) (*ListAPIKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAPIKeys not implemented")
}
func (UnimplementedConsoleAPIMgmtServer) GetAPIKey(context.Context, *GetAPIKeyRequest) (*GetAPIKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAPIKey not implemented")
}
func (UnimplementedConsoleAPIMgmtServer) UpdateAPIKey(context.Context, *UpdateAPIKeyRequest) (*UpdateAPIKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAPIKey not implemented")
}
func (UnimplementedConsoleAPIMgmtServer) DeleteAPIKey(context.Context, *DeleteAPIKeyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAPIKey not implemented")
}
func (UnimplementedConsoleAPIMgmtServer) RotateAPIKey(context.Context, *RotateAPIKeyRequest) (*RotateAPIKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateAPIKey not implemented")
}
func (UnimplementedConsoleAPIMgmtServer) RegeneratePublicChatID(context.Context, *RegeneratePublicChatIDRequest) (*RegeneratePublicChatIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegeneratePublicChatID not implemented")
}
func (UnimplementedConsoleAPIMgmtServer) ListUsageLogs(context.Context, *ListUsageLogsRequest) (*ListUsageLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsageLogs not implemented")
}
func (UnimplementedConsoleAPIMgmtServer) GetUsageSummary(context.Context, *GetUsageSummaryRequest) (*GetUsageSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsageSummary not implemented")
}
func (UnimplementedConsoleAPIMgmtServer) ExportUsageLogs(context.Context, *ExportUsageLogsRequest) (*ExportUsageLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportUsageLogs not implemented")
}
func (UnimplementedConsoleAPIMgmtServer) mustEmbedUnimplementedConsoleAPIMgmtServer() {}
func (UnimplementedConsoleAPIMgmtServer) testEmbeddedByValue()                        {}

// UnsafeConsoleAPIMgmtServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsoleAPIMgmtServer will
// result in compilation errors.
type UnsafeConsoleAPIMgmtServer interface {
	mustEmbedUnimplementedConsoleAPIMgmtServer()
}

func RegisterConsoleAPIMgmtServer(s grpc.ServiceRegistrar, srv ConsoleAPIMgmtServer) {
	// If the following call panics, it indicates UnimplementedConsoleAPIMgmtServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsoleAPIMgmt_ServiceDesc, srv)
}

func _ConsoleAPIMgmt_CreateAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleAPIMgmtServer).CreateAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleAPIMgmt_CreateAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleAPIMgmtServer).CreateAPIKey(ctx, req.(*CreateAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleAPIMgmt_ListAPIKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAPIKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleAPIMgmtServer).ListAPIKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleAPIMgmt_ListAPIKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleAPIMgmtServer).ListAPIKeys(ctx, req.(*ListAPIKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleAPIMgmt_GetAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleAPIMgmtServer).GetAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleAPIMgmt_GetAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleAPIMgmtServer).GetAPIKey(ctx, req.(*GetAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleAPIMgmt_UpdateAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleAPIMgmtServer).UpdateAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleAPIMgmt_UpdateAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleAPIMgmtServer).UpdateAPIKey(ctx, req.(*UpdateAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleAPIMgmt_DeleteAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleAPIMgmtServer).DeleteAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleAPIMgmt_DeleteAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleAPIMgmtServer).DeleteAPIKey(ctx, req.(*DeleteAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleAPIMgmt_RotateAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleAPIMgmtServer).RotateAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleAPIMgmt_RotateAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleAPIMgmtServer).RotateAPIKey(ctx, req.(*RotateAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleAPIMgmt_RegeneratePublicChatID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegeneratePublicChatIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleAPIMgmtServer).RegeneratePublicChatID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleAPIMgmt_RegeneratePublicChatID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleAPIMgmtServer).RegeneratePublicChatID(ctx, req.(*RegeneratePublicChatIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleAPIMgmt_ListUsageLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsageLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleAPIMgmtServer).ListUsageLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleAPIMgmt_ListUsageLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleAPIMgmtServer).ListUsageLogs(ctx, req.(*ListUsageLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleAPIMgmt_GetUsageSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsageSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleAPIMgmtServer).GetUsageSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleAPIMgmt_GetUsageSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleAPIMgmtServer).GetUsageSummary(ctx, req.(*GetUsageSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleAPIMgmt_ExportUsageLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportUsageLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleAPIMgmtServer).ExportUsageLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleAPIMgmt_ExportUsageLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleAPIMgmtServer).ExportUsageLogs(ctx, req.(*ExportUsageLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsoleAPIMgmt_ServiceDesc is the grpc.ServiceDesc for ConsoleAPIMgmt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsoleAPIMgmt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.apimgmt.v1.ConsoleAPIMgmt",
	HandlerType: (*ConsoleAPIMgmtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAPIKey",
			Handler:    _ConsoleAPIMgmt_CreateAPIKey_Handler,
		},
		{
			MethodName: "ListAPIKeys",
			Handler:    _ConsoleAPIMgmt_ListAPIKeys_Handler,
		},
		{
			MethodName: "GetAPIKey",
			Handler:    _ConsoleAPIMgmt_GetAPIKey_Handler,
		},
		{
			MethodName: "UpdateAPIKey",
			Handler:    _ConsoleAPIMgmt_UpdateAPIKey_Handler,
		},
		{
			MethodName: "DeleteAPIKey",
			Handler:    _ConsoleAPIMgmt_DeleteAPIKey_Handler,
		},
		{
			MethodName: "RotateAPIKey",
			Handler:    _ConsoleAPIMgmt_RotateAPIKey_Handler,
		},
		{
			MethodName: "RegeneratePublicChatID",
			Handler:    _ConsoleAPIMgmt_RegeneratePublicChatID_Handler,
		},
		{
			MethodName: "ListUsageLogs",
			Handler:    _ConsoleAPIMgmt_ListUsageLogs_Handler,
		},
		{
			MethodName: "GetUsageSummary",
			Handler:    _ConsoleAPIMgmt_GetUsageSummary_Handler,
		},
		{
			MethodName: "ExportUsageLogs",
			Handler:    _ConsoleAPIMgmt_ExportUsageLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/apimgmt/v1/console_apimgmt.proto",
}
