// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/apimgmt/v1/console_apimgmt.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIKey struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId          string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BotId             string                 `protobuf:"bytes,3,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Name              string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Scopes            []string               `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	ApiVersions       []string               `protobuf:"bytes,7,rep,name=api_versions,json=apiVersions,proto3" json:"api_versions,omitempty"`
	QuotaDaily        int32                  `protobuf:"varint,8,opt,name=quota_daily,json=quotaDaily,proto3" json:"quota_daily,omitempty"`
	QpsLimit          int32                  `protobuf:"varint,9,opt,name=qps_limit,json=qpsLimit,proto3" json:"qps_limit,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	PublicChatId      string                 `protobuf:"bytes,12,opt,name=public_chat_id,json=publicChatId,proto3" json:"public_chat_id,omitempty"`
	PublicChatEnabled bool                   `protobuf:"varint,13,opt,name=public_chat_enabled,json=publicChatEnabled,proto3" json:"public_chat_enabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *APIKey) Reset() {
	*x = APIKey{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKey) ProtoMessage() {}

func (x *APIKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKey.ProtoReflect.Descriptor instead.
func (*APIKey) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{0}
}

func (x *APIKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIKey) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *APIKey) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *APIKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKey) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *APIKey) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *APIKey) GetApiVersions() []string {
	if x != nil {
		return x.ApiVersions
	}
	return nil
}

func (x *APIKey) GetQuotaDaily() int32 {
	if x != nil {
		return x.QuotaDaily
	}
	return 0
}

func (x *APIKey) GetQpsLimit() int32 {
	if x != nil {
		return x.QpsLimit
	}
	return 0
}

func (x *APIKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *APIKey) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *APIKey) GetPublicChatId() string {
	if x != nil {
		return x.PublicChatId
	}
	return ""
}

func (x *APIKey) GetPublicChatEnabled() bool {
	if x != nil {
		return x.PublicChatEnabled
	}
	return false
}

type UsageLog struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApiKeyId         string                 `protobuf:"bytes,2,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	BotId            string                 `protobuf:"bytes,3,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Path             string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	ApiVersion       string                 `protobuf:"bytes,5,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Model            string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	StatusCode       int32                  `protobuf:"varint,7,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	LatencyMs        int32                  `protobuf:"varint,8,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	PromptTokens     int32                  `protobuf:"varint,9,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,10,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,11,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClientIp         string                 `protobuf:"bytes,13,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent        string                 `protobuf:"bytes,14,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UsageLog) Reset() {
	*x = UsageLog{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageLog) ProtoMessage() {}

func (x *UsageLog) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageLog.ProtoReflect.Descriptor instead.
func (*UsageLog) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{1}
}

func (x *UsageLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UsageLog) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *UsageLog) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *UsageLog) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UsageLog) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *UsageLog) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UsageLog) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UsageLog) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *UsageLog) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *UsageLog) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *UsageLog) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *UsageLog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UsageLog) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *UsageLog) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type UsageSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Total            int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	ErrorCount       int64                  `protobuf:"varint,2,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	AvgLatencyMs     float64                `protobuf:"fixed64,3,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,4,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,5,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int64                  `protobuf:"varint,6,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UsageSummary) Reset() {
	*x = UsageSummary{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageSummary) ProtoMessage() {}

func (x *UsageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageSummary.ProtoReflect.Descriptor instead.
func (*UsageSummary) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{2}
}

func (x *UsageSummary) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UsageSummary) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *UsageSummary) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *UsageSummary) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *UsageSummary) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *UsageSummary) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type CreateAPIKeyRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BotId             string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scopes            []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	ApiVersions       []string               `protobuf:"bytes,4,rep,name=api_versions,json=apiVersions,proto3" json:"api_versions,omitempty"`
	QuotaDaily        int32                  `protobuf:"varint,5,opt,name=quota_daily,json=quotaDaily,proto3" json:"quota_daily,omitempty"`
	QpsLimit          int32                  `protobuf:"varint,6,opt,name=qps_limit,json=qpsLimit,proto3" json:"qps_limit,omitempty"`
	PublicChatEnabled *wrapperspb.BoolValue  `protobuf:"bytes,7,opt,name=public_chat_enabled,json=publicChatEnabled,proto3" json:"public_chat_enabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateAPIKeyRequest) Reset() {
	*x = CreateAPIKeyRequest{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyRequest) ProtoMessage() {}

func (x *CreateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAPIKeyRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *CreateAPIKeyRequest) GetApiVersions() []string {
	if x != nil {
		return x.ApiVersions
	}
	return nil
}

func (x *CreateAPIKeyRequest) GetQuotaDaily() int32 {
	if x != nil {
		return x.QuotaDaily
	}
	return 0
}

func (x *CreateAPIKeyRequest) GetQpsLimit() int32 {
	if x != nil {
		return x.QpsLimit
	}
	return 0
}

func (x *CreateAPIKeyRequest) GetPublicChatEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.PublicChatEnabled
	}
	return nil
}

type CreateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        *APIKey                `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	RawKey        string                 `protobuf:"bytes,2,opt,name=raw_key,json=rawKey,proto3" json:"raw_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyResponse) Reset() {
	*x = CreateAPIKeyResponse{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyResponse) ProtoMessage() {}

func (x *CreateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAPIKeyResponse) GetApiKey() *APIKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

func (x *CreateAPIKeyResponse) GetRawKey() string {
	if x != nil {
		return x.RawKey
	}
	return ""
}

type ListAPIKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysRequest) Reset() {
	*x = ListAPIKeysRequest{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysRequest) ProtoMessage() {}

func (x *ListAPIKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysRequest.ProtoReflect.Descriptor instead.
func (*ListAPIKeysRequest) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{5}
}

func (x *ListAPIKeysRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *ListAPIKeysRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAPIKeysRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListAPIKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*APIKey              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysResponse) Reset() {
	*x = ListAPIKeysResponse{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysResponse) ProtoMessage() {}

func (x *ListAPIKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysResponse.ProtoReflect.Descriptor instead.
func (*ListAPIKeysResponse) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{6}
}

func (x *ListAPIKeysResponse) GetItems() []*APIKey {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAPIKeyRequest) Reset() {
	*x = GetAPIKeyRequest{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPIKeyRequest) ProtoMessage() {}

func (x *GetAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*GetAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{7}
}

func (x *GetAPIKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        *APIKey                `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAPIKeyResponse) Reset() {
	*x = GetAPIKeyResponse{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPIKeyResponse) ProtoMessage() {}

func (x *GetAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*GetAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{8}
}

func (x *GetAPIKeyResponse) GetApiKey() *APIKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

type UpdateAPIKeyRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Scopes            []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	ApiVersions       []string               `protobuf:"bytes,5,rep,name=api_versions,json=apiVersions,proto3" json:"api_versions,omitempty"`
	QuotaDaily        *wrapperspb.Int32Value `protobuf:"bytes,6,opt,name=quota_daily,json=quotaDaily,proto3" json:"quota_daily,omitempty"`
	QpsLimit          *wrapperspb.Int32Value `protobuf:"bytes,7,opt,name=qps_limit,json=qpsLimit,proto3" json:"qps_limit,omitempty"`
	PublicChatEnabled *wrapperspb.BoolValue  `protobuf:"bytes,8,opt,name=public_chat_enabled,json=publicChatEnabled,proto3" json:"public_chat_enabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateAPIKeyRequest) Reset() {
	*x = UpdateAPIKeyRequest{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAPIKeyRequest) ProtoMessage() {}

func (x *UpdateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*UpdateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAPIKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAPIKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAPIKeyRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateAPIKeyRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *UpdateAPIKeyRequest) GetApiVersions() []string {
	if x != nil {
		return x.ApiVersions
	}
	return nil
}

func (x *UpdateAPIKeyRequest) GetQuotaDaily() *wrapperspb.Int32Value {
	if x != nil {
		return x.QuotaDaily
	}
	return nil
}

func (x *UpdateAPIKeyRequest) GetQpsLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.QpsLimit
	}
	return nil
}

func (x *UpdateAPIKeyRequest) GetPublicChatEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.PublicChatEnabled
	}
	return nil
}

type UpdateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        *APIKey                `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAPIKeyResponse) Reset() {
	*x = UpdateAPIKeyResponse{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAPIKeyResponse) ProtoMessage() {}

func (x *UpdateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*UpdateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAPIKeyResponse) GetApiKey() *APIKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

type DeleteAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAPIKeyRequest) Reset() {
	*x = DeleteAPIKeyRequest{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPIKeyRequest) ProtoMessage() {}

func (x *DeleteAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAPIKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RotateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateAPIKeyRequest) Reset() {
	*x = RotateAPIKeyRequest{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateAPIKeyRequest) ProtoMessage() {}

func (x *RotateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{12}
}

func (x *RotateAPIKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RotateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        *APIKey                `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	RawKey        string                 `protobuf:"bytes,2,opt,name=raw_key,json=rawKey,proto3" json:"raw_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateAPIKeyResponse) Reset() {
	*x = RotateAPIKeyResponse{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateAPIKeyResponse) ProtoMessage() {}

func (x *RotateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*RotateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{13}
}

func (x *RotateAPIKeyResponse) GetApiKey() *APIKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

func (x *RotateAPIKeyResponse) GetRawKey() string {
	if x != nil {
		return x.RawKey
	}
	return ""
}

type RegeneratePublicChatIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegeneratePublicChatIDRequest) Reset() {
	*x = RegeneratePublicChatIDRequest{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegeneratePublicChatIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegeneratePublicChatIDRequest) ProtoMessage() {}

func (x *RegeneratePublicChatIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegeneratePublicChatIDRequest.ProtoReflect.Descriptor instead.
func (*RegeneratePublicChatIDRequest) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{14}
}

func (x *RegeneratePublicChatIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RegeneratePublicChatIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        *APIKey                `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegeneratePublicChatIDResponse) Reset() {
	*x = RegeneratePublicChatIDResponse{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegeneratePublicChatIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegeneratePublicChatIDResponse) ProtoMessage() {}

func (x *RegeneratePublicChatIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegeneratePublicChatIDResponse.ProtoReflect.Descriptor instead.
func (*RegeneratePublicChatIDResponse) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{15}
}

func (x *RegeneratePublicChatIDResponse) GetApiKey() *APIKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

type ListUsageLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeyId      string                 `protobuf:"bytes,1,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	BotId         string                 `protobuf:"bytes,2,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,3,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsageLogsRequest) Reset() {
	*x = ListUsageLogsRequest{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsageLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsageLogsRequest) ProtoMessage() {}

func (x *ListUsageLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsageLogsRequest.ProtoReflect.Descriptor instead.
func (*ListUsageLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{16}
}

func (x *ListUsageLogsRequest) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *ListUsageLogsRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *ListUsageLogsRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ListUsageLogsRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ListUsageLogsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListUsageLogsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListUsageLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsageLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListUsageLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UsageLog            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsageLogsResponse) Reset() {
	*x = ListUsageLogsResponse{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsageLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsageLogsResponse) ProtoMessage() {}

func (x *ListUsageLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsageLogsResponse.ProtoReflect.Descriptor instead.
func (*ListUsageLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{17}
}

func (x *ListUsageLogsResponse) GetItems() []*UsageLog {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetUsageSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeyId      string                 `protobuf:"bytes,1,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	BotId         string                 `protobuf:"bytes,2,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,3,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageSummaryRequest) Reset() {
	*x = GetUsageSummaryRequest{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageSummaryRequest) ProtoMessage() {}

func (x *GetUsageSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetUsageSummaryRequest) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{18}
}

func (x *GetUsageSummaryRequest) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *GetUsageSummaryRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *GetUsageSummaryRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetUsageSummaryRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GetUsageSummaryRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetUsageSummaryRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type GetUsageSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *UsageSummary          `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageSummaryResponse) Reset() {
	*x = GetUsageSummaryResponse{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageSummaryResponse) ProtoMessage() {}

func (x *GetUsageSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetUsageSummaryResponse) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{19}
}

func (x *GetUsageSummaryResponse) GetSummary() *UsageSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type ExportUsageLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeyId      string                 `protobuf:"bytes,1,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	BotId         string                 `protobuf:"bytes,2,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,3,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	Format        string                 `protobuf:"bytes,9,opt,name=format,proto3" json:"format,omitempty"` // csv only for MVP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportUsageLogsRequest) Reset() {
	*x = ExportUsageLogsRequest{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportUsageLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportUsageLogsRequest) ProtoMessage() {}

func (x *ExportUsageLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportUsageLogsRequest.ProtoReflect.Descriptor instead.
func (*ExportUsageLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{20}
}

func (x *ExportUsageLogsRequest) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *ExportUsageLogsRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *ExportUsageLogsRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ExportUsageLogsRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ExportUsageLogsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ExportUsageLogsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ExportUsageLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ExportUsageLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ExportUsageLogsRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ExportUsageLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,4,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	ObjectUri     string                 `protobuf:"bytes,5,opt,name=object_uri,json=objectUri,proto3" json:"object_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportUsageLogsResponse) Reset() {
	*x = ExportUsageLogsResponse{}
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportUsageLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportUsageLogsResponse) ProtoMessage() {}

func (x *ExportUsageLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_apimgmt_v1_console_apimgmt_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportUsageLogsResponse.ProtoReflect.Descriptor instead.
func (*ExportUsageLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP(), []int{21}
}

func (x *ExportUsageLogsResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExportUsageLogsResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExportUsageLogsResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ExportUsageLogsResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ExportUsageLogsResponse) GetObjectUri() string {
	if x != nil {
		return x.ObjectUri
	}
	return ""
}

var File_api_apimgmt_v1_console_apimgmt_proto protoreflect.FileDescriptor

const file_api_apimgmt_v1_console_apimgmt_proto_rawDesc = "" +
	"\n" +
	"$api/apimgmt/v1/console_apimgmt.proto\x12\x0eapi.apimgmt.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xc0\x03\n" +
	"\x06APIKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x15\n" +
	"\x06bot_id\x18\x03 \x01(\tR\x05botId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x16\n" +
	"\x06scopes\x18\x06 \x03(\tR\x06scopes\x12!\n" +
	"\fapi_versions\x18\a \x03(\tR\vapiVersions\x12\x1f\n" +
	"\vquota_daily\x18\b \x01(\x05R\n" +
	"quotaDaily\x12\x1b\n" +
	"\tqps_limit\x18\t \x01(\x05R\bqpsLimit\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x12$\n" +
	"\x0epublic_chat_id\x18\f \x01(\tR\fpublicChatId\x12.\n" +
	"\x13public_chat_enabled\x18\r \x01(\bR\x11publicChatEnabled\"\xc6\x03\n" +
	"\bUsageLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x02 \x01(\tR\bapiKeyId\x12\x15\n" +
	"\x06bot_id\x18\x03 \x01(\tR\x05botId\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1f\n" +
	"\vapi_version\x18\x05 \x01(\tR\n" +
	"apiVersion\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12\x1f\n" +
	"\vstatus_code\x18\a \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\b \x01(\x05R\tlatencyMs\x12#\n" +
	"\rprompt_tokens\x18\t \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\n" +
	" \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\v \x01(\x05R\vtotalTokens\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tclient_ip\x18\r \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x0e \x01(\tR\tuserAgent\"\xe0\x01\n" +
	"\fUsageSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1f\n" +
	"\verror_count\x18\x02 \x01(\x03R\n" +
	"errorCount\x12$\n" +
	"\x0eavg_latency_ms\x18\x03 \x01(\x01R\favgLatencyMs\x12#\n" +
	"\rprompt_tokens\x18\x04 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x05 \x01(\x03R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x06 \x01(\x03R\vtotalTokens\"\x85\x02\n" +
	"\x13CreateAPIKeyRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\x12!\n" +
	"\fapi_versions\x18\x04 \x03(\tR\vapiVersions\x12\x1f\n" +
	"\vquota_daily\x18\x05 \x01(\x05R\n" +
	"quotaDaily\x12\x1b\n" +
	"\tqps_limit\x18\x06 \x01(\x05R\bqpsLimit\x12J\n" +
	"\x13public_chat_enabled\x18\a \x01(\v2\x1a.google.protobuf.BoolValueR\x11publicChatEnabled\"`\n" +
	"\x14CreateAPIKeyResponse\x12/\n" +
	"\aapi_key\x18\x01 \x01(\v2\x16.api.apimgmt.v1.APIKeyR\x06apiKey\x12\x17\n" +
	"\araw_key\x18\x02 \x01(\tR\x06rawKey\"Y\n" +
	"\x12ListAPIKeysRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"C\n" +
	"\x13ListAPIKeysResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.api.apimgmt.v1.APIKeyR\x05items\"\"\n" +
	"\x10GetAPIKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x11GetAPIKeyResponse\x12/\n" +
	"\aapi_key\x18\x01 \x01(\v2\x16.api.apimgmt.v1.APIKeyR\x06apiKey\"\xd0\x02\n" +
	"\x13UpdateAPIKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12!\n" +
	"\fapi_versions\x18\x05 \x03(\tR\vapiVersions\x12<\n" +
	"\vquota_daily\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"quotaDaily\x128\n" +
	"\tqps_limit\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueR\bqpsLimit\x12J\n" +
	"\x13public_chat_enabled\x18\b \x01(\v2\x1a.google.protobuf.BoolValueR\x11publicChatEnabled\"G\n" +
	"\x14UpdateAPIKeyResponse\x12/\n" +
	"\aapi_key\x18\x01 \x01(\v2\x16.api.apimgmt.v1.APIKeyR\x06apiKey\"%\n" +
	"\x13DeleteAPIKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13RotateAPIKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"`\n" +
	"\x14RotateAPIKeyResponse\x12/\n" +
	"\aapi_key\x18\x01 \x01(\v2\x16.api.apimgmt.v1.APIKeyR\x06apiKey\x12\x17\n" +
	"\araw_key\x18\x02 \x01(\tR\x06rawKey\"/\n" +
	"\x1dRegeneratePublicChatIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x1eRegeneratePublicChatIDResponse\x12/\n" +
	"\aapi_key\x18\x01 \x01(\v2\x16.api.apimgmt.v1.APIKeyR\x06apiKey\"\xa2\x02\n" +
	"\x14ListUsageLogsRequest\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x01 \x01(\tR\bapiKeyId\x12\x15\n" +
	"\x06bot_id\x18\x02 \x01(\tR\x05botId\x12\x1f\n" +
	"\vapi_version\x18\x03 \x01(\tR\n" +
	"apiVersion\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\b \x01(\x05R\x06offset\"G\n" +
	"\x15ListUsageLogsResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.api.apimgmt.v1.UsageLogR\x05items\"\xf6\x01\n" +
	"\x16GetUsageSummaryRequest\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x01 \x01(\tR\bapiKeyId\x12\x15\n" +
	"\x06bot_id\x18\x02 \x01(\tR\x05botId\x12\x1f\n" +
	"\vapi_version\x18\x03 \x01(\tR\n" +
	"apiVersion\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"Q\n" +
	"\x17GetUsageSummaryResponse\x126\n" +
	"\asummary\x18\x01 \x01(\v2\x1c.api.apimgmt.v1.UsageSummaryR\asummary\"\xbc\x02\n" +
	"\x16ExportUsageLogsRequest\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x01 \x01(\tR\bapiKeyId\x12\x15\n" +
	"\x06bot_id\x18\x02 \x01(\tR\x05botId\x12\x1f\n" +
	"\vapi_version\x18\x03 \x01(\tR\n" +
	"apiVersion\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\b \x01(\x05R\x06offset\x12\x16\n" +
	"\x06format\x18\t \x01(\tR\x06format\"\xb4\x01\n" +
	"\x17ExportUsageLogsResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12!\n" +
	"\fdownload_url\x18\x04 \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"object_uri\x18\x05 \x01(\tR\tobjectUri2\xbf\n" +
	"\n" +
	"\x0eConsoleAPIMgmt\x12z\n" +
	"\fCreateAPIKey\x12#.api.apimgmt.v1.CreateAPIKeyRequest\x1a$.api.apimgmt.v1.CreateAPIKeyResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/console/v1/api_keys\x12t\n" +
	"\vListAPIKeys\x12\".api.apimgmt.v1.ListAPIKeysRequest\x1a#.api.apimgmt.v1.ListAPIKeysResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/console/v1/api_keys\x12s\n" +
	"\tGetAPIKey\x12 .api.apimgmt.v1.GetAPIKeyRequest\x1a!.api.apimgmt.v1.GetAPIKeyResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/console/v1/api_keys/{id}\x12\x7f\n" +
	"\fUpdateAPIKey\x12#.api.apimgmt.v1.UpdateAPIKeyRequest\x1a$.api.apimgmt.v1.UpdateAPIKeyResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*2\x19/console/v1/api_keys/{id}\x12n\n" +
	"\fDeleteAPIKey\x12#.api.apimgmt.v1.DeleteAPIKeyRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b*\x19/console/v1/api_keys/{id}\x12\x86\x01\n" +
	"\fRotateAPIKey\x12#.api.apimgmt.v1.RotateAPIKeyRequest\x1a$.api.apimgmt.v1.RotateAPIKeyResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /console/v1/api_keys/{id}/rotate\x12\xb4\x01\n" +
	"\x16RegeneratePublicChatID\x12-.api.apimgmt.v1.RegeneratePublicChatIDRequest\x1a..api.apimgmt.v1.RegeneratePublicChatIDResponse\";\x82\xd3\xe4\x93\x025:\x01*\"0/console/v1/api_keys/{id}/public_chat/regenerate\x12{\n" +
	"\rListUsageLogs\x12$.api.apimgmt.v1.ListUsageLogsRequest\x1a%.api.apimgmt.v1.ListUsageLogsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/console/v1/api_usage\x12\x89\x01\n" +
	"\x0fGetUsageSummary\x12&.api.apimgmt.v1.GetUsageSummaryRequest\x1a'.api.apimgmt.v1.GetUsageSummaryResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/console/v1/api_usage/summary\x12\x8b\x01\n" +
	"\x0fExportUsageLogs\x12&.api.apimgmt.v1.ExportUsageLogsRequest\x1a'.api.apimgmt.v1.ExportUsageLogsResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/console/v1/api_usage/exportB8Z6github.com/ZTH7/RagoDesk/apps/server/api/apimgmt/v1;v1b\x06proto3"

var (
	file_api_apimgmt_v1_console_apimgmt_proto_rawDescOnce sync.Once
	file_api_apimgmt_v1_console_apimgmt_proto_rawDescData []byte
)

func file_api_apimgmt_v1_console_apimgmt_proto_rawDescGZIP() []byte {
	file_api_apimgmt_v1_console_apimgmt_proto_rawDescOnce.Do(func() {
		file_api_apimgmt_v1_console_apimgmt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_apimgmt_v1_console_apimgmt_proto_rawDesc), len(file_api_apimgmt_v1_console_apimgmt_proto_rawDesc)))
	})
	return file_api_apimgmt_v1_console_apimgmt_proto_rawDescData
}

var file_api_apimgmt_v1_console_apimgmt_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_apimgmt_v1_console_apimgmt_proto_goTypes = []any{
	(*APIKey)(nil),                         // 0: api.apimgmt.v1.APIKey
	(*UsageLog)(nil),                       // 1: api.apimgmt.v1.UsageLog
	(*UsageSummary)(nil),                   // 2: api.apimgmt.v1.UsageSummary
	(*CreateAPIKeyRequest)(nil),            // 3: api.apimgmt.v1.CreateAPIKeyRequest
	(*CreateAPIKeyResponse)(nil),           // 4: api.apimgmt.v1.CreateAPIKeyResponse
	(*ListAPIKeysRequest)(nil),             // 5: api.apimgmt.v1.ListAPIKeysRequest
	(*ListAPIKeysResponse)(nil),            // 6: api.apimgmt.v1.ListAPIKeysResponse
	(*GetAPIKeyRequest)(nil),               // 7: api.apimgmt.v1.GetAPIKeyRequest
	(*GetAPIKeyResponse)(nil),              // 8: api.apimgmt.v1.GetAPIKeyResponse
	(*UpdateAPIKeyRequest)(nil),            // 9: api.apimgmt.v1.UpdateAPIKeyRequest
	(*UpdateAPIKeyResponse)(nil),           // 10: api.apimgmt.v1.UpdateAPIKeyResponse
	(*DeleteAPIKeyRequest)(nil),            // 11: api.apimgmt.v1.DeleteAPIKeyRequest
	(*RotateAPIKeyRequest)(nil),            // 12: api.apimgmt.v1.RotateAPIKeyRequest
	(*RotateAPIKeyResponse)(nil),           // 13: api.apimgmt.v1.RotateAPIKeyResponse
	(*RegeneratePublicChatIDRequest)(nil),  // 14: api.apimgmt.v1.RegeneratePublicChatIDRequest
	(*RegeneratePublicChatIDResponse)(nil), // 15: api.apimgmt.v1.RegeneratePublicChatIDResponse
	(*ListUsageLogsRequest)(nil),           // 16: api.apimgmt.v1.ListUsageLogsRequest
	(*ListUsageLogsResponse)(nil),          // 17: api.apimgmt.v1.ListUsageLogsResponse
	(*GetUsageSummaryRequest)(nil),         // 18: api.apimgmt.v1.GetUsageSummaryRequest
	(*GetUsageSummaryResponse)(nil),        // 19: api.apimgmt.v1.GetUsageSummaryResponse
	(*ExportUsageLogsRequest)(nil),         // 20: api.apimgmt.v1.ExportUsageLogsRequest
	(*ExportUsageLogsResponse)(nil),        // 21: api.apimgmt.v1.ExportUsageLogsResponse
	(*timestamppb.Timestamp)(nil),          // 22: google.protobuf.Timestamp
	(*wrapperspb.BoolValue)(nil),           // 23: google.protobuf.BoolValue
	(*wrapperspb.Int32Value)(nil),          // 24: google.protobuf.Int32Value
	(*emptypb.Empty)(nil),                  // 25: google.protobuf.Empty
}
var file_api_apimgmt_v1_console_apimgmt_proto_depIdxs = []int32{
	22, // 0: api.apimgmt.v1.APIKey.created_at:type_name -> google.protobuf.Timestamp
	22, // 1: api.apimgmt.v1.APIKey.last_used_at:type_name -> google.protobuf.Timestamp
	22, // 2: api.apimgmt.v1.UsageLog.created_at:type_name -> google.protobuf.Timestamp
	23, // 3: api.apimgmt.v1.CreateAPIKeyRequest.public_chat_enabled:type_name -> google.protobuf.BoolValue
	0,  // 4: api.apimgmt.v1.CreateAPIKeyResponse.api_key:type_name -> api.apimgmt.v1.APIKey
	0,  // 5: api.apimgmt.v1.ListAPIKeysResponse.items:type_name -> api.apimgmt.v1.APIKey
	0,  // 6: api.apimgmt.v1.GetAPIKeyResponse.api_key:type_name -> api.apimgmt.v1.APIKey
	24, // 7: api.apimgmt.v1.UpdateAPIKeyRequest.quota_daily:type_name -> google.protobuf.Int32Value
	24, // 8: api.apimgmt.v1.UpdateAPIKeyRequest.qps_limit:type_name -> google.protobuf.Int32Value
	23, // 9: api.apimgmt.v1.UpdateAPIKeyRequest.public_chat_enabled:type_name -> google.protobuf.BoolValue
	0,  // 10: api.apimgmt.v1.UpdateAPIKeyResponse.api_key:type_name -> api.apimgmt.v1.APIKey
	0,  // 11: api.apimgmt.v1.RotateAPIKeyResponse.api_key:type_name -> api.apimgmt.v1.APIKey
	0,  // 12: api.apimgmt.v1.RegeneratePublicChatIDResponse.api_key:type_name -> api.apimgmt.v1.APIKey
	22, // 13: api.apimgmt.v1.ListUsageLogsRequest.start_time:type_name -> google.protobuf.Timestamp
	22, // 14: api.apimgmt.v1.ListUsageLogsRequest.end_time:type_name -> google.protobuf.Timestamp
	1,  // 15: api.apimgmt.v1.ListUsageLogsResponse.items:type_name -> api.apimgmt.v1.UsageLog
	22, // 16: api.apimgmt.v1.GetUsageSummaryRequest.start_time:type_name -> google.protobuf.Timestamp
	22, // 17: api.apimgmt.v1.GetUsageSummaryRequest.end_time:type_name -> google.protobuf.Timestamp
	2,  // 18: api.apimgmt.v1.GetUsageSummaryResponse.summary:type_name -> api.apimgmt.v1.UsageSummary
	22, // 19: api.apimgmt.v1.ExportUsageLogsRequest.start_time:type_name -> google.protobuf.Timestamp
	22, // 20: api.apimgmt.v1.ExportUsageLogsRequest.end_time:type_name -> google.protobuf.Timestamp
	3,  // 21: api.apimgmt.v1.ConsoleAPIMgmt.CreateAPIKey:input_type -> api.apimgmt.v1.CreateAPIKeyRequest
	5,  // 22: api.apimgmt.v1.ConsoleAPIMgmt.ListAPIKeys:input_type -> api.apimgmt.v1.ListAPIKeysRequest
	7,  // 23: api.apimgmt.v1.ConsoleAPIMgmt.GetAPIKey:input_type -> api.apimgmt.v1.GetAPIKeyRequest
	9,  // 24: api.apimgmt.v1.ConsoleAPIMgmt.UpdateAPIKey:input_type -> api.apimgmt.v1.UpdateAPIKeyRequest
	11, // 25: api.apimgmt.v1.ConsoleAPIMgmt.DeleteAPIKey:input_type -> api.apimgmt.v1.DeleteAPIKeyRequest
	12, // 26: api.apimgmt.v1.ConsoleAPIMgmt.RotateAPIKey:input_type -> api.apimgmt.v1.RotateAPIKeyRequest
	14, // 27: api.apimgmt.v1.ConsoleAPIMgmt.RegeneratePublicChatID:input_type -> api.apimgmt.v1.RegeneratePublicChatIDRequest
	16, // 28: api.apimgmt.v1.ConsoleAPIMgmt.ListUsageLogs:input_type -> api.apimgmt.v1.ListUsageLogsRequest
	18, // 29: api.apimgmt.v1.ConsoleAPIMgmt.GetUsageSummary:input_type -> api.apimgmt.v1.GetUsageSummaryRequest
	20, // 30: api.apimgmt.v1.ConsoleAPIMgmt.ExportUsageLogs:input_type -> api.apimgmt.v1.ExportUsageLogsRequest
	4,  // 31: api.apimgmt.v1.ConsoleAPIMgmt.CreateAPIKey:output_type -> api.apimgmt.v1.CreateAPIKeyResponse
	6,  // 32: api.apimgmt.v1.ConsoleAPIMgmt.ListAPIKeys:output_type -> api.apimgmt.v1.ListAPIKeysResponse
	8,  // 33: api.apimgmt.v1.ConsoleAPIMgmt.GetAPIKey:output_type -> api.apimgmt.v1.GetAPIKeyResponse
	10, // 34: api.apimgmt.v1.ConsoleAPIMgmt.UpdateAPIKey:output_type -> api.apimgmt.v1.UpdateAPIKeyResponse
	25, // 35: api.apimgmt.v1.ConsoleAPIMgmt.DeleteAPIKey:output_type -> google.protobuf.Empty
	13, // 36: api.apimgmt.v1.ConsoleAPIMgmt.RotateAPIKey:output_type -> api.apimgmt.v1.RotateAPIKeyResponse
	15, // 37: api.apimgmt.v1.ConsoleAPIMgmt.RegeneratePublicChatID:output_type -> api.apimgmt.v1.RegeneratePublicChatIDResponse
	17, // 38: api.apimgmt.v1.ConsoleAPIMgmt.ListUsageLogs:output_type -> api.apimgmt.v1.ListUsageLogsResponse
	19, // 39: api.apimgmt.v1.ConsoleAPIMgmt.GetUsageSummary:output_type -> api.apimgmt.v1.GetUsageSummaryResponse
	21, // 40: api.apimgmt.v1.ConsoleAPIMgmt.ExportUsageLogs:output_type -> api.apimgmt.v1.ExportUsageLogsResponse
	31, // [31:41] is the sub-list for method output_type
	21, // [21:31] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_api_apimgmt_v1_console_apimgmt_proto_init() }
func file_api_apimgmt_v1_console_apimgmt_proto_init() {
	if File_api_apimgmt_v1_console_apimgmt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_apimgmt_v1_console_apimgmt_proto_rawDesc), len(file_api_apimgmt_v1_console_apimgmt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_apimgmt_v1_console_apimgmt_proto_goTypes,
		DependencyIndexes: file_api_apimgmt_v1_console_apimgmt_proto_depIdxs,
		MessageInfos:      file_api_apimgmt_v1_console_apimgmt_proto_msgTypes,
	}.Build()
	File_api_apimgmt_v1_console_apimgmt_proto = out.File
	file_api_apimgmt_v1_console_apimgmt_proto_goTypes = nil
	file_api_apimgmt_v1_console_apimgmt_proto_depIdxs = nil
}
