// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	analyticsbiz "github.com/ZTH7/RagoDesk/apps/server/internal/analytics/biz"
	analyticsdata "github.com/ZTH7/RagoDesk/apps/server/internal/analytics/data"
	analyticsservice "github.com/ZTH7/RagoDesk/apps/server/internal/analytics/service"
	apimgmtbiz "github.com/ZTH7/RagoDesk/apps/server/internal/apimgmt/biz"
	apimgmtdata "github.com/ZTH7/RagoDesk/apps/server/internal/apimgmt/data"
	apimgmtservice "github.com/ZTH7/RagoDesk/apps/server/internal/apimgmt/service"
	authnbiz "github.com/ZTH7/RagoDesk/apps/server/internal/authn/biz"
	authndata "github.com/ZTH7/RagoDesk/apps/server/internal/authn/data"
	authnservice "github.com/ZTH7/RagoDesk/apps/server/internal/authn/service"
	botbiz "github.com/ZTH7/RagoDesk/apps/server/internal/bot/biz"
	botdata "github.com/ZTH7/RagoDesk/apps/server/internal/bot/data"
	botservice "github.com/ZTH7/RagoDesk/apps/server/internal/bot/service"
	"github.com/ZTH7/RagoDesk/apps/server/internal/conf"
	conversationbiz "github.com/ZTH7/RagoDesk/apps/server/internal/conversation/biz"
	conversationdata "github.com/ZTH7/RagoDesk/apps/server/internal/conversation/data"
	conversationservice "github.com/ZTH7/RagoDesk/apps/server/internal/conversation/service"
	"github.com/ZTH7/RagoDesk/apps/server/internal/data"
	iambiz "github.com/ZTH7/RagoDesk/apps/server/internal/iam/biz"
	iamdata "github.com/ZTH7/RagoDesk/apps/server/internal/iam/data"
	iamservice "github.com/ZTH7/RagoDesk/apps/server/internal/iam/service"
	knowledgebiz "github.com/ZTH7/RagoDesk/apps/server/internal/knowledge/biz"
	knowledgedata "github.com/ZTH7/RagoDesk/apps/server/internal/knowledge/data"
	knowledgeservice "github.com/ZTH7/RagoDesk/apps/server/internal/knowledge/service"
	ragbiz "github.com/ZTH7/RagoDesk/apps/server/internal/rag/biz"
	ragdata "github.com/ZTH7/RagoDesk/apps/server/internal/rag/data"
	ragservice "github.com/ZTH7/RagoDesk/apps/server/internal/rag/service"
	"github.com/ZTH7/RagoDesk/apps/server/internal/server"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	apimgmtRepo := apimgmtdata.NewAPIMgmtRepo(dataData, logger)
	usageExporter := apimgmtdata.NewUsageExporter(confData, logger)
	rateLimiter := apimgmtdata.NewRateLimiter(confData, logger)
	usageSink := apimgmtbiz.NewUsageSink()
	apimgmtUsecase := apimgmtbiz.NewAPIMgmtUsecase(apimgmtRepo, usageExporter, rateLimiter, usageSink, confData, logger)
	conversationRepo := conversationdata.NewConversationRepo(dataData)
	conversationUsecase := conversationbiz.NewConversationUsecase(conversationRepo, confData)
	analyticsRepo := analyticsdata.NewAnalyticsRepo(dataData)
	analyticsUsecase := analyticsbiz.NewAnalyticsUsecase(analyticsRepo, logger)
	conversationService := conversationservice.NewConversationService(conversationUsecase, apimgmtUsecase, analyticsUsecase)
	iamRepo := iamdata.NewIAMRepo(dataData, logger)
	iamUsecase := iambiz.NewIAMUsecase(iamRepo, logger)
	iamService := iamservice.NewIAMService(iamUsecase, logger)
	authRepo := authndata.NewAuthRepo(dataData, logger)
	authUsecase := authnbiz.NewAuthUsecase(authRepo, confServer, logger)
	consoleAuthService := authnservice.NewConsoleAuthService(authUsecase)
	platformAuthService := authnservice.NewPlatformAuthService(authUsecase)
	botRepo := botdata.NewBotRepo(dataData, logger)
	botUsecase := botbiz.NewBotUsecase(botRepo, logger)
	botService := botservice.NewBotService(botUsecase, iamUsecase)
	apimgmtService := apimgmtservice.NewAPIMgmtService(apimgmtUsecase, iamUsecase, logger)
	analyticsService := analyticsservice.NewAnalyticsService(analyticsUsecase, iamUsecase, logger)
	knowledgeRepo := knowledgedata.NewKnowledgeRepo(dataData, confData, logger)
	ingestionQueue := knowledgedata.NewIngestionQueue(confData, logger)
	knowledgeUsecase := knowledgebiz.NewKnowledgeUsecase(knowledgeRepo, ingestionQueue, confData, logger)
	knowledgeService := knowledgeservice.NewKnowledgeService(knowledgeUsecase, iamUsecase, logger)
	ragKBRepo := ragdata.NewKBRepo(dataData)
	ragVectorRepo := ragdata.NewVectorRepo(confData)
	ragChunkRepo := ragdata.NewChunkRepo(dataData)
	ragUsecase, err := ragbiz.NewRAGUsecase(ragKBRepo, ragVectorRepo, ragChunkRepo, confData, logger)
	if err != nil {
		return nil, nil, err
	}
	ragService := ragservice.NewRAGService(ragUsecase, conversationUsecase, apimgmtUsecase, analyticsUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, iamService, knowledgeService, ragService, conversationService, apimgmtService, analyticsService, botService, consoleAuthService, platformAuthService)
	httpServer := server.NewHTTPServer(confServer, logger, iamService, knowledgeService, ragService, conversationService, apimgmtService, analyticsService, botService, consoleAuthService, platformAuthService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
